### ISSUE TITLE
AppStore submit fail 

### ISSUE THREAD

**Issue by adrianilie9** [DataDog/dd-sdk-ios#1015]
### The issue

When I submit the app to the App Store using Transporter I get the following error:

`"This bundle is invalid. The bundle at path Payload/AppName.app/Frameworks/_Datadog_Private.framework has an invalid CFBundleIdentifier '_Datadog_Private' There are invalid characters(characters that are not dots, hyphen and alphanumerics) that have been replaced with their code point '\u005fDatadog\u005fPrivate' CFBundleIdentifier must be present, must contain only alphanumerics, dots, hyphens and must not end with a dot. [see the Core Foundation Keys at https://developer.apple.com/library/content/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html#//apple_ref/doc/uid/TP40009249-102070-TPXREF105]"`

---

#### Datadog SDK version:

1.12.0

#### Last working Datadog SDK version:

N/A

#### Dependency Manager:

SPM

#### Other toolset:

- tuist
- fastlane

#### Xcode version:

14.0.1

#### Swift version:

5.7

#### Deployment Target:

iPhone, iOS 13.0

#### macOS version:

macOS 12.6

**Comment by maxep** [comment]
Hello @adrianilie9 ! Thanks for using our SDK :)

Is it the first time you try to submit your app with Datadog? Could you share a bit more your configuration and how you setup the dependency in your Tuist `Project.swift`?
Thank you!

**Comment by adrianilie9** [comment]
Hey @maxep, thanks for helping out.

Yes, it's the first time submitting since integrating Datadog.

The setup consists of a single Xcode workspace, outputting multiple targets.

```
public extension Package {
    static let datadog: Package = .remote(url: "https://github.com/DataDog/dd-sdk-ios.git", requirement: .exact("1.12.0"))
}

public extension TargetDependency {
    static let datadog: TargetDependency = .package(product: "Datadog")
    static let datadogCrashReporting: TargetDependency = .package(product: "DatadogCrashReporting")
}

private let application: Target = .app(
	appName: appName,
	resourceTypes: [ .strings, .xib, .other, .storyboard ],
	dependencies: [
            .datadog,
	    .datadogCrashReporting,
            ...
        ],
        ...
)
```

**Comment by maxep** [comment]
Thanks for sharing the snippet!

We have a SPM definition with cross dependencies that is confusing. `DatadogCrashReporting` already depends on `Datadog`, when using SPM you only need to link `DatadogCrashReporting`. 

Can you try the following:
```swift 
public extension Package {
    static let datadog: Package = .remote(url: "https://github.com/DataDog/dd-sdk-ios.git", requirement: .exact("1.12.0"))
}

public extension TargetDependency {
    // static let datadog: TargetDependency = .package(product: "Datadog")
    static let datadogCrashReporting: TargetDependency = .package(product: "DatadogCrashReporting")
}

private let application: Target = .app(
	appName: appName,
	resourceTypes: [ .strings, .xib, .other, .storyboard ],
	dependencies: [
            // .datadog,
	    .datadogCrashReporting,
            ...
        ],
        ...
)
```

If that doesn't work, we will need to investigate and try to reproduce with a blank Tuist project.

**Comment by adrianilie9** [comment]
After some trial & error I've managed to fix the issue.

There is also a separate module (target) that was outputted by the workspace, which also included `.datadog, . datadogCrashReporting` as dependencies. Thing is this module was also a dependency for the app, and after removing both Datadog dependency from the app definition, everything worked. I guess there was some kind of duplicate dependency happening.

Thank you again for your suggestions, will keep it in mind in the future.
