### ISSUE TITLE
PLCrashReporter included even when not using CrashReporting

### ISSUE THREAD

**Issue by Kaspik** [DataDog/dd-sdk-ios#1021]
### The thing
Good evening! We are using Datadog via SPM:

```
dependencies: [
    .package(url: "https://github.com/DataDog/dd-sdk-ios.git", from: "1.12.0")
]
```

We are using it for logging mainly and we are not using RUM or Crash Collecting. I noticed that we still have `PLCrashReporter` as a dependency in our project. Would it be possible to improve the Package.swift and not include this third party (Microsoft) library if not used?

Because we have another crash reporting methods and we have strict privacy policy about third party frameworks, this could cause an issue for us.

Thanks!

**Comment by maxep** [comment]
Hi @Kaspik !

Indeed, the package will be downloaded, this is how SPM behaves. But the library will not be added to your app until you actually link it to a target of your project. We have to describe the entire package description in the `Package.swift`, then you can pick the libraries you need. In your case, if you do not select `DatadogCrashReporting` as a target dependency,  `PLCrashReporter` won't be linked.
I hope this help!

**Comment by maxep** [comment]
Yes, this is actually our current effort :) We are currently working on a `2.0` version of the SDK that can be tracked on the [`feature/v2` branch](https://github.com/DataDog/dd-sdk-ios/tree/feature/v2), the goal is to apply modularity like you described.

Note: `DatadogCrashReporting` can also work with Logs if RUM is disabled. Also, even if we depend on `PLCrashReporter` that is a Microsoft library, no data is shared with Microsoft. It's a library that helps collecting crash information, that data is solely transmitted to Datadog.
