### ISSUE TITLE
Fails during "Copy Datadog" phase

### ISSUE THREAD

**Issue by bbaic** [DataDog/dd-sdk-ios#1037]
### The issue

```
Copy /path/to/DerivedData/{product-name}-bltvnfsvdlcoymdmzjbjqtofzjne/Build/Products/Debug\ DEV-iphonesimulator/{product-name}.app/Frameworks/Datadog /path/to/DerivedData/{product-name}-bltvnfsvdlcoymdmzjbjqtofzjne/Build/Products/Debug\ DEV-iphonesimulator/Datadog (in target '{product-name}' from project '{product-name}')
    cd /path/to/repo
    builtin-copy -exclude .DS_Store -exclude CVS -exclude .svn -exclude .git -exclude .hg -resolve-src-symlinks /path/to/DerivedData/{product-name}-bltvnfsvdlcoymdmzjbjqtofzjne/Build/Products/Debug\ DEV-iphonesimulator/Datadog /path/to/DerivedData/{product-name}-bltvnfsvdlcoymdmzjbjqtofzjne/Build/Products/Debug\ DEV-iphonesimulator/{product-name}.app/Frameworks

**error: /path/to/DerivedData/{product-name}-bltvnfsvdlcoymdmzjbjqtofzjne/Build/Products/Debug DEV-iphonesimulator/Datadog: No such file or directory (in target '{product-name}' from project '{product-name}')**
```
---

#### Datadog SDK version:

1.12.0 and 1.12.1 fail

#### Last working Datadog SDK version:

1.11.1 works

#### Dependency Manager:

SPM

#### Xcode version:

Xcode 14.0.1 (14A400) in Rosetta mode

#### Swift version:

5

#### Deployment Target:

iOS 15.5 simulator

#### macOS version:

macOS 12.6 (21G115) on M1 Max chip

**Comment by bazscott** [comment]
I am also seeing this error with Xcode 14.1 and DD SDK version 1.12.1

**Comment by maxep** [comment]
Hi @bbaic ! Thank you for the report. Tho, there is too few information for us to troubleshoot. Could you share your Build Phases? It should read similar to:
<img width="805" alt="image" src="https://user-images.githubusercontent.com/6815992/200353320-59234fa9-0ad7-4e14-9b79-4bb55cc9d087.png">

**Comment by bbaic** [comment]
<img width="896" alt="Screen Shot 2022-11-11 at 10 41 12 AM" src="https://user-images.githubusercontent.com/1171334/201388193-63e80f13-24b3-4c69-b93d-12982ff93150.png">
@maxep

**Comment by maxep** [comment]
Hey @bbaic ! You can remove `Datadog` from the `Embed Frameworks` section 👍

**Comment by bbaic** [comment]
et voila! Thank you much :D
