### ISSUE TITLE
<unknown>:0: error: missing required module '_Datadog_Private'

### ISSUE THREAD

**Issue by Sachin-Jeeves** [DataDog/dd-sdk-ios#1055]
### Unable to run tests in the project

I have integrated datadog-ios-sdk v1.12.1 through SPM. I am getting this error when running tests.
I am using Xcode 14.0 and SwiftUI

<unknown>:0: error: missing required module '_Datadog_Private'

---

#### Datadog SDK version: v1.12.1 / v1.13.0

**Comment by ncreated** [comment]
Hello @Sachin-Jeeves 👋. This could be the same problem as https://github.com/DataDog/dd-sdk-ios/issues/1040. What's there in your _"Frameworks, Libraries and Embedded Content"_ configuration? You should set `Datadog` in there:

<img width="842" alt="Screenshot 2022-11-17 at 13 01 25" src="https://user-images.githubusercontent.com/2358722/202441218-222ed06c-aec4-4415-a9a8-67c449d60c05.png">

**Comment by Sachin-Jeeves** [comment]
I do have it. Still getting the error.
<img width="811" alt="Screenshot 2022-11-17 at 8 06 26 PM" src="https://user-images.githubusercontent.com/101637953/202474783-77724e7f-45cb-42b9-bc83-c10ab13e8f02.png">
<img width="655" alt="Screenshot 2022-11-17 at 8 06 39 PM" src="https://user-images.githubusercontent.com/101637953/202474835-73cbec52-9c07-4b07-b5e7-33a9a64bf0bc.png">

Just a note, while adding the package - I only selected DatadogCrashReporting.

**Comment by Sachin-Jeeves** [comment]
I tried by upgrading to Xcode 14.1, but seems to have the same issue

**Comment by ncreated** [comment]
@Sachin-Jeeves you seem to be missing `Datadog` as a dependency. `DatadogCrashReporting` is our add-on for integrating crash reporting, but it needs `Datadog` to also be present there. Let me know if this helps 🙌.

**Comment by Sachin-Jeeves** [comment]
@ncreated I tried this one too and failed. I also created a new project using Xcode 14.1 & SwiftUI -> added dependency, but as soon as I do testable import -> the tests don't compile and throw this error of missing required module.

**Comment by ttrznadel** [comment]
Same problem, any solution?

**Comment by TarekSalama** [comment]
> Same problem, any solution?
> 
> import Datadog Missing required module '_Datadog_Private'

Check this https://github.com/DataDog/dd-sdk-ios/issues/1040#event-7915496526

**Comment by maxep** [comment]
Closing in favor of #1085
