### ISSUE TITLE
I can't find documentation on which packages to import into project

### ISSUE THREAD

**Issue by jonas-simkus-mw** [DataDog/dd-sdk-ios#1064]
### There is no documentation of which packages are for what, which ones I should import

When using Swift Package Manager to import DataDog SDK into Xcode project, it asks to choose which internal packages I want to import, but clearly it either does not exists or is somewhere hidden out of site explanation on what each of them are for.

These are the packages I'm asked to choose from, but not told what each of them are for (with one exception being `*Crash*`):
- Datadog
- DatadogCrashReporting
- DatadogDynamic
- DatadogDynamicObjc
- DatadogObjc
- DatadogStatic
- DatadogStaticObjc

Can we have this covered in README?
Or at least a link to where this is documented.

**Comment by maxep** [comment]
Hi @jonas-simkus-mw 👋 

The Datadog SDK has 3 packages: 
- `Datadog`: the main library with Logs, RUM, and Traces features
- `DatadogObjc`: objective-c interfaces of `Datadog`
- `DatadogCrashReporting`: Crash Reporting feature

The `Static` and `Dynamic` suffixes describe the linking of the library ([here a good read of dynamic vs. static linking](https://pratheeshbennet.medium.com/static-library-vs-dynamic-library-in-ios-55478ed53a03)), if you ever want to force the linking type for a specific use case.

It is recommended to import a lib with no linking type specified, to let SPM decide which is best in your context. So you can pick either `Datadog`, `DatadogObjc`, or `DatadogCrashReporting` based on your need. I agree our documentation for SPM lack some details, but we plan on doing updates soon.

I hope this helps!
