### ISSUE TITLE
SDK failed to compile, Xcode 14 + Swift 5.7.2/5.7

### ISSUE THREAD

**Issue by InfinityCode777** [DataDog/dd-sdk-ios#1106]
### The issue

📝 Give us the error message you receive, describe the problem and answer the questions.

---

#### Datadog SDK version:

_Which version of the Datadog SDK causes this problem? e.g. `1.14.0`_

#### Last working Datadog SDK version:

_What is the last Datadog SDK version where this problem didn't occur? e.g. `1.10.0`_

#### Dependency Manager:

_Which dependency manager do you use? Carthage_

#### Other toolset:

_Do you use additional tools with your dependency manager? No_

#### Xcode version:

_e.g. `Xcode 14.2 (14C18)`_

#### Swift version:

_e.g. `5.7.2`_

#### Deployment Target:

_What is the Deployment Target of your app?  `iOS 14`,  `iPad`_

#### macOS version:

_e.g. `macOS Monterey 12.6.1 (21G217)`_

### Problem Description
Tried to compile the SDK alone using the following command

```
carthage update dd-sdk-ios --platform iOS --use-xcframeworks --no-use-binaries --cache-builds
```

and I got this error 

```
A shell task (/usr/bin/xcrun xcodebuild -project /Users/jingwang/Documents/XcodeProject/app-ios-figur8/Figur8DeviceSDK/Vendor/Carthage/Checkouts/dd-sdk-ios/dependency-manager-tests/cocoapods/CPProject.xcodeproj -scheme CPProject -configuration Release CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -showBuildSettings -skipUnavailableActions) failed with exit code 6:
2022-12-28 21:22:09.961 xcodebuild[4491:51603] [MT] DVTAssertions: ASSERTION FAILURE in /System/Volumes/Data/SWE/Apps/DT/BuildRoots/BuildRoot2/ActiveBuildRoot/Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-21534/IDEFoundation/Execution/RunDestinations/IDERunDestinationCLI.m:566
Details:  Unhandled/unexpected case where no run destinations were produced.
Object:   <IDERunDestinationCLI>
Method:   +resolveRunDestinationsWithWorkspace:scheme:buildAction:schemeCommand:schemeTask:destinationSpecifications:architectures:timeout:runDestinationManager:deviceManager:fallbackPreferredSDK:fallbackPreferredArchitectures:skipUnsupportedDestinations:shouldSkipRunDestinationValidation:didDisambiguate:disambiguatedMatches:disambiguatedMatchesDescription:error:
Thread:   <_NSMainThread: 0x600002178400>{number = 1, name = main}
Hints:

Backtrace:
  0   -[DVTAssertionHandler handleFailureInMethod:object:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1   _DVTAssertionHandler (in DVTFoundation)
  2   _DVTAssertionFailureHandler (in DVTFoundation)
  3   +[IDERunDestinationCLI resolveRunDestinationsWithWorkspace:scheme:buildAction:schemeCommand:schemeTask:destinationSpecifications:architectures:timeout:runDestinationManager:deviceManager:fallbackPreferredSDK:fallbackPreferredArchitectures:skipUnsupportedDestinations:shouldSkipRunDestinationValidation:didDisambiguate:disambiguatedMatches:disambiguatedMatchesDescription:error:] (in IDEFoundation)
  4   -[Xcode3CommandLineBuildTool _resolveRunDestinationsForBuildAction:] (in Xcode3Core)
  5   -[Xcode3CommandLineBuildTool _resolveInputOptionsWithTimingSection:] (in Xcode3Core)
  6   -[Xcode3CommandLineBuildTool run] (in Xcode3Core)
  7   XcodeBuildMain (in libxcodebuildLoader.dylib)
  8   start (in dyld)
```

I tried to use lower version command line tool to compile the SDK (Xcode 14.0, 14A309) but I got the same error above. I checked out the project. When I tried to build the target `DatadogCrashReporting iOS`, it failed to compile with the following error

<img width="1143" alt="image" src="https://user-images.githubusercontent.com/8001169/209904070-de7366c7-f5e5-4d34-904b-6ae64176bbb1.png">

**Comment by ncreated** [comment]
Hello @InfinityCode777 👋. I've been looking into this issue, but cannot reproduce it on my end. I do following and it works (Xcode 14.2, macOS Monterey 12.6.1, Apple Silicon, Carthage 0.38.0):

`Cartfile`:
```
github "DataDog/dd-sdk-ios"
```

```sh
❯ carthage update  --platform iOS --use-xcframeworks --no-use-binaries
*** Fetching dd-sdk-ios
*** Fetching plcrashreporter
*** Checking out plcrashreporter at "1.11.0"
*** Checking out dd-sdk-ios at "1.14.0"
*** xcodebuild output can be found in /var/folders/lh/0w6f67557dq4g8ky8r8_96_80000gp/T/carthage-xcodebuild.VqTW5Q.log
*** Building scheme "CrashReporter iOS Framework" in CrashReporter.xcodeproj
*** Building scheme "Datadog iOS" in Datadog.xcworkspace
*** Building scheme "DatadogCrashReporting iOS" in Datadog.xcworkspace
*** Building scheme "DatadogObjc iOS" in Datadog.xcworkspace
```

Also, performing exactly your setup works fine:
```sh
❯ carthage update dd-sdk-ios --platform iOS --use-xcframeworks --no-use-binaries --cache-builds
*** Cloning dd-sdk-ios
*** Cloning plcrashreporter
*** Checking out plcrashreporter at "1.11.0"
*** Checking out dd-sdk-ios at "1.14.0"
*** No cache found for plcrashreporter, building with all downstream dependencies
*** xcodebuild output can be found in /var/folders/lh/0w6f67557dq4g8ky8r8_96_80000gp/T/carthage-xcodebuild.HdBZyB.log
*** Building scheme "CrashReporter iOS Framework" in CrashReporter.xcodeproj
*** Building scheme "Datadog iOS" in Datadog.xcworkspace
*** Building scheme "DatadogCrashReporting iOS" in Datadog.xcworkspace
*** Building scheme "DatadogObjc iOS" in Datadog.xcworkspace
```

Which makes me thing this is rather a problem with your setup or env. I only wonder why it attempts to build our test utility project `CPProject.xcodeproj -scheme CPProject` on your machine 🤔💭.

Few troubleshooting hints to move forward:
- What is your Carthage version? (`carthage version`)
- Because you use `--cache-builds`, have you tried [clearing up Carthage's cache](https://stackoverflow.com/questions/45504896/how-to-clear-carthage-cache)?
- What is the exact `carthage update ...` output you see in Terminal? 
- Last, do you try on Apple Silicon Mac or Intel one?

**Comment by InfinityCode777** [comment]
* What is your Carthage version? (carthage version)
   *  0.38.0
* Because you use --cache-builds, have you tried [clearing up Carthage's cache](https://stackoverflow.com/questions/45504896/how-to-clear-carthage-cache)?
   * Yes I did 
* What is the exact carthage update ... output you see in Terminal?
   * Please see my original post. Also, any idea that `DatadogCrashReporting iOS` failed to compmile? Would that be the possible reason? Also, do you have a non dev laptop, can you try the same command
* Last, do you try on Apple Silicon Mac or Intel one?
   * It uses silicon M1 chip

Here is my Cartfile
```
jingwang@jing-MacBook-Pro ~ % cd Documents/XcodeProject/app-ios-figur8
jingwang@jing-MacBook-Pro app-ios-figur8 % cd Figur8DeviceSDK/Vendor
jingwang@jing-MacBook-Pro Vendor % cat Cartfile
github "Rightpoint/Anchorage" >= 4.2.1
github "Alamofire/Alamofire" >= 4.7.3
github "danielgindi/Charts" == 4.0.0
github "auth0/Auth0.swift" >= 2.0
github "AliSoftware/OHHTTPStubs"
github "DataDog/dd-sdk-ios"

binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseAnalyticsBinary.json" == 8.9.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebasePerformanceBinary.json" == 8.9.0
binary "https://dl.google.com/dl/firebase/ios/carthage/FirebaseCrashlyticsBinary.json" == 8.9.0
```
