### ISSUE TITLE
SDK compilation failures in Xcode 14.2/Swift 5.7.2/Ventura 13.1 with versions 1.12.0 to 1.14.0

### ISSUE THREAD

**Issue by awaltzforvenus** [DataDog/dd-sdk-ios#1142]
### The issue

Seeing issues when compiling a project with any version of the SDK newer than `1.11.1` — specifically, it looks like a linking error:

```/Users/[redacted]/Library/Developer/Xcode/DerivedData/[redacted]/Build/Products/Debug-iphonesimulator/Datadog: No such file or directory```

It's worth noting that this is a project that also uses Quick/Nimble as dedicated dependencies (specifically, versions `6.1.0` and `11.2.1` at time of writing; we set all of our SPM dependencies to match exact versions, rather than ranges), since that seems to be potentially related to other similar issues reported that I've seen (but isn't conclusive). When I navigate to that directory, I do see `Datadog.o` and `Datadog.swiftmodule`, so I'm not sure why the linker isn't finding them.

Not sure what else I should be looking for, or may be missing?

#### Datadog SDK version:

Any version from `1.12.0` to `1.14.0` (latest at time of writing)

#### Last working Datadog SDK version:

`1.11.1`

#### Dependency Manager:

SPM

#### Other toolset:

Nope!

#### Xcode version:

`14.2 (14C18)`

#### Swift version:

`5.7.2`

#### Deployment Target:

`iOS 15.0`, `iPhone` + `iPad`

#### macOS version:

`macOS Ventura 13.1 (22C65)`

**Comment by maxep** [comment]
Hey @awaltzforvenus 👋 

What modules are you linking to? Only [`Datadog`](https://github.com/DataDog/dd-sdk-ios/blob/develop/Package.swift#L13), or any other package?

**Comment by vani2** [comment]
I had a similar issue, but it was resolved by removing SDK and adding again and linking only `DataDog.`

**Comment by awaltzforvenus** [comment]
Hi @maxep, thanks for the reply! It was only DataDog, and yes, DerivedData was cleared each time before trying to compile with it again. I had also tried @vani2's suggestion of removing and relinking the base package, but to no avail, unfortunately.

Upon additional review within our team since opening this, we've come to recognize that DD isn't actually serving our use case anyway, and have decided to remove the package from our project for the time being — we can go ahead and close this. Thank you!

**Comment by maxep** [comment]
Hey @awaltzforvenus 👋 

I hope this issue was not a blocker for you, we test our SDK with all dependency managers available, and I'm sure we would have found a solution.
Can I ask you what was your use case we couldn't serve? It's valuable information so we can improve :)
