### ISSUE TITLE
feature: crash logger

### ISSUE THREAD

**Issue by fleficher** [DataDog/dd-sdk-ios#1161]
### The thing

Hi 👋 
On the Android SDK, when the crash reports feature is configured, a logger with the name "crash" is automatically created and logs the errors.

This logger is missing on the iOS SDK. It would be useful to have it, especially to be able to create metrics based on crash logs.

**Comment by maciejburda** [comment]
Hello @fleficher 👋 

Thanks for pointing out the issue. I can confirm that there is a discrepancy between platforms.

I'll discuss with the team and try to prioritise the fix.

**Comment by maciejburda** [comment]
Quick question:
Which features of the SDK do you use simultaneously? It's Crash Reporting and Logs only or also Real User Monitoring?

**Comment by fleficher** [comment]
> Quick question: Which features of the SDK do you use simultaneously? It's Crash Reporting and Logs only or also Real User Monitoring?

Hi @maciejburda we're using crash reporting + logs + RUM.

**Comment by maciejburda** [comment]
Thanks!

Currently on iOS, only RUM crash event will be generated. Currently, there is a discrepancy between platforms, as Android sends crash reports to both RUM and logs. However, our team is working towards resolving this discrepancy in the near future.

**Comment by maxep** [comment]
Hey @fleficher 👋  this was fixed in #1209 and released in [1.17.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.17.0)
