### ISSUE TITLE
XCFrameworks from Github Release don't compile into an empty project.

### ISSUE THREAD

**Issue by iainsmith** [DataDog/dd-sdk-ios#1167]
### The issue

Compilation issues when using `Datadog.xcframework` from Github releases page, in new Xcode Project  due to Swift namespacing issues, in private.swiftinterface.

 - download link [1.15.0](https://github.com/DataDog/dd-sdk-ios/releases/download/1.15.0/Datadog-1.15.0.zip)
---

#### Steps to reproduce

- Create a New Xcode Project
- Download Datadog xcframeworks [1.15.0](https://github.com/DataDog/dd-sdk-ios/releases/download/1.15.0/Datadog-1.15.0.zip) and link into project.
- Build will error from `arm64-apple-ios-simulator.private.swiftinterface`
- Full Build Log - [Build HelloWorld_2023-02-17T15-56-46.txt](https://github.com/DataDog/dd-sdk-ios/files/10768615/Build.HelloWorld_2023-02-17T15-56-46.txt)

Example errors:

```

/Users/iain/Library/Developer/Xcode/DerivedData/HelloWorld-frmivyeoikjlcyfddjefvvbbmfni/Build/Products/Debug-iphonesimulator/Datadog.framework/Modules/Datadog.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface:2365:19: error: 'OTelHTTPHeadersWriter' is not a member type of class 'Datadog.Datadog'
extension Datadog.OTelHTTPHeadersWriter.InjectEncoding : Swift.Equatable {}
          ~~~~~~~ ^
/Users/iain/Library/Developer/Xcode/DerivedData/HelloWorld-frmivyeoikjlcyfddjefvvbbmfni/Build/Products/Debug-iphonesimulator/Datadog.framework/Modules/Datadog.swiftmodule/arm64-apple-ios-simulator.private.swiftinterface:1990:49: note: 'Datadog' declared here
@_hasMissingDesignatedInitializers public class Datadog {
```

#### Datadog SDK version:

1.15.0

#### Last working Datadog SDK version:

Never tried this before

#### Dependency Manager:

- Downloading and install XCFramework manually

#### Other toolset:

- End goal: Integrate through Bazel

#### Xcode version:

Xcode 14.2
Build version 14C18

#### Swift version:

swift-driver version: 1.62.15 Apple Swift version 5.7.2 (swiftlang-5.7.2.135.5 clang-1400.0.29.51)

#### Deployment Target:

N/A

#### macOS version:

12.6.3

**Comment by ncreated** [comment]
Hello @iainsmith 👋. Thanks for opening an issue - we managed to reproduce the problem and we will work on the fix with high priority.

**Comment by maxep** [comment]
Hello @iainsmith! 
I've made a fix in our XCFrameworks build, could you please try with the new binaries in [1.15.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.15.0)?
Thanks again for the report!

**Comment by iainsmith** [comment]
Hi @maxep I tried this again, and it works as a dynamic XCFramework. 

It would be great to have both options for either a dynamic or static XCFramework sometime in the future.
