### ISSUE TITLE
Xcode 14.3 beta support - PLCrashReporter issue

### ISSUE THREAD

**Issue by AvdLee** [DataDog/dd-sdk-ios#1198]
Datadog implements PLCrashReporter, and that dependency results in the following failure:

![CleanShot 2023-03-08 at 11 34 36@2x](https://user-images.githubusercontent.com/4329185/223690401-228e2d88-0194-4fa1-9fdb-f77d685df844.jpg)

I've also created an issue on their end: https://github.com/microsoft/plcrashreporter/issues/276

**Comment by ncreated** [comment]
Hey @AvdLee 👋 - thanks for opening an issue in PLCR repo too (we'll keep track of it). I was trying to reproduce the problem using Xcode 14.3.0-beta2 but it seems to work on my side:

<img width="618" alt="Screenshot 2023-03-09 at 14 58 02" src="https://user-images.githubusercontent.com/2358722/224047802-14915fdb-d949-4fe8-ae7e-dc98d04c6dbc.png">

I'm building for iOS 16.4 Simulator on M1 machine. Installed `dd-sdk-ios` through SPM. What is different compared to your setup?

**Comment by AvdLee** [comment]
Hmm, interesting! It might be related to me using beta 1 still. I would suggest to keep an eye open on this issue until Xcode is out of beta. I'll keep you posted!
