### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException 

### ISSUE THREAD

**Issue by Shain-Dholakiya** [DataDog/dd-sdk-ios#1241]
### The crash

📝 Give us the crash report or stack trace, describe the problem in details and answer the questions.

partial apply for closure #1 in SwiftDatadogSdkPlugin.handle(_:result:)
NSInternalInconsistencyException - Sending a message before the FlutterEngine has been run.

Fatal Exception: NSInternalInconsistencyException
0  CoreFoundation                 0xa248 __exceptionPreprocess
1  libobjc.A.dylib                0x17a68 objc_exception_throw
2  Foundation                     0x54681c _userInfoForFileAndLine
3  Flutter                        0x12eb4 (Missing UUID 66de630a2b913f7d9856a3b1841da964)
4  Runner                         0x1100cc partial apply for closure #1 in SwiftDatadogSdkPlugin.handle(_:result:) (<compiler-generated>)
5  Datadog                        0x1522a4 (Missing UUID b65fc4e76a9237bd86862888604e503c)
6  Datadog                        0xd1d7c (Missing UUID b65fc4e76a9237bd86862888604e503c)
7  Datadog                        0x141e38 (Missing UUID b65fc4e76a9237bd86862888604e503c)
8  Datadog                        0x6dd50 (Missing UUID b65fc4e76a9237bd86862888604e503c)
9  Datadog                        0x6dd70 (Missing UUID b65fc4e76a9237bd86862888604e503c)
10 libdispatch.dylib              0x3fdc _dispatch_client_callout
11 libdispatch.dylib              0x13574 _dispatch_lane_barrier_sync_invoke_and_complete
12 Datadog                        0x141d0c (Missing UUID b65fc4e76a9237bd86862888604e503c)
13 Datadog                        0x145920 (Missing UUID b65fc4e76a9237bd86862888604e503c)
14 Datadog                        0x678a0 (Missing UUID b65fc4e76a9237bd86862888604e503c)
15 Datadog                        0x5f6a0 (Missing UUID b65fc4e76a9237bd86862888604e503c)
16 Datadog                        0x13d120 (Missing UUID b65fc4e76a9237bd86862888604e503c)
17 libdispatch.dylib              0x24b4 _dispatch_call_block_and_release
18 libdispatch.dylib              0x3fdc _dispatch_client_callout
19 libdispatch.dylib              0xb694 _dispatch_lane_serial_drain
20 libdispatch.dylib              0xc1e0 _dispatch_lane_invoke
21 libdispatch.dylib              0x16e10 _dispatch_workloop_worker_thread
22 libsystem_pthread.dylib        0xdf8 _pthread_wqthread
23 libsystem_pthread.dylib        0xb98 start_wqthread

---

#### Datadog SDK versions:

_Which version(s) of the Datadog SDK you see this crash happening in?_ 1.17.0

#### Last stable Datadog SDK version:

_What is the last Datadog SDK version where this crash doesn't happen?_

#### Volume:

_What % of your app sessions is impacted with this crash?_ 

#### OS version:

_Which iOS versions does this crash happen on?_ 16

#### Deployment Target:

_What is the Deployment Target of your app? e.g. `iOS 12`, `iPhone` + `iPad`_ iOS 12.0

#### Device version:

_Which devices does this crash happen on? e.g. `iPhone X` only or various iPads_ iPhone 11, iPhone 14 Pro, iPhone 13 Pro Max

#### Environment:

_Do you notice any environment correlation in crash reports? e.g. low battery, no internet connection, memory pressure_ No

**Comment by Shain-Dholakiya** [comment]
Hey @fuzzybinary thanks for the quick reply! I am using both the datadog_flutter_plugin (v1.1.1) and datadog_tracking_http_client (v1.2.0)

**Comment by fuzzybinary** [comment]
This is more likely related to the Flutter plugin than to the iOS SDK. I'm going to close this bug -- can you reopen on the Flutter repo instead?

**Comment by Shain-Dholakiya** [comment]
@fuzzybinary https://github.com/DataDog/dd-sdk-flutter/issues/390
