### ISSUE TITLE
Support watchOS

### ISSUE THREAD

**Issue by mozeryansky** [DataDog/dd-sdk-ios#125]
I had implemented a custom datadog internal sdk for logging before this official SDK was available. I have both watchOS and iOS applications. However, I can't switch to using this SDK because it relies on certain UIKit components not in watchOS.

Could we get watchOS support?

**Comment by ncreated** [comment]
Hello @mozeryansky 👋 , thanks for reaching us out 🙂! This question is similar to #78 (`macOS` support). Our strategy for the iOS SDK is to first deliver all three major features: [Logging](https://docs.datadoghq.com/logs/), [Tracing](https://docs.datadoghq.com/tracing/) and [Real User Monitoring](https://docs.datadoghq.com/real_user_monitoring/installation/?tab=us). After that point, we will re-evaluate supporting more platforms (including `watchOS`).

Although we don't have any time estimations for more platforms support, the facts are: Logging feature is already done and we're close to starting Tracing beta. After this, we'll work on RUM.

Please stay updated to our releases, to be notified when the `watchOS` is eventually supported 🙂. And we're glad you use Datadog 🚀.

**Comment by ncreated** [comment]
@mozeryansky Sure, let's keep it alive for more visibility 👌.

**Comment by n-ravichandran** [comment]
@ncreated Is there are update on this?

**Comment by antonmartinsson** [comment]
Still no updates on this @ncreated? Has any kind of evaluation like you mentioned taken place?

**Comment by MaelNamNam** [comment]
Hello and thanks for bumping this up, but unfortunately we still don’t have plans to support WatchOS with our SDK in the near future. However, the need has surfaced again a few times in the past few months and we might re-evaluate our priorities. Therefore, could you escalate a feature request through your support channels so we can properly track demand please?

**Comment by antonmartinsson** [comment]
Bummer! I'll gladly create a feature request. As someone who hasn't been in contact with your support before, what's the best way to do so? [This page](https://help.datadoghq.com/hc/en-us/requests/new)?

**Comment by MaelNamNam** [comment]
@antonmartinsson yes this is it! Please select `General Issue` in the "Impact" dropdown :)

**Comment by dfed** [comment]
Was this meant to be closed as "completed"? Or is this a "won't do"?

**Comment by maciejburda** [comment]
@dfed Thanks for double checking with us!

In this case it's neither. It's on our list, but unfortunately it falls behind other priorities as of now.

We're trying to find the best way to allow everyone to track progress of SDKs works. GH Issues are becoming quite busy - being a mix of feature requests, bug reports, configuration issues and questions.

I'll keep this open to allow everyone in the thread to track the resolution.

**Comment by mozeryansky** [comment]
@maciejburda Good to hear this won't be closed again, but I'm curious what the actual issue is. When I filed this ticket I was already using my own DataDog sdk for watchOS successfully. When I tried using this sdk the only issue was importing iOS only frameworks which were already unnecessary. 

From the list that @ncreated mentioned, it appears all the blockers have been completed. I know there must be more to offer official support, but I'm not sure the specifics.

I see in 2022 that the tvOS target was added. Was anyone able to try adding the watchOS target and seeing what the error is?

**Comment by ncreated** [comment]
👋 Hello. Great news to this very old issue - with a fantastic contribution from @jfiser-paylocity (#1946) we enabled `DatadogLogs` and `DatadogTrace` to compile for watchOS. This isn't yet official support, but definitely a significant step forward.

Logs for watchOS will be available in next minor release of the SDK.

**Comment by mozeryansky** [comment]
Wonderful!

Makes me wonder how many companies actually make watchOS apps considering DD supported visionOS before watchOS [#1652](https://github.com/DataDog/dd-sdk-ios/issues/1652)

**Comment by jakov-clay** [comment]
@ncreated do you know when watchOS release is planned? I guess I'll be first user. Our whole company uses DD and I'm really looking forward to be able to use DD on watch.

**Comment by ncreated** [comment]
Hey @jakov-clay 👋. We're targeting at next release this or next week. Stay tuned 🙂.

**Comment by ncreated** [comment]
WatchOS build compatibility was finally shipped in [**2.15.0**](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.15.0). That includes `DatadogLogs` and `DatadogTrace` (#1946). Happy to close one of the oldest issues in this repo 🥳.

**Comment by ncreated** [comment]
> [@ncreated](https://github.com/ncreated) the lack of error tracking on watchOS is still a blocker for my team, would it be worth reopening or better as a separate issue?

Hey @levibuzolic 👋. In **2.15.0**, we focused on enabling build compatibility for watchOS along with initial support for logging and tracing. However, enabling `DatadogCrashReporting` would require full RUM support on watchOS, which is not currently available.

If you'd like to request this feature, the best way to do so is through our **official [support channel](https://www.datadoghq.com/support)**. That allows our product team to properly review and prioritize it 🙏
