### ISSUE TITLE
trackRUMView vs startView and stopView

### ISSUE THREAD

**Issue by noureen-motorway** [DataDog/dd-sdk-ios#1269]
I am currently trying to build a module that will be isolated from swiftUI. I don't want to do 
`
import SwiftUI
` in my module.
I have access to datadog in my libraries and I want to track the RUMView. I was just wondering rather than doing 
trackRUMView on swiftUI if I do 
`Global.rum.startView` 
and
`Global.rum.stopView` in my module, will it log the same event?
Can anyone from team can clarify me. If we can use one and another interchangeably?

**Comment by maxep** [comment]
Hey @noureen-motorway 👋 

Thanks for using Datadog! Yes, you can instrument your views manually with `Global.rum.startView` and `Global.rum.stopView`, you will get the same events. You just have to make sure to call them when the view appears and disappears from the screen.
