### ISSUE TITLE
App's UILabel rendering with attributed strings is messed up when importing Datadog

### ISSUE THREAD

**Issue by sergiocampama** [DataDog/dd-sdk-ios#1286]
https://github.com/sergiocampama/DatadogBaseline for a repro case. I was able to repro this on Xcode 14.3, on the iPhone 14 Pro simulator running 16.4.

The project has 2 schemes, DatadogBaseline and DatadogBaselineExpected. Both schemes run the exact same app code, but only the DatadogBaseline app has access to Datadog through Cocoapods.

This is what I expect:

![Screenshot 2023-05-19 at 1 54 54 PM](https://github.com/DataDog/dd-sdk-ios/assets/689198/3080f2ce-d09d-4287-9643-371907f725b7)

This is how the UILabel is rendered when Datadog is just imported, and not referenced anywhere else.

![Screenshot 2023-05-19 at 1 55 33 PM](https://github.com/DataDog/dd-sdk-ios/assets/689198/3f9d7f25-e0e5-4c9c-bf6c-87346646baf4)

I tried for a couple hours to find the root cause, but I wasn't able to, so I'm hoping that someone in datadog has some idea of what might be happening.

**Comment by sergiocampama** [comment]
fyi: if I manually remove all the contents of the Swift files in datadog, the issue disappears

**Comment by sergiocampama** [comment]
After much looking, this seems to be unrelated to Datadog, and instead is because SwiftUI is transitively imported, which makes the issue appear.

**Comment by ncreated** [comment]
Hey @sergiocampama 👋. Happy you found the root cause - yes, it seems there is nothing we can address on our side (filling in a bug report to Apple could make most sense).

Anyway, thanks for managing this through GH Issue, this way it can help more people 💜.

**Comment by sergiocampama** [comment]
Filed it as FB12194719 if anyone cares to dupe
