### ISSUE TITLE
APM Traces not connecting in RUM Views

### ISSUE THREAD

**Issue by lfurukawa-ml** [DataDog/dd-sdk-ios#1292]
Hi guys,

We are trying to connect APM traces with RUM views, but when viewing the session in RUM, the trace information does not appear in the "Trace" tab:

<img width="1036" alt="img_01" src="https://github.com/DataDog/dd-sdk-ios/assets/102163451/bbccc28b-f5b6-424e-ab9a-3c9ab67ce5e7">

Upon examining the trace information in APM, we can see that it has the RUM view's attribute "view.id":

APM Trace:
<img width="733" alt="img_03" src="https://github.com/DataDog/dd-sdk-ios/assets/102163451/bf69e549-e076-41c3-85e3-4eeeb09229a9">

RUM view attributes:

<img width="1201" alt="img_02" src="https://github.com/DataDog/dd-sdk-ios/assets/102163451/4f35179c-b9ec-420b-bd4f-371483003d91">

We followed the recommended SDK configuration mentioned in this [issue](https://github.com/DataDog/dd-sdk-ios/issues/424) 

I noticed in the issue that you mentioned it might take some time for APM traces to appear in RUM, but even after waiting for 12 hours, the trace did not appear in the associated RUM view.

> **3. APM Trace <> RUM View connection.**
> Similar to Log <> RUM View connection, all APM traces created with Global.sharedTracer should be linked to the active RUM View and appear on the "Traces" tab. It may just take some more time until the trace appears there (logs appear almost instantly).

Currently, we are using the Datadog SDK 1.16.0, and we have tried updating it to version 1.19.0, but it still didn't work.

Could you please help us in identifying the problem?

Thank you!

**Comment by ncreated** [comment]
Hey @lfurukawa-ml. Thanks for reporting the problem - I confirm that I'm seeing this too 👍. We need to discuss what exactly got broken and we will come back to you with updates - please stay tuned.

**Comment by lfurukawa-ml** [comment]
hi @ncreated thanks for the prompt reply! we appreciate it

I wanted to use this thread to report another issue we've come across during our APM Traces testing. We have noticed that when creating traces at moments where a view has not yet been rendered, the span is sent without any RUM session information. 
For example, if we create a span during the application launch to measure the execution time of a method inside `applicationDidFinishLaunchingWithOptions` (which is automatically associated with the "view" ApplicationLaunch), this span is sent without any RUM information.

**Comment by lfurukawa-ml** [comment]
hi @ncreated
I noticed that you're working on a PR to address this issue, thank you
I was wondering if you could provide an estimate of when the fix will be deployed?

Once again, thank you for your assistance!

**Comment by plousada** [comment]
Hi @lfurukawa-ml, 

We're actively investigating and think we've pinpointed the main issues. Because we have a dependency on another team (APM) it's taking a little longer to investigate but we hope to come out with a fix in the following weeks. It's still hard for us to give a concrete date at this time. 
Once we have a fix finalized we'll reply on this issue. 

Sorry for not being able to provide a more concrete date.

**Comment by lfurukawa-ml** [comment]
hi @plousada thanks for your prompt reply, I'm glad to know that you are actively working towards a fix in the coming weeks
I await your response once the fix is finalized 😄 

thank you once again for your attention to this matter

**Comment by ncreated** [comment]
@lfurukawa-ml Thanks again for surfacing this problem 🙂. It has been solved and the fix is available in [`1.22.0`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.22.0).

**Comment by lfurukawa-ml** [comment]
hi @ncreated thank you for resolving the issue! we are going to test the new version 💪
