### ISSUE TITLE
Missing required module `_Datadog_Private` in Widgets target

### ISSUE THREAD

**Issue by LucasAbijmil** [DataDog/dd-sdk-ios#1304]
### The issue

📝 The DataDog SDK is a dependency of a _local_ Swift Package. So far I haven't had any problems compiling my iOS application.
However, when I added a target for Widgets (iOS 15+), and wanted to import my _local_ Swift Package, I got the following error at the very beginning of compilation: `Missing required module '_Datadog_Private'`.

Here's my `Package.swift` configuration: 
```
let package = Package(
  name: "MyPackage",
  platforms: [.iOS(.v15)],
  products: [
    .library(
      name: "MyPackage",
      targets: ["MyPackage"]),
  ],
  dependencies: [
    ...
    .package(url: "https://github.com/Datadog/dd-sdk-ios", .upToNextMinor(from: "1.20.0"))
    ...],
  targets: [
    .target(
      name: "MyPackage",
      dependencies: [
        ...
        .product(name: "Datadog", package: "dd-sdk-ios"),
        ...]),
    .testTarget(
      name: "MyPackageTests",
      dependencies: [.target(name: "MyPackage")])
  ]
)
```
---

#### Datadog SDK version:

Version: `1.20.0` 

#### Last working Datadog SDK version:
--

#### Dependency Manager:
Swift Package Manager (see _the issue_)

#### Other toolset:
--

#### Xcode version:
Xcode 14.3 (14E222b)

#### Swift version:
Swift version: 5.8

#### Deployment Target:
iOS 15+ (+ Widgets)

**Comment by maxep** [comment]
Hi @LucasAbijmil 👋 

Xcode does not seem to work well transitive dependencies from local `Package.swift`...
Have you tried to also add the `Datadog` package to your widget target?

**Comment by LucasAbijmil** [comment]
Hi @maxep 👋, 

Thank you for your reply. 

A little more context: 
- My widgets target was created before I created this _local_ Swift Package (containing the DataDog SDK).
- Once I added my _local_ Swift Package to my widgets target the compile error appeared.

However, I found a workaround to this problem: recreate my widget target from scratch. This solves the problem.

If you need more details on this, let me know.

**Comment by LucasAbijmil** [comment]
Hi @maxep 👋,

Thank you for your reply.

A little more context:

My widgets target was created before I created this local Swift Package (containing the DataDog SDK).
Once I added my local Swift Package to my widgets target the compile error appeared.
However, I found a workaround to this problem: recreate my widget target from scratch. This solves the problem.

I think the problem lies more with Xcode than with the SDK itself.

If you need more details on this, let me know.
