### ISSUE TITLE
XCFramework - zip contained on release is not found by Carthage

### ISSUE THREAD

**Issue by netbe** [DataDog/dd-sdk-ios#1318]
### Change name of artifact

Carthage can download the xcframework from github releases. But the name should be DataDog.xcframework.zip instead of DataDog.zip.

See https://github.com/Carthage/Carthage#archive-prebuilt-frameworks-into-zip-files

**Comment by ganeshnj** [comment]
Thanks for reaching out @netbe 

The V1 version of the SDK is not module stable which means you can't use prebuilt binaries across different Xcode versions (Swift compilers). We don't want people to directly depend on the SDK in their automations (CI) and encounter issues without a manual intervention.

We are fixing this issue in V2 version which is being worked on [here](https://github.com/DataDog/dd-sdk-ios/tree/feature/v2). Please stay tuned for more updates on this.

I'm going to keep this issue opened for tracking.

**Comment by maxep** [comment]
Fixed in [`2.0`](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.0.0).
