### ISSUE TITLE
Using more than one instance of the SDK

### ISSUE THREAD

**Issue by nileshcse14** [DataDog/dd-sdk-ios#1346]
I have one swift package manager where I want to use Datadog . My App is already using datadog. Now when I try to initialize the datadog library again in my SPM , its giving Datadog SDK usage error: SDK is already initialized error. How can we use datadog multiple instances within the same app?

**Comment by ncreated** [comment]
Hello @nileshcse14 👋, thanks for reaching us 🙂. In `1.x` version of the SDK we only support "single instance". This is a known limitation that will be relaxed in `2.0.0` where we will support multiple instances, unlocking scenarios like vendor SDKs instrumentation with Datadog.

Currently, we are consolidating our work on the `2.0.0` release and first beta will be available in following weeks.

Stay tuned 🙂.

**Comment by nileshcse14** [comment]
Thanks. Eagerly waiting for this update.

**Comment by maxep** [comment]
Available in [`2.0`](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.0.0).
