### ISSUE TITLE
UINavigationController subclass crashes

### ISSUE THREAD

**Issue by abear247** [DataDog/dd-sdk-ios#1356]
### The crash

objc[75872]: Cannot form weak reference to instance (0x14f032000) of class Top_Hat.TestNav. It is possible that this object was over-released, or is in the process of deallocation.

Crash log from our setup.
<img width="1228" alt="Screenshot 2023-06-30 at 12 18 34 PM" src="https://github.com/DataDog/dd-sdk-ios/assets/22183710/7594a756-baf5-4a89-9f22-8a7fe1245762">

Digging into it we found that the simplest reproducible was 
```
class TestNav: UINavigationController {}

// triggered from a button
func buttonPressed() {
    let hostingViewController = UIHostingController(rootView: EmptyView())
    let navigationController = TestNav(rootViewController: hostingViewController)
    present(navigationController, animated: true)
}
```

This was caught during QA when we were trying to add in Datadog RUM.

RUM setup code
```
    private func initializeDatadog(config: Config) {
        let ddConfig = Datadog.Configuration.builderUsing(
            rumApplicationID: config.rumApplicationID,
            clientToken: config.clientToken,
            environment: config.environment
        )
        .set(serviceName: config.serviceName)
        .set(endpoint: .us1)
        .trackUIKitRUMViews()
        .trackUIKitRUMActions()
        .enableTracing(true)
        .build()

        Datadog.initialize(
            appContext: .init(), trackingConsent: .granted, configuration: ddConfig
        )
        Global.rum = RUMMonitor.initialize()
    }
```

There is a workaround that does not crash.  So this seems particularly related to the default predicate.
```
class CustomPredicate: UIKitRUMViewsPredicate {
    func rumView(for viewController: UIViewController) -> RUMView? {
        return .init(name: "\(type(of: viewController))")
    }
}
```
#### Datadog SDK versions:

1.20.0

#### Last stable Datadog SDK version:

None, we haven't shipped this yet

#### Volume:

Easily reproducible within <5 swipes to close presented view

#### OS version:

iOS 16.2

#### Deployment Target:

14.0, iPhone and iPad

#### Device version:

iPhone 11

#### Environment:

N/A

**Comment by ncreated** [comment]
Hello @abear247 👋. I confirm, we can reproduce the problem and we added it to our backlog. Stay tuned for updates.

💡 Regarding mitigation (nice you discovered it ⭐), you can make it more specific by only applying it to the modal view controller and forwarding all other calls to our default predicate.

PS. Thanks a million for perfect information and isolating the reproduction steps to bare minimum. That helps a lot!

**Comment by ncreated** [comment]
This problem was fixed in https://github.com/DataDog/dd-sdk-ios/pull/1533 and deployed in **[2.5.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.5.0)**. I'm closing this issue.
