### ISSUE TITLE
Session Replay Beta - in objective - c

### ISSUE THREAD

**Issue by Jacob-Dev-12** [DataDog/dd-sdk-ios#1387]
### The thing

Tell us the thing 🙂
Hi,

I am trying to check on Session Replay Beta branch. I am trying to switch swift code to objective-c (my AppDelegate in objective - c) , is there any help for objective - c code below?

```
import DatadogSessionReplay
var sessionReplay: SessionReplayController!

let configuration = SessionReplayConfiguration(privacy: .maskAll)
sessionReplay = SessionReplay.initialize(with: configuration)
sessionReplay.start()
```

**Comment by ncreated** [comment]
Hello @Jacob-Dev-12 👋. Thanks for reaching us and glad you're exploring iOS Session Replay product 🙂! This product is currently in private beta, so we don't yet offer it fully. This will change soon, so please stay tuned.

**Comment by chetan-sevaro** [comment]
@Jacob-Dev-12 were you able to implement it in Objective C. Can you please share the code for the same if you have implemented
