### ISSUE TITLE
trackURLSession with Kingfisher

### ISSUE THREAD

**Issue by joseewu** [DataDog/dd-sdk-ios#1395]
Hello Datadog team 👋 
We are planning to add url session tracing for image loading.

We are using Kingfisher and we tried to inject url session by DDURLSessionDelegate, but it does not work. 
Kingfisher uses its owned session delegate. 

Do you have any way/ suggestion of how to achieve this?  Thanks 🙏

**Comment by maxep** [comment]
Hi @joseewu ! Thanks for using our SDK.

You can use the `__URLSessionDelegateProviding` protocol which can combine the `DDURLSessionDelegate` with another delegate.
By looking at Kingfisher's doc, it looks like they expect a `SessionDelegate` subclass, so you can try something like:
```swift
import DatadogSDK
import Kingfisher

class CustomSessionDelegate: Kingfisher.SessionDelegate, __URLSessionDelegateProviding {
    // MARK: - __URLSessionDelegateProviding conformance

    let ddURLSessionDelegate = DDURLSessionDelegate()

    // MARK: - __URLSessionDelegateProviding handling

    func urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics) {
        ddURLSessionDelegate.urlSession(session, task: task, didFinishCollecting: metrics) // forward to Datadog delegate
    }

    override func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
        ddURLSessionDelegate.urlSession(session, task: task, didCompleteWithError: error) // forward to Datadog delegate
        super.urlSession(session, task:task, didCompleteWithError: error)
    }

    override func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {
        ddURLSessionDelegate.urlSession(session, dataTask: dataTask, didReceive: data) // forward to Datadog delegate
        super.urlSession(session, task:task, didReceive: data)
    }
}
```

You can read about it in our [doc](https://docs.datadoghq.com/real_user_monitoring/ios/troubleshooting/#using-ddurlsessiondelegate-with-your-own-session-delegate).

I hope this helps!

**Comment by joseewu** [comment]
hey 👍 thanks! I also figure it out!! 
Good work on `DDURLSessionDelegate` and also` __URLSessionDelegateProviding`! 🙏 
Let me try.

**Comment by joseewu** [comment]
Hi @maxep yes I did plug the session delegate into ImageDownloader, and those three function also got called. 
```
    override func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
       /// the task here is not sent by URLSessionInterceptor.
    }
    override func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {

    }

```

However, in the URLSessionInterceptor I set the break point and found the request is not sent. 
So I am wondering if on my side I need to do any extra setup? 
I've added the host into `FirstPartyHosts` 🤔

**Comment by joseewu** [comment]
Hi I figure it out
```swift
class CustomSessionDelegate: Kingfisher.SessionDelegate, __URLSessionDelegateProviding {
    let ddURLSessionDelegate = DDURLSessionDelegate()

   /// For Kingfisher, I need to send created task manually, since DDURLSessionDelegate can not do that for me

    func urlSession(_ session: URLSession, didCreateTask: URLSessionTask) {
        URLSessionInterceptor.shared?.taskCreated(task: didCreateTask)
    }

    // MARK: - __URLSessionDelegateProviding handling

    func urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics) {
        ddURLSessionDelegate.urlSession(session, task: task, didFinishCollecting: metrics) // forward to Datadog delegate
    }

    override func urlSession(_ session: URLSession, task: URLSessionTask, didCompleteWithError error: Error?) {
        ddURLSessionDelegate.urlSession(session, task: task, didCompleteWithError: error) // forward to Datadog delegate
        super.urlSession(session, task:task, didCompleteWithError: error)
    }

    override func urlSession(_ session: URLSession, dataTask: URLSessionDataTask, didReceive data: Data) {
        ddURLSessionDelegate.urlSession(session, dataTask: dataTask, didReceive: data) // forward to Datadog delegate
        super.urlSession(session, task:task, didReceive: data)
    }
}
```

Now I can receive the data, let me know if it's not a good practice! 

Thanks!

**Comment by maxep** [comment]
Hey,

You shouldn't have to call `URLSessionInterceptor.shared` directly. Did you properly enable RUM and `URLSession` tracking when initialising the SDK?

```swift
Datadog.initialize(
    appContext: .init(),
    trackingConsent: .granted,
    configuration: Datadog.Configuration
        .builderUsing(
            rumApplicationID: "<#RUM Application ID#>",
            clientToken: "<#Client Token#>",
            environment: "test"
        )
        .trackURLSession()
        .build()
)

Global.rum = RUMMonitor.initialize()
```

I've tested it in a sample project and everything works as expected:
[KingfisherApp.zip](https://github.com/DataDog/dd-sdk-ios/files/12193946/KingfisherApp.zip)

**Comment by maxep** [comment]
Hey @joseewu 👋  Have you tried the example project I've shared?

**Comment by joseewu** [comment]
Yes, I tried, it worked. But it did not work on our project. I am trying to investigate the reason. 🙏

**Comment by joseewu** [comment]
hi @maxep I tried on our project, but the events are not fired without actively called `URLSessionInterceptor.shared?.taskCreated(task: didCreateTask)` 

Do you know if which wrong settings/ misuse could cause this? 

I looked into our project, there is no other places override Kingfisher's session delegate.

**Comment by maxep** [comment]
Hi @joseewu 👋 

Sorry for the late reply, I don't see anything wrong in your configuration, do you properly initialise the SDK in you AppDelegate?
Also, which version of the SDK and Kingfisher do you use?
