### ISSUE TITLE
Proxy to solve whitelisting

### ISSUE THREAD

**Issue by akovalov** [DataDog/dd-sdk-ios#1404]
Hi, is it possible to use a proxy on our own domain like `www.example.com/datadog` to solve the network whitelisting issue? So the DD SDK will send data to `www.example.com/datadog` that will forward to `browser-intake-datadoghq.com`?

[This](https://docs.datadoghq.com/real_user_monitoring/ios/advanced_configuration/?tab=swift#configuring-a-custom-proxy-for-datadog-data-upload) `proxyConfiguration` does not seem to work in this case. Thanks.

**Comment by akovalov** [comment]
@ncreated thanks, yes, I saw that SO advice and tried. Did a check with a local proxy as you wrote, but I still don't see that DD SDK requests go through this local proxy. I verified that the local proxy works by setting it in iOS Settings and seeing that everything goes through it. Do you see DD SDK network traffic in your local proxy server with this `proxyConfiguration`? (just to be clear I didn't use your IP address and port from the example and used my local proxy server).

**Comment by ncreated** [comment]
The test I did was about starting simple Flask HTTP server and setting the `proxyConfiguration` as above. After this, I can see that the traffic reaches the server but it responds with `405`, as expected (it's not HTTPS server):
```
192.168.1.10 - - [04/Aug/2023 09:27:30] "CONNECT browser-intake-datadoghq.com:443 HTTP/1.1" 405 -
```

Starting from here, I rather seems to be the question of how to configure [connectionProxyDictionary](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/1411499-connectionproxydictionary) and proxy server with certificates trusted on both ends, rather than a problem with the SDK. No matter that, our [online doc](https://docs.datadoghq.com/real_user_monitoring/ios/advanced_configuration/?tab=swift#configuring-a-custom-proxy-for-datadog-data-upload) should be better on this part. For that reason, I'll create an item in our backlog to investigate this further and come up with better advice. Meantime, if you figure out sth, please share 🙏.

**Comment by akovalov** [comment]
@ncreated we've not succeded using `proxyConfiguration` with HTTPS server, not sure why. However, I found that the DD SDK v2.0.0 has a `customEndpoint` parameter in the configuration for each product (RUM, Logs, Trace) separately. And we tested that it works OK with our proxy if we set `customEndpoint` like this

```
let config = Logs.Configuration(
    customEndpoint: URL(string: "https://our.custom.domain/api/v2/logs"))
Logs.enable(with: config, in: core)
```

Where `https://our.custom.domain` is our configured proxy that forwards all HTTP traffic to `https://browser-intake-datadoghq.com/api/v2/logs`. It's not very documented how to use `customEndpoint` and looks like DD SDK can communicate with `browser-intake-datadoghq.com` and `iam-rum-intake.datadoghq.com` and maybe some other. Also the path `api/v2/logs` can change inside DD. 

So, is there documentation on where our proxy should send traffic to and what the `customEndpoint` should look like when setting it in v2.0.0 DD SDK? Thanks

**Comment by ncreated** [comment]
Hey @akovalov 👋. Indeed, you could be using `customEndpoint` as a workaround. We leverage it in our integration testing, but decided to make it public for some customer use cases as well. Glad you figured it out 🏅!

The concept of `customEndpoint` is very simple.  Setting `customEndpoint` in configuration will overwrite the effect of `site:` parameter [set in `Datadog.Configuration`](https://swiftpackageindex.com/datadog/dd-sdk-ios/2.0.0/documentation/datadogcore/datadog/configuration/site). Notably, it will ignore the base URL dictated by the value of `site` and will send data to `customEndpoint` URL instead.

To make use of it in your scenario:
* Set `customEndpoint` to your proxy address.
* In your proxy implementation, ensure that data is forwarded to the right base URL - that will depend on the `site:` you use in `Datadog.Configuration` (`.us1` is used by default):
https://github.com/DataDog/dd-sdk-ios/blob/5d5c1f161f2e4f97533ce84dc357fb7784182f98/DatadogInternal/Sources/Context/DatadogSite.swift#L42-L55
* The actual endpoint to add to these ☝️ URLs will differ depending on the product you use:
   * for Logs: [`api/v2/logs`](https://github.com/DataDog/dd-sdk-ios/blob/5d5c1f161f2e4f97533ce84dc357fb7784182f98/DatadogLogs/Sources/Feature/RequestBuilder.swift#L48)
   * for Trace: [`api/v2/spans`](https://github.com/DataDog/dd-sdk-ios/blob/5d5c1f161f2e4f97533ce84dc357fb7784182f98/DatadogTrace/Sources/Feature/RequestBuilder.swift#L46)
   * for RUM: [`api/v2/rum`](https://github.com/DataDog/dd-sdk-ios/blob/5d5c1f161f2e4f97533ce84dc357fb7784182f98/DatadogRUM/Sources/Feature/RequestBuilder.swift#L60)

Last, make sure you don't alter SDK requests when forwarding them (e.g. do not change the `User-Agent` header as we send [some metadata](https://github.com/DataDog/dd-sdk-ios/blob/5d5c1f161f2e4f97533ce84dc357fb7784182f98/DatadogInternal/Sources/Upload/URLRequestBuilder.swift#L69-L70) in it).

Let me know if you have further questions and if it worked 🙂🤞.

**Comment by akovalov** [comment]
@ncreated Hi, thank you for the details! I confirm that it works great now. Closing this question. Thank you for the help!

**Comment by akovalov** [comment]
@ncreated just one clarification. We could have a proxy server changed dynamically while app is running. What would be the best way to update `customEndpoint` in the DD configuration? Calling the same enable function with the full configuration or possible to update only `customEndpoint` field in the existing configuration? Thanks

```
let config = Logs.Configuration(
    customEndpoint: URL(string: "https://our.custom.domain/api/v2/logs"))
Logs.enable(with: config, in: core)
```

**Comment by ncreated** [comment]
@akovalov Unfortunately, changing configuration after initialization is not something we currently support. Calling `enable()` won't work if `Logs` product was already enabled for that instance of the `core`. What may work is destroying the entire `core` instance and constructing it again. That should tear down all features.
