### ISSUE TITLE
How to decrease network traffic consumption

### ISSUE THREAD

**Issue by akovalov** [DataDog/dd-sdk-ios#1407]
We use the following Datadog configuration

```
let config = Datadog.Configuration(
            clientToken: clientToken,
            env: env.string,
            bundle: bundle,
            batchSize: .large,
            uploadFrequency: .rare)
let core = Datadog.initialize(
            with: config,
            trackingConsent: .granted,
            instanceName: instanceName)
```

Datadog SDK consumed 1.5 MB in total for 86 requests and made 1-3 HTTP requests per minute during the 30 mins measurement session. 

<img width="401" alt="Screenshot 2023-08-08 at 19 37 38" src="https://github.com/DataDog/dd-sdk-ios/assets/9693643/10feee49-bd0a-4488-9bc4-e58b50fd49ca">

And as you see the total content size that was sent is less than 100 KB, but because of the number of requests made the TLS handshake consumed ~1.3 MB. 

For us, it's more important to keep network consumption very low sacrificing the real timing of appearing logs and other data on the Datadog website. Based on the measurement above it will be 3 MB consumed in an hour which is a high number for our service. 

Is there a way to increase time intervals to send data to the server even more than it happens with the above configuration? Or how we could optimize it more? Thanks

**Comment by maciejburda** [comment]
Thanks for reporting!

It looks like it's related to iOS not keeping the connection open which forces too many TLS handshakes.
I'll need to run some tests locally. I'll get back to you later this week.

**Comment by maciejburda** [comment]
I contacted with the backend team and they quoted default idle timeout to be 60 seconds.

To explain a little bit the logic behind those configurations:
- single batch is opened for finite number of time based on the batchSize property:
```
.small -> 5 seconds
.medium -> 15 seconds
.large -> 60 seconds
```
- Upload frequency translates to a delay between requests of:
```
.frequent -> 1 second
.average -> 5 seconds
.rare -> 10 seconds
```

When using `large` batch size and `rare` frequency you are going to send a batch roughly every 70 seconds, which might miss the idle timeout.
I run some local tests using mitmproxy and it appears that standard configuration keeps the connection alive.
I would suggest playing around with the batchSize and see if it decreases the amount of TLS handshakes.

Would be great to learn a few things about your case:
- What tool did you use to measure the data? (1.26 MB / 2313 bytes = 545 TLS handshakes for 86 requests, which seems off).
- Does your application has a stable access to the Internet?

Having said that, we will take a deeper look into those configurations and make sure that they provide correct values and explain desired outcome in the documentation well.

Please let us know.

**Comment by akovalov** [comment]
@maciejburda thank you for your reply. It appeared to me that with `large` and `rare` the logs were sent a few times during a minute, so the 70 seconds interval was not applied. However, I will double-check that and let you know. 

We have multiple loggers created using `let logger = DatadogLogs.Logger.create(with: logsConfig, in: core)` with different names. Can that influence the intervals? 

Also, is there a way to increase time intervals between requests even more than 70 s? 

I've used [Charles Proxy](https://www.charlesproxy.com) running it on the Mac and setting it as a proxy in iPad WiFi settings.
I believe the internet was stable during the measurement session, but will make a new one to make sure. Speaking about our application in general, it is typically used with unstable internet access.

**Comment by maciejburda** [comment]
@akovalov Multiple loggers don't affect intervals.

Also there no supported way to increase the interval above 70 seconds. Although, we plug in system reachability and if there's no internet connection we pause all the uploads.

**Comment by akovalov** [comment]
Got it, thanks. 

Note regarding the above TLS size measurements for future reference. The Charles proxy client proxies SSL traffic and generates its certificate, so it increases TLS handshaking traffic and it can be ignored here and not counted. 

On our side, we've decreased the number of logs to send only important things so it will keep bandwidth usage at a minimum. Thanks.
