### ISSUE TITLE
Context property in `DDCrashReport` is `nil` in `sendCrashReportIfFound()`

### ISSUE THREAD

**Issue by JonathanFuentesF** [DataDog/dd-sdk-ios#1423]
### context property is nil in sendCrashReportIfFound()

I just implemented Crash report and notice that crashes are not showing up in DD dashboard.
I added logs to the library and notice that the context property in DDCrashReport object is nil hence the report is sent to purge before sending it to the service.

What could be the cause of this property being nil?

    func sendCrashReportIfFound() {
        queue.async {
            self.plugin.readPendingCrashReport { [weak self] crashReport in
                guard let self = self, let availableCrashReport = crashReport else {
                    DD.logger.debug("No pending crash available")
                    return false
                }

                DD.logger.debug("Loaded pending crash report")

                guard let crashContext = availableCrashReport.context.flatMap({ self.decode(crashContextData: $0) }) else {
                    // `CrashContext` is malformed and and cannot be read. Return `true` to let the crash reporter
                    // purge this crash report as we are not able to process it respectively.
                    DD.logger.debug("THIS IS NOT WORKING") <<<<<<----------------

                    return true
                }

                self.sender.send(report: availableCrashReport, with: crashContext)
                return true
            }
        }
    }

**Comment by ncreated** [comment]
Hello @JonathanFuentesF 👋. Which version of the SDK you experience this problem in?

If the crash context is malformed, an extra troubleshooting info will be printed to your debugger console if `Datadog.verbosityLevel` flag is set to `.debug`, could you please enable it and share that info?
```swift
Datadog.verbosityLevel = .debug
```

**Comment by JonathanFuentesF** [comment]
@ncreated This is interesting......
I created a vanilla project and I'm having the same issue.... I'm running Xcode 14.2 and on simulator.
Can this be my machine maybe ?

This is the code for the vanilla project

```
let dataDogConfiguration = Datadog.Configuration
            .builderUsing(
                rumApplicationID: "...,
                clientToken: "...",
                environment: "..."
            )
            .set(serviceName: "...")
            .set(endpoint: .us1)
            .trackUIKitRUMViews()
            .trackUIKitRUMActions()
            .build()
        
        Datadog.initialize(
            appContext: .init(),
            trackingConsent: .granted,
            configuration: dataDogConfiguration
        )
        
        Global.rum = RUMMonitor.initialize()
        
        Global.sharedTracer = Tracer.initialize(
            configuration: Tracer.Configuration(
                sendNetworkInfo: true
            )
        )
        Datadog.verbosityLevel = .debug
        CrashReporting.enable()
```

**Comment by ncreated** [comment]
Hey @JonathanFuentesF Thanks for the snippet. Recently, we released [`2.x`](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.1.1) of our SDK and I can see there that you're mixing `1.x` and `2.x` APIs, which isn't allowed. Using `2.x` crash reporter with `1.x` SDK won't work. You need to use either [`1.x`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.23.0) or [`2.x`](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.1.1) (recommended) for all Datadog modules.

While in your snippet, RUM SDK is initialized in `1.x` way, the `CrashReporting.enable()` is coming from `2.x`, so it won't work together.

Please refer to following guides:
* [iOS Crash Reporting and Error tracking (2.x)](https://docs.datadoghq.com/real_user_monitoring/error_tracking/ios/?tab=cocoapods)
* [1.x → 2.x migration guide](https://github.com/DataDog/dd-sdk-ios/blob/2.1.1/MIGRATION.md#crash-reporting-changes)

and let us know if it is clear enough 🙂.

**Comment by JonathanFuentesF** [comment]
@ncreated version implementation mismatch was the issue.
I was using old version as I follow an old tutorial.
Thank you.
