### ISSUE TITLE
Appstore upload failure

### ISSUE THREAD

**Issue by ogjurgjej** [DataDog/dd-sdk-ios#1443]
### The issue

`DatadogRUM.xcframework` with architecture `ios-arm64_arm64e` has `DatadogInternal.framework` embeded inside.
Path: `Datadog.xcframework/DatadogRUM.xcframework/ios-arm64_arm64e/DatadogRUM.framework/Frameworks/DatadogInternal.framework`

Apple does not allow xcframeworks to embed other xframeworks.
Whey trying to upload to Appstore, it fails with the following error:

```
Asset validation failed
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.datadoghq.DatadogInternal' under the iOS application 'SampleApp.app'. (ID: 42fd1e2e-3cf5-4c8b-bbda-c1a30d81ef74)

Asset validation failed
Invalid Bundle. The bundle at 'SampleApp.app/Frameworks/DatadogRUM.framework' contains disallowed nested bundles. (ID: 2ec0e31c-843f-4a2e-80af-66a4b025f832)

Asset validation failed
Invalid Bundle. The bundle at 'SampleApp.app/Frameworks/DatadogRUM.framework' contains disallowed file 'Frameworks'. (ID: 87213736-864b-4796-84b7-691003b64837)
```

---

#### Datadog SDK version:

`2.1.1` 

#### Last working Datadog SDK version:

n/a

#### Dependency Manager:

manually, frameworks downloaded from github
https://github.com/DataDog/dd-sdk-ios/releases/download/2.1.1/Datadog.xcframework.zip

#### Other toolset:

-

#### Xcode version:

`Xcode 14.3.1 (14E300c)`

#### Swift version:

`5.1`

#### Deployment Target:

`iOS 11`, `iPhone` + `iPad`

#### macOS version:

`macOS Ventura 13.5 (22G74) `

**Comment by ganeshnj** [comment]
Looks related to https://github.com/DataDog/dd-sdk-ios/issues/1402#issuecomment-1693669456

**Comment by ganeshnj** [comment]
A new version [2.1.2](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.1.2) with the fix.
