### ISSUE TITLE
[Bug] Conflict Between Datadog v2 and FirebaseCrashlytics Prevents Crash Data from Being Sent to Datadog

### ISSUE THREAD

**Issue by arnaud512** [DataDog/dd-sdk-ios#1448]
## Summary:

After updating to version 2 of the Datadog SDK, we've noticed that crash data is not being sent to the Datadog console when FirebaseCrashlytics is also integrated into the project. (not configured, just in the build) The issue does not occur when FirebaseCrashlytics is removed. 
**This appears to be a regression, as the functionality was working as expected in version 1 of the Datadog SDK.**

## Steps to Reproduce:

1. Create a new iOS project and integrate both Datadog SDK v2 and FirebaseCrashlytics.
2. Implement the Datadog sdk
3. Trigger a crash in the app.
4. Check the Datadog console for crash data.

## Expected Behavior:

Crash data should appear in the Datadog console, even when FirebaseCrashlytics is integrated into the project.

## Actual Behavior:

No crash data is sent to the Datadog console when FirebaseCrashlytics is also in use.

## Environment:

- **iOS Version:** 16.6
- **Datadog SDK Version:** 2.1.2
- **FirebaseCrashlytics Version:** 7.11.0
- **Installation method:** CocoaPods
- **Xcode Version:** Xcode 14.3.1

## Additional Information:

We're running an A/B test with both Crashlytics and Datadog, which is why both services need to be operational.

## Screenshot

![image](https://github.com/DataDog/dd-sdk-ios/assets/3939593/a5720174-7da3-4efd-86a3-9b239d81cbdd)

**Comment by ganeshnj** [comment]
Hi @arnaud512,

I just did a quick test with FirebaseCrashlytics enabled in the `Example iOS` and I was able to use upload the crash report.

![image](https://github.com/DataDog/dd-sdk-ios/assets/8882380/c8b8843f-7a57-450c-aae7-567a7b595702)


Check https://github.com/DataDog/dd-sdk-ios/commit/7a1223fa80c7fa6282c029c2e924244178dc1974
> Make sure you update `xcconfigs/Datadog.xcconfig` before testing.

Can you share a simple iOS application with steps to reproduce the issue? This would help us to diagnose the root cause faster.

**Comment by arnaud512** [comment]
Hi @ganeshnj 

Sorry I cannot push directly to github in my organisation (not even zip), so. i'll not be able to give you the sample application. But here is a sample code that you can use to test.

I just created a new ios app (and using cocoapods), and I can reproduce the issue. (crash are not reported on datadog v2, but was on v1)
(Don't forget to include a GoogleService-Info.plist to connect to firebase)

Podfile
```
# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'TestDatadog' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'DatadogCore'
  pod 'DatadogLogs'
  pod 'DatadogTrace'
  pod 'DatadogRUM'
  pod 'DatadogCrashReporting'
  pod 'DatadogWebViewTracking'
  pod 'DatadogObjc'

  pod 'Firebase/Crashlytics'
  pod 'Firebase/Analytics'
  # Pods for TestDatadog

end

```

TestDatadogApp.swift
```
import SwiftUI
import DatadogCore
import DatadogCrashReporting
import DatadogRUM
import DatadogTrace

import Firebase
import FirebaseCore

class AppDelegate: NSObject, UIApplicationDelegate {
    func application(_ application: UIApplication,
                     didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey : Any]? = nil) -> Bool {
        FirebaseApp.configure()
        Crashlytics.crashlytics().setCrashlyticsCollectionEnabled(false)

        configureDatadog()

        return true
    }

    private func configureDatadog() {

        let configuration = Datadog.Configuration(
            clientToken: "pubXX",
            env: "TestDatadog2",
            site: .us1,
            service: "TestDatadog2"
        )

        Datadog.initialize(with: configuration, trackingConsent: .granted)
        CrashReporting.enable()
        //        Logs.enable()

        RUM.enable(
            with: RUM.Configuration(
                applicationID: "ID",
                uiKitViewsPredicate: DefaultUIKitRUMViewsPredicate(),
                uiKitActionsPredicate: DefaultUIKitRUMActionsPredicate(),
                urlSessionTracking: RUM.Configuration.URLSessionTracking(),
                trackFrustrations: true,
                trackBackgroundEvents: true,
                longTaskThreshold: 0.1)
        )

        Trace.enable(
            with: Trace.Configuration(networkInfoEnabled: true)
        )

        RUMMonitor.shared().addAttribute(forKey: "usr.name", value: "TestUser2")

        Datadog.verbosityLevel = .debug
        RUMMonitor.shared().debug = true
    }
}

@main
struct TestDatadogApp: App {

    @UIApplicationDelegateAdaptor(AppDelegate.self) var delegate

    var body: some Scene {
        WindowGroup {
            ContentView()
        }
    }
}

```

**Comment by lpbas** [comment]
@arnaud512 We saw a similar issue when we were trying to integrate datadog into our app. Can you try to move your `configureDatadog()` call above the initialisation of Firebase (`FirebaseApp.configure()`)?

I want to verify we are facing a similar issue, since when we move the initialisation of datadog before Firebase the crash reports arrive to Datadog as expected.

**Comment by arnaud512** [comment]
@lpbas I can confirm that this trick works. If we configure datadog before firebase, it seems that it works! 
So right now we had implemented this hacky implementation. 
But it's a big regression from v1. 

@Datadog, can you please look into it?

**Comment by maxep** [comment]
Hey 👋 

Please have a look at https://github.com/DataDog/dd-sdk-ios/issues/634#issuecomment-942096892
This issue was already there in v1 and there is not much we can do sadly. I hope initialising Datadog first was enough for you to move forward.
