### ISSUE TITLE
Recommend use Lock rather than queue

### ISSUE THREAD

**Issue by muukii** [DataDog/dd-sdk-ios#1452]
### The thing

Using queues appears for making critical sessions.
What about using lock instead?

From this tips https://gist.github.com/tclementdev/6af616354912b0347cdf6db159c37057
> queue.async() is wasteful if the dispatched block is small (< 1ms), as it will most likely require a new thread due to libdispatch's overcommit behavior. Prefer locking to protect shared state (rather than switching the execution context).

it often takes a bit longer time to dispatch into critical session of using queue.
if the work item is quite cheap, it might be better to use lock to make a critical session.

If you agree this topic, I will work on this.
Thank you.

**Comment by maxep** [comment]
Hi @muukii 👋 

Thanks for those tips, it's an interesting read. We are already using locks in many cases, and during the migration to `2.0` we have drastically reduced the number of GDC queues.
In some cases tho, we leverage the fairness of a serial queue to keep the order of execution and report consistent events. Locks are cheap but unfair and cannot guarantee the order of execution and so they cannot be generally applied. We won't be committing changes on this topic at this point but rest assure that we will continue our effort to optimize.

Thank you again for your proposal 🙏  I'm closing this ticket but feel free to add any more details.
