### ISSUE TITLE
Get OTSpan to have operation name property

### ISSUE THREAD

**Issue by muukii** [DataDog/dd-sdk-ios#1453]
### The thing

Currently, we can't retrieve the operation name that is set outside.
Can we do this by updating OTSpan?

Tell us the thing 🙂

**Comment by maxep** [comment]
Hi @muukii  👋 

Indeed, the OpenTracing specification of a span only requires to [override the operation name](https://github.com/opentracing/specification/blob/master/specification.md#overwrite-the-operation-name). It is the same on [android](https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/Span.java#L144).

What is your use case to read the operation name? Maybe we can find another way to answer your needs.

Thanks 🙂

**Comment by muukii** [comment]
for instance, one of the use cases is making child span.
Using parent span's operation name, the child span can get a name including the parent name.

- parent: someOperation
  - child: someOperation-processingA
  - child: someOperation-processingB

something like this, we could build an operation name programmatically in runtime.
I'm not sure if my thinking is following datadog tracing best practices.

**Comment by maxep** [comment]
Hey @muukii 👋 🙂 

A child span will always carry over its parent span id, so when navigating your Trace in Datadog you will see the full context including parent and children spans. So having the parent operation name in children would be redundant. Would that be sufficient for your usage or do you see any blocker?

**Comment by maxep** [comment]
Hey @muukii 👋  I'm closing the issue but feel free to add another other comment!
