### ISSUE TITLE
iOS 17 crashes do not get symbolicated

### ISSUE THREAD

**Issue by msrutek-paylocity** [DataDog/dd-sdk-ios#1478]
### The Issue

👋 Hello, we've noticed that our crash reports do not get symbolicated on for iOS 17 - running devices.

iOS 16 example             |  iOS 17 example
:-------------------------:|:-------------------------:
<img width="803" alt="ios16" src="https://github.com/DataDog/dd-sdk-ios/assets/111602326/cac376b0-0950-47e2-bb45-d99dee9106fd"> | <img width="692" alt="ios17" src="https://github.com/DataDog/dd-sdk-ios/assets/111602326/0ee98ca9-a2b8-40aa-815f-ae4f30422378">

✅ We've followed the guide at https://docs.datadoghq.com/real_user_monitoring/error_tracking/ios/?tab=cocoapods#symbolicate-crash-reports

We're
- sending the dSYMs
- seeing crash reports symbolicated for iOS 16 and lower
- unable to see symbolicated reports for iOS 17

We use Xcode 14.3.1 to distribute our app and version 1.23.0 of Datadog SDK.

Is this something that can be fixed on your end? Or do we need to take some steps?

Thanks!

cc @augard

**Comment by msrutek-paylocity** [comment]
> which iOS version it is including build number?

@ganeshnj Can this information be found in the DD Error Tracking web app? All we currently know about the device is that it's running on `17.0` and the model is `iPhone15,3` (iPhone 14 Pro Max).

<img width="225" alt="Screenshot 2023-09-15 at 16 29 23" src="https://github.com/DataDog/dd-sdk-ios/assets/111602326/a11ddb4a-3680-4139-a377-c38aa417b0a4">

**Comment by msrutek-paylocity** [comment]
I still can't see the `build` property that you've highlighted.

But - the good news is that we've received some crashes on iOS 17 that do get symbolicated. We'll assume that the crash I've shared in the issue is from the developer beta build.

Therefore, closing for now - and we'll reopen if we encounter this again.

**Comment by msrutek-paylocity** [comment]
Hello @ganeshnj @maciejburda and  @ncreated .

We're reopening the issue as we're still seeing some of the crashes not being symbolicated - some of the crashes are on iOS `17.0.0`, `17.0.1` and even `17.0.2`.

Would you be able to look into this? 🙏

**Comment by ganeshnj** [comment]
Can you share the raw JSON events of non-symbolicated crashes?

I can see we have symbols for

- 17.0-21A329
- 17.0-21A5268h
- 17.0-21A5277h
- 17.0-21A5277j
- 17.0-21A5291h
- 17.0-21A5291j
- 17.0-21A5303d
- 17.0-21A5312c
- 17.0-21A5319a
- 17.0-21A5326a
- 17.0.1-21A340
- 17.0.2-21A350
- 17.0.2-21A351
- 17.0.3-21A360
I'm curious which particular version is failing in your case?

**Comment by msrutek-paylocity** [comment]
Unfortunately, the `build` field is nowhere to be found 🤯 . Is there a way to find it in logs (app.datadoghq.com/logs)?

**Comment by ganeshnj** [comment]
Got it, I think we need to take a deeper look, could you create a ticket via customer support? We may need additional information which is not appropriate to share in public.

**Comment by msrutek-paylocity** [comment]
Will do 👍

**Comment by ncreated** [comment]
Hello 👋. This problem has been fixed - we identified an issue impacting some iOS 17 crashes. No need for SDK version upgrade. I'm closing the issue, please reopen it if problem persists.
