### ISSUE TITLE
iOS Device Model, No Type

### ISSUE THREAD

**Issue by ls-clark-yin** [DataDog/dd-sdk-ios#1489]
### Lack of Device Type

Currently, is there a way to get the device model type?

like iPad Pro, iPad Air etc? I only see "iPad" and i am trying to recreate the panel from new relic we currently have. I Know i can implement it on our-side but is there a way to differentiate on DD that i'm missing? Thanks.

<img width="488" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/81585044/891bd8f8-7faa-464c-aeb1-ad05a0eb6e78">

**Comment by ncreated** [comment]
Hello @ls-clark-yin 👋. What you're looking for is `device.model`:\

<img width="293" alt="Screenshot 2023-09-20 at 17 49 34" src="https://github.com/DataDog/dd-sdk-ios/assets/2358722/eb02e976-12af-4311-b295-c2d8f8f5ddd1">

Simply, aggregate by `device.model` 👇 and display it as "Pie Chart".

<img width="245" alt="Screenshot 2023-09-20 at 17 51 42" src="https://github.com/DataDog/dd-sdk-ios/assets/2358722/be17153a-ffeb-49b8-933e-f76a1f69c031">


Let us know if this helps.

**Comment by ls-clark-yin** [comment]
> Hello @ls-clark-yin 👋. What you're looking for is `device.model`:
> 
> <img alt="Screenshot 2023-09-20 at 17 49 34" width="293" src="https://user-images.githubusercontent.com/2358722/269343930-eb02e976-12af-4311-b295-c2d8f8f5ddd1.png">
> Simply, aggregate by `device.model` 👇 and display it as "Pie Chart".
> 
> <img alt="Screenshot 2023-09-20 at 17 51 42" width="245" src="https://user-images.githubusercontent.com/2358722/269344530-be17153a-ffeb-49b8-933e-f76a1f69c031.png">
> Let us know if this helps.

Thanks for the quick reply i don't have those facet and only see iPad under what i believe is the same place for my logs. am i missing something in terms of implementing my logger? I am currently running on simulator as well, i think that shouldn't be an issue but let me know if it is.

<img width="892" alt="image" src="https://github.com/DataDog/dd-sdk-ios/assets/81585044/418a3e2b-685d-4287-828a-4c7e2ac4e321">

**Comment by ls-clark-yin** [comment]
@ncreated Let me know if i need to provide more information on how logger was setup thank you!

**Comment by ncreated** [comment]
@ls-clark-yin What I explained is for RUM, didn't know you refer to Logs 🙂. Indeed, I acknowledge the problem: we need to improve `device` info in log events. We will work on this on our side and keep this issue updated.

Meantime, you may want to send this information manually and create facets by your own. You can configure it globally for all events with [`logger.addAttribute(forKey:value:)`](https://swiftpackageindex.com/datadog/dd-sdk-ios/develop/documentation/datadoglogs/loggerprotocol/addattribute(forkey:value:)).

**Comment by ls-clark-yin** [comment]
Got it, sorry for the confusion, so if we use Logs exclusively we will need to orchestrate it on our side but if we use RUM it should be working, i'll try that out thanks.

**Comment by ls-clark-yin** [comment]
Is there any timeline for the facets for logs? Thanks

**Comment by aldoKelvianto** [comment]
Hi @ls-clark-yin @ncreated I've made a PR to address this in here https://github.com/DataDog/dd-sdk-ios/pull/1672

Please let me know whether this is what you've expected or not.

Thank you

**Comment by ls-clark-yin** [comment]
> Hi @ls-clark-yin @ncreated I've made a PR to address this in here #1672
> 
> Please let me know whether this is what you've expected or not.
> 
> Thank you


Yes! thank you for working on this, this looks correct, once it's up i'll make a ticket to add it and see if it's as expected. Thank you!

**Comment by ncreated** [comment]
@aldoKelvianto Thanks for contribution 👍. It is now merged, expect this to be available in next minor release.
