### ISSUE TITLE
Missing APM events on SPM

### ISSUE THREAD

**Issue by joseewu** [DataDog/dd-sdk-ios#1497]
### The issue

Hi Datadog team, 
We are facing an issue that not receiving APM events after migrating to SPM. 
Before migration, we still got the url requests on APM and connect with RUM events.
But we stop seeing APM after installing the Datadog sdk via SPM.

![Screenshot 2023-09-26 at 21 04 18](https://github.com/DataDog/dd-sdk-ios/assets/8402073/241f5975-4733-4d99-9907-38d2d4c14996)

![Screenshot 2023-09-26 at 21 05 08](https://github.com/DataDog/dd-sdk-ios/assets/8402073/c3db71ca-f22d-407d-930e-e74f869d84f1)

I filled the information below.

And here is our Datadog configure setting.

```
Datadog.initialize(
            appContext: .init(),
            trackingConsent: .granted,
            configuration: Datadog.Configuration
                .builderUsing(
                    rumApplicationID: Keys.appId,
                    clientToken: Keys.token,
                    environment: buildType
                )
                .set(endpoint: .eu1)
                .set(serviceName: Keys.serviceName)
                .enableLogging(false)
                .enableTracing(true)
                .trackUIKitRUMViews()
                .trackUIKitRUMActions()
                .trackRUMLongTasks()
                .trackURLSession(firstPartyHosts: hosts)
                .set(rumSessionsSamplingRate: samplingRate)
                .set(tracingSamplingRate: samplingRate)
                .build()
        )
        Global.rum = RUMMonitor.initialize()
        Global.sharedTracer = Tracer.initialize(
            configuration:
                Tracer.Configuration(
                    serviceName: Keys.serviceName,
                    sendNetworkInfo: true,
                    bundleWithRUM: true,
                    globalTags: globalTags
                )
        )
```

Before/ after migration we use the same version of sdk (both Datadog and Alamofire)
And also the configuration remained the same. 

I am not so sure if others use SPM have some issue or not.

Do you know what might be the root cause or help me to debug? 🙏 

Thanks for your time!

---

#### Datadog SDK version:

_Which version of the Datadog SDK causes this problem? e.g. `1.15.0`_

#### Last working Datadog SDK version:

_What is the last Datadog SDK version where this problem didn't occur? e.g. `1.15.0`_

#### Dependency Manager:

SPM 

#### Other toolset:

We also use `DatadogAlamofireExtension` to get the request from Alamofire. 
Alamofire version is 5.2.2.

#### Xcode version:

Xcode 14.3.1

**Comment by maciejburda** [comment]
Hey @joseewu 

Thanks for reporting the issue.

Normally package manager should have no effect on the behaviour of the SDK.
There is one difference though between Cocoapods and SPM. We don't provide Alamofire extension through SPM. You can read more about it [here](https://github.com/DataDog/dd-sdk-ios/tree/develop/DatadogExtensions/Alamofire).

In order to fix this, you can provide [this implementation](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogExtensions/Alamofire/DatadogAlamofireExtension.swift) directly in your source code.

We spotted one strange thing in the configuration:
```environment: buildType```
Could you please shed some light on what' behind this variable?

In the dashboard it would be great if you could remove all the filters from the query and just select `source:ios`. Our guess is that your data is there, but just filtered out (probably by environment mentioned before).

Last but not least, we recommend updating SDK to newest version `2.2.1`. [Migration Guide](https://github.com/DataDog/dd-sdk-ios/blob/2.0.0/MIGRATION.md) should help you a ton.

**Comment by joseewu** [comment]
hi @maciejburda 
Thanks for the reply!

Yes, I noticed the only difference is the Alamofire extension, since we are still in the older version, we follow the way of intercepting calls of Alamorefire like [here](https://github.com/DataDog/dd-sdk-ios/commit/092808aae599d5e481a93253528014c519ff91c6#diff-f9a742d3698dbcc1f2532dc0b1667f516ffb77ea94553e6bef07a11e68feca81L12). 

The weird part is that we still see the request/ view event normally but only lost the APM events. 

`environment: buildType ` is just a variable to know the app build type (could be release/ debug and QA ..etc)

I tried only fiter `source:ios` but could not see any event we did not send this information. 

We are using `service:ios-app` or `service:front-end` to differentiate events. 

I also tried to upgrade to 1.23.0, but still no events. 

May I know if Alamofire extension is supported natively by 2.3.0? 

I think it might related to that we need to use `URLSessionInterceptor` out of datadog sdk just on SPM.


Let me know if you need more information, Thanks 🙏 

Josee

**Comment by joseewu** [comment]
Hi i just did a quick test on the demo project with the same key and token as my company. 

I hardcoded the user id 12345, and fire the GET request from this url `https://cat-fact.herokuapp.com/facts`. 

The response succeed and I can see the session on RUM, but no traces connected. 
![Screenshot 2023-10-06 at 20 26 13](https://github.com/DataDog/dd-sdk-ios/assets/8402073/ecc6db04-f9c9-4bb9-b3f9-78c6f1adceb9)

![Screenshot 2023-10-06 at 20 24 08](https://github.com/DataDog/dd-sdk-ios/assets/8402073/1f5881c2-911f-4cd7-a5da-8eb09c87b0d7)

![Screenshot 2023-10-06 at 20 22 44](https://github.com/DataDog/dd-sdk-ios/assets/8402073/f01aebe3-c26b-4105-ae31-be91dd0b8c3c)

![Screenshot 2023-10-06 at 20 22 39](https://github.com/DataDog/dd-sdk-ios/assets/8402073/8bc5d480-79de-4c1c-bfd7-f7bd76aa6f12)

![Screenshot 2023-10-06 at 20 22 03](https://github.com/DataDog/dd-sdk-ios/assets/8402073/23b4b037-4e3c-4d00-a0ec-52793e490d06)

**Comment by joseewu** [comment]
Hi, I just tried a demo project in SPM with the same setting as my company. It works ... 
I can see the RUM event connect to APM traces. 
I will need to check the url on our side if some information is missing.

**Comment by maciejburda** [comment]
Are you using async/await URLSession API by any chance?

**Comment by joseewu** [comment]
Hello, thanks for the reply. 

I found one place using await, but it's not related to api work. It's on SwiftUI view.
Is it something related?

**Comment by joseewu** [comment]
Hi 👋 
@maciejburda 
I compared the working and non-working version and found that the non-working does not contain the necessary headers for RUM events. 
is it something related to missing traces? 

working:

![Simulator Screenshot - iPhone 14 Pro - 2023-10-10 at 19 12 22](https://github.com/DataDog/dd-sdk-ios/assets/8402073/c726c66b-166b-41ba-845b-cf04ea9938bc)

not working:
![Simulator Screenshot - iPhone 14 Pro - 2023-10-10 at 19 40 34](https://github.com/DataDog/dd-sdk-ios/assets/8402073/4f20382a-ecb1-4dfc-b504-18ed359abd4f)

**Comment by joseewu** [comment]
hi @maciejburda I figured it out. 
We have a custom DDRequestInterceptor to replace some header values. 
after the SPM migration, the custom DDRequestInterceptor does not work (it does not forward the request to `URLSessionInterceptor.shared?.modify`). 
The implementation looks like this 

```swift
class CustomInterceptor: RequestInterceptor {

    let datadogInterceptor = DDRequestInterceptor()

    func adapt(_ urlRequest: URLRequest, for session: Alamofire.Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {
        var newRequest = urlRequest
        newRequest.setValue(<newValue>, forHTTPHeaderField: "__session")
        datadogInterceptor.adapt(newRequest, for: session, completion: completion)
    }

    func retry(_ request: Request, for session: Alamofire.Session, dueTo error: Error, completion: @escaping (RetryResult) -> Void) {
        datadogInterceptor.retry(request, for: session, dueTo: error, completion: completion)
    }
}
``` 

I need to use URLSessionInterceptor directly from the CustomInterceptor. 

```swift
class CustomInterceptor: RequestInterceptor {

    func adapt(_ urlRequest: URLRequest, for session: Alamofire.Session, completion: @escaping (Result<URLRequest, Error>) -> Void) {
        var newRequest = urlRequest
        newRequest.setValue(<newValue>, forHTTPHeaderField: "__session")
        let instrumentedRequest = URLSessionInterceptor.shared?.modify(request: newRequest)
        completion(.success(instrumentedRequest ?? urlRequest))
    }
}
```

Is this implementation expected? 
Since the old one was implemented year ago and we did not change it during SPM, I am wondering that adding `DatadogAlamofireExtension` locally actually changes the lifecycle and the way that datadog modify the request. 

Let me know if the explanation is not clear.

**Comment by joseewu** [comment]
I also noticed that sometimes in DDRequestInterceptor `adapt(_ urlRequest: URLRequest, for session: Session, completion: @escaping (Result<URLRequest, Error>)` does not get called, unless I switch to `adapt(_ urlRequest: URLRequest, using state: RequestAdapterState, completion: @escaping (Result<URLRequest, Error>)` do you think it's something related to Alamofire?

**Comment by ncreated** [comment]
Hey @joseewu 👋. In order to use multiple request interceptors in Alamofire you should use "composite interceptor" rather than invoking one interceptor from the other. Please see this AF guide: 
- [_Using Multiple RequestInterceptors_](https://github.com/Alamofire/Alamofire/blob/master/Documentation/AdvancedUsage.md#using-multiple-requestinterceptors)

With `Interceptor(interceptors:)` our interceptor should work as intended. If it doesn't please start a new GH Issue with providing enough information so we can reproduce it on our side.
