### ISSUE TITLE
Simulator symbolication failed on crash report

### ISSUE THREAD

**Issue by joseewu** [DataDog/dd-sdk-ios#1537]
### The thing

Hi folks, I am trying to adopting the crash report of Datadog sdk. 
But I found this warning on the crash report.

![Screenshot 2023-11-03 at 16 38 50](https://github.com/DataDog/dd-sdk-ios/assets/8402073/2149700d-b135-47f4-ab33-5666269a4b97)

The crash is triggered simply by `fatalerror` in the demo project and the dsym is uploaded by the [datadog fastlane plugin](https://github.com/DataDog/datadog-fastlane-plugin).

Do you know why and what could cause this warning? 

Thanks in advance!

**Comment by plousada** [comment]
Hi @joseewu, typically you'll see that error message when the crash stack contains frames pertaining system libraries in versions that we don't yet support. This is currently the case for iOS beta versions for example.

Could you share with which iOS version you were testing?

**Comment by joseewu** [comment]
hi @plousada I am sorry for the delay. 

![Screenshot 2023-11-15 at 21 47 53](https://github.com/DataDog/dd-sdk-ios/assets/8402073/08884534-c082-4dd6-8eb8-5593d25c6f6e)
I took a screenshot. 
The iOS version is 16.4 on simulator and the xcode is 14.3.1.

Please let me know if you need more information.

**Comment by maxep** [comment]
Hey @joseewu 👋 

We currently do not have symbols for simulators, only physical devices. The banner is not accurate and we should change that.
If having simulator symbolication is important in your workflow, please contact support to open a Feature Request.
