### ISSUE TITLE
Automatic network requests tracing filters

### ISSUE THREAD

**Issue by BeetLab** [DataDog/dd-sdk-ios#1568]
Hi!

There can be PII leaks via URL's query parameters in automatic network requests tracing. I haven't found any options to filter outgoing URL SpanEvents, cause the tracer's filter doesn't work with URL spans - only with custom ones:

```swift 
var traceConfig = Trace.Configuration(service: Bundle.main.bundleIdentifier) { event in
      print("filter event: \(event)")
      return event
}
``` 
        
So are there any options to filter URL query in trace events? Like Logs pipelines filters or RUM's disabling geo-ip collection?

**Comment by maxep** [comment]
Hi @BeetLab 👋 

The event mapper should be called with automatic instrumentation as well. To complete your configuration, you should set the `urlSessionTracking` parameter, that will enable the automatic tracking in `DatadogTrace`.
```swift
Trace.enable(
    with: Trace.Configuration(
        urlSessionTracking: Trace.Configuration.URLSessionTracking(...),
        eventMapper: { event in
            print("filter event: \(event)")
            return event
        }
    )
)
```

If you are using pre `2.5.0` version of the SDK, you should also use an instance of `DatadogURLSessionDelegate` as delegate of your `URLSession`.

Starting with `2.5.0`, you don't have to use the `DatadogURLSessionDelegate` anymore and you can enable the instrumentation on any delegate class, like so:
```swift
URLSessionInstrumentation.enable(
    with: URLSessionInstrumentation.Configuration(delegateClass: YourCustomDelegate.self)
)
```

I hope this helps!

**Comment by BeetLab** [comment]
Thanks for the reply, @maxep will try!
Are there any filters/processors that can be applied at DataDog side? (like string processor for logs).
Cause we've got multiple platforms and it would be better to have single filtering logic.
Thanks in advance!

**Comment by maxep** [comment]
We have the [Sensitive Data Scanner](https://docs.datadoghq.com/sensitive_data_scanner/) which is made specifically for that :) It is available for Logs, APM, and RUM. You can read more about it in [this blog post](https://www.datadoghq.com/blog/identify-sensitive-data-leakage-in-apm-rum-with-sensitive-data-scanner/#obfuscate-sensitive-data-from-apm).

**Comment by BeetLab** [comment]
Thanks a lot!
