### ISSUE TITLE
RUM + Tracer works only one way

### ISSUE THREAD

**Issue by mswswing** [DataDog/dd-sdk-ios#1571]
Version: 2.5.0

# Implementation 1
```swift
Datadog.initialize(
	with: Datadog.Configuration(
		clientToken: clientToken,
		env: environment,
		site: .us1,
		service: serviceName
	),
	trackingConsent: .granted
)
Datadog.setUserInfo(id: UIDevice.current.identifierForVendor?.uuidString ?? "")
RUM.enable(
	with: RUM.Configuration(
		applicationID: appID,
		uiKitViewsPredicate: DefaultUIKitRUMViewsPredicate(),
		uiKitActionsPredicate: DefaultUIKitRUMActionsPredicate(),
		urlSessionTracking: RUM.Configuration.URLSessionTracking(firstPartyHostsTracing: .trace(
			hosts: [
				"domain.com"
			],
			sampleRate: sampleRate
		))
	)
)
Trace.enable(
	with: Trace.Configuration(
		sampleRate: sampleRate,
		service: serviceName,
		urlSessionTracking: Trace.Configuration.URLSessionTracking(
			firstPartyHostsTracing: .trace(
				hosts: [
					"domain.com"
				],
				sampleRate: sampleRate
			)
		),
		bundleWithRumEnabled: false,
		networkInfoEnabled: false
	)
)
URLSessionInstrumentation.enable(with: .init(
	delegateClass: SessionDelegate.self,
	firstPartyHostsTracing: .trace(hosts: [
		"domain.com"
	])
))
SessionReplay.enable(
	with: SessionReplay.Configuration(
		replaySampleRate: sampleRate,
		defaultPrivacyLevel: .allow
	)
)

let session = Session(
	configuration: configuration,
	interceptor: DDRequestInterceptor(),
	redirectHandler: redirector,
	eventMonitors: [DDEventMonitor()]
)
```
- RUM works good (I can see backend trace too)
- APM Service Summary not working
<img width="1782" alt="Screenshot of Slack (2023-12-01 3-00-58 PM)" src="https://github.com/DataDog/dd-sdk-ios/assets/100562641/dc568406-5443-4630-9b45-aa0baff33c09">

# Implementation 2
```swift
Datadog.initialize(
	with: Datadog.Configuration(
		clientToken: clientToken,
		env: environment,
		site: .us1,
		service: serviceName
	),
	trackingConsent: .granted
)
Datadog.setUserInfo(id: UIDevice.current.identifierForVendor?.uuidString ?? "")
RUM.enable(
	with: RUM.Configuration(
		applicationID: appID,
		uiKitViewsPredicate: DefaultUIKitRUMViewsPredicate(),
		uiKitActionsPredicate: DefaultUIKitRUMActionsPredicate(),
	)
)
Trace.enable(
	with: Trace.Configuration(
		sampleRate: sampleRate,
		service: serviceName,
		urlSessionTracking: Trace.Configuration.URLSessionTracking(
			firstPartyHostsTracing: .trace(
				hosts: [
					"domain.com"
				],
				sampleRate: sampleRate
			)
		),
		bundleWithRumEnabled: false,
		networkInfoEnabled: false
	)
)
URLSessionInstrumentation.enable(with: .init(
	delegateClass: SessionDelegate.self,
	firstPartyHostsTracing: .trace(hosts: [
		"domain.com"
	])
))
SessionReplay.enable(
	with: SessionReplay.Configuration(
		replaySampleRate: sampleRate,
		defaultPrivacyLevel: .allow
	)
)

let session = Session(
	configuration: configuration,
	interceptor: DDRequestInterceptor(),
	redirectHandler: redirector,
	eventMonitors: [DDEventMonitor()]
)
```
urlSessionTracking configuration removed on RUM
- APM works good
<img width="1209" alt="Screenshot of Google Chrome (2023-12-01 3-02-55 PM)" src="https://github.com/DataDog/dd-sdk-ios/assets/100562641/b76de064-9003-4a53-a91a-428650644a08">
- But RUM does not show backend trace

# Problem
- To make APM Service Summery working I have to turn off RUM urlSessionTracking
```
[DATADOG SDK] 🐶 → 13:43:36.844 💡 (tracing) No upload. Batch to upload: NO, System conditions: ✅
```

# Inspect
<img width="1167" alt="Screenshot of Google Chrome (2023-12-01 3-14-47 PM)" src="https://github.com/DataDog/dd-sdk-ios/assets/100562641/2e3b9878-92df-40a8-ad38-c3b81932425a">

- https://github.com/DataDog/dd-sdk-ios/blob/331faa268f387470bd541cec0717282add79c1d1/DatadogTrace/Sources/Integrations/TracingURLSessionHandler.swift#L80C12-L80C141

- I found that TracingURLSessionHandler ignores interception if origin is "rum"

<img width="881" alt="Screenshot of Google Chrome (2023-12-01 3-14-37 PM)" src="https://github.com/DataDog/dd-sdk-ios/assets/100562641/457838f3-c897-4cd3-8d12-d191e74f5a5c">

- https://github.com/DataDog/dd-sdk-ios/blob/331faa268f387470bd541cec0717282add79c1d1/DatadogRUM/Sources/Instrumentation/Resources/URLSessionRUMResourcesHandler.swift#L71

- And URLSessionRUMResourcesHandler sets origin = "rum"

# I need help
Thanks

**Comment by maxep** [comment]
Hi @mswswing ! Thank you for the detailed report, it is super clear.

When using RUM, what we offer is a RUM-to-APM distributing tracing integration. This integration prevents from sending Span events to APM, instead a Trace is created backend side when a RUM Resource is received. That's why the `TracingURLSessionHandler` is not invoked when using RUM.
I will ask internally why the RUM-to-APM does not generate service data in APM.

Thanks again 🙏

**Comment by mswswing** [comment]
Answer cleared thanks
