### ISSUE TITLE
iOS Stack Trace for Error Log

### ISSUE THREAD

**Issue by akovalov** [DataDog/dd-sdk-ios#1572]
Is it possible to have a stack trace for the error type log in the iOS SDK? 
For example, if the error was logged as

```
logger.error("An error was met!")
// or with an Error object
logger.error("An error was met!", error: errorObj)
```

How to get the stack trace that led to this error? Can SDK automatically attach it or need manually pass somehow?

Thanks

**Comment by ncreated** [comment]
Hello @akovalov 👋. At this moment our SDK doesn't collect backtraces for errors collected with `logger.error()`. Although you could implement it by your own with leveraging [`Thread. callStackSymbols()`](https://developer.apple.com/documentation/foundation/thread/1414836-callstacksymbols) and sending it as log attribute, this may not work reliably if debug symbols are stripped out in release build.

Today, we only symbolicate crashes if dSYMs are uploaded to Datadog. Symbolication isn't yet supported for other kind of errors (log errors, span errors nor manually collected RUM errors), hence we don't collect stack trace as part of them.

**Comment by akovalov** [comment]
Hi @ncreated got it, thanks.
