### ISSUE TITLE
RUM implementation in SwiftUI does not work along with UINavigationController

### ISSUE THREAD

**Issue by piotrgorecki** [DataDog/dd-sdk-ios#1587]
Hello,

I have a problem with session replay and our SwiftUI usage. I get a placeholder instead of a visible SwiftUI component. I attached a snippet below. This is my first approach to Datadog & RUM

iOS: 17.2, Xcode 15.1, SDK 2.5.0.

```
struct Customers: View {
    var body: some View {
        VStack(spacing: 0) {
           ....
        }
        .trackRUMView(name: "Customers")
    }
}

let rootView = Customers()
let viewController = UIHostingHiddenNavBarController(rootView: rootView)
navigationController: UINavigationController
navigationController.pushViewController(viewController, animated: true)
```

<img width="248" alt="Zrzut ekranu 2023-12-13 o 13 59 19" src="https://github.com/DataDog/dd-sdk-ios/assets/1668651/aa53eac6-7ec3-424d-bb0e-118bd8f9d938">

**Comment by maciejburda** [comment]
Thanks for opening the issue @piotrgorecki,

Current implementation of the Session Replay does not officially support SwiftUI, hence the placeholder you're seeing.

Though, it's definitely on our roadmap and we aim to add support for it in future releases.
