### ISSUE TITLE
Custom logs endpoint in 2.0

### ISSUE THREAD

**Issue by Petter-W** [DataDog/dd-sdk-ios#1606]
I'm looking into upgrading from to the 2.0 version of the framework, but I can't find a counterpart to `func set(customLogsEndpoint: URL)` after upgrading.

I cannot see any information about this either in the [release notes](https://github.com/DataDog/dd-sdk-ios/releases)  or the [migration guide](https://github.com/DataDog/dd-sdk-ios/blob/2.0.0/MIGRATION.md). We've been using it to limit data we send. Has the option to  set a custom logs endpoint been removed?

**Comment by plousada** [comment]
Hi @Petter-W, you can still find it in the Logs feature [Configuration](https://github.com/DataDog/dd-sdk-ios/blob/47822aa3f995104549aa2de3a6392ab1183428d6/DatadogLogs/Sources/Logs.swift#L30).

**Comment by Petter-W** [comment]
Thanks @plousada! I still don't understand fully the relationship between the Logs and the Logger.

Our setup has been pretty simple, we've set up the Datadog core and created a Logger. With 2.0 we should set up the core, enable Logs (`Logs.enable`) and then create the logger?

**Comment by ganeshnj** [comment]
> I still don't understand fully the relationship between the Logs and the Logger.

`Logs` struct is simply used for namespacing, I would have preferred `Logs` as empty enum to make is obvious because you can't instantiate enum type itself.

You are on right track, there is full list of instructions provided in the [log collection documentation](https://docs.datadoghq.com/logs/log_collection/ios/?tab=cocoapods#setup)

Essentially
```swift
// initialize the SDK
Datadog.initialize(
    with: Datadog.Configuration(
        clientToken: "<client token>",
        env: "<environment>",
        service: "<service name>"
    ), 
    trackingConsent: trackingConsent
)

// Enable logging
Logs.enable()

// Create your logger
let logger = Logger.create(
    with: Logger.Configuration(
        name: "<logger name>",
        networkInfoEnabled: true,
        remoteLogThreshold: .info,
        consoleLogFormat: .shortWith(prefix: "[iOS App] ")
    )
)```
