### ISSUE TITLE
Support for .NET iOS / .NET MAUI apps

### ISSUE THREAD

**Issue by mattleibow** [DataDog/dd-sdk-ios#1617]
**Are you requesting automatic instrumentation for a framework or library? Please describe.**
I am wondering about the plans and/or interest in supporting .NET for iOS and/or .NET MAUI for iOS.

**Is your feature request related to a problem? Please describe.**
I would like to use DataDog RUM with my .NET mobile app, but I am unable to find any bindings for the DataDog SDK for iOS.

**Describe the solution you'd like**
An official or community .NET binding for the iOS SDK so I ca use it in my apps.

**Describe alternatives you've considered**
I am not able to maintain a binding myself at this time.

**Additional context**

- https://learn.microsoft.com/en-us/dotnet/maui/migration/ios-binding-projects
- https://learn.microsoft.com/en-us/xamarin/cross-platform/macios/binding

**Comment by MaelNamNam** [comment]
Hi Matthew and thanks for reaching out! x-posting this from our [Android repo](https://github.com/DataDog/dd-sdk-android/issues/1811#issuecomment-1880612957) but indeed, we are not supporting .NET frameworks at the moment, and unfortunately do not have plans to bring official support in the near future. However, it's something that has been on our radar for some time already, and I was wondering if you could go through your support channels to escalate this feature request? It will help us better track demand to re-asses our priorities, and retrieve more details about your needs (number of apps, volume of sessions, particular use cases...) in a more confidential way :)
Cheers!

**Comment by craigwi** [comment]
As I mentioned on https://github.com/DataDog/dd-sdk-android/issues/1811, DataDog is referenced as a recommended solution for the retirement of https://appcenter.ms/apps.  Will you be ready by March 2025?

**Comment by ivandamyanov** [comment]
> As I mentioned on [DataDog/dd-sdk-android#1811](https://github.com/DataDog/dd-sdk-android/issues/1811), DataDog is referenced as a recommended solution for the retirement of https://appcenter.ms/apps. Will you be ready by March 2025?

Same reason I am looking into DataDog for Xamarin - the AppCenter recommendation. I guess not all AppCenter were using Xamarin (which I am) and maybe that's why Microsoft recommended it even though Xamarin/MAUI is not even planned. That's why I am looking into New Relic as well.

**Comment by mariedm** [comment]
Hi! Support for Xamarin or MAUI is currently not on our roadmap. As @MaelNamNam suggested, please feel free to submit this feature request through your support channels to ensure it’s escalated internally.

**Comment by prashanth-ardex** [comment]
Hi,
Has there been any change regarding the status of this feature request?

**Comment by oddfrer** [comment]
I've tested the binding [Bcr.Datadog.iOS.Sdk](https://www.nuget.org/packages/Bcr.Datadog.iOS.Sdk) for Logs and RUM, and it works great.

Easy setup:

```
// DDConfig
var configuration = new DDConfiguration(ClientToken, environment);
configuration.Site = DDSite.EU1;
DDDatadog.Initialize(configuration, DDTrackingConsent.Granted);

// DDLogs
var logsConfiguration = new DDLogsConfiguration(null);
DDLogs.Enable(logsConfiguration);

// DDCrashReporter
DDCrashReporter.Enable();

// DDRUM
var rumConfiguration = new DDRUMConfiguration(AppId);
DDRUM.Enable(rumConfiguration);

_rumMonitor = DDRUMMonitor.Shared;

// DDLogger
var loggerConfiguration = new DDLoggerConfiguration
{
    Service = "test.test.test",
    Name = "ios-logger",
    NetworkInfoEnabled = true,
    RemoteLogThreshold = DDLogLevel.Info,
    RemoteSampleRate = 100,
    PrintLogsToConsole = true,
};

_logger = DDLogger.Create(loggerConfiguration);
```

Example of custom RUM events and page tracking:
```
static partial void TrackAppPagePlatform(string pageName)
{   
    _rumMonitor?.StartView(pageName, pageName, new NSDictionary<NSString, NSObject>());
}

static partial void StopTrackAppPagePlatform(string pageName)
{
    _rumMonitor?.StopView(pageName, new NSDictionary<NSString, NSObject>());
}

static partial void TrackTapEventPlatform(string viewName)
{
    _rumMonitor?.AddAction(DDRUMActionType.Tap, viewName, new NSDictionary<NSString, NSObject>());
}
```

**Comment by oddfrer** [comment]
@brunck, are you planning to make the repo public anytime soon?

I’ve encountered some issues with the library on iOS versions earlier than 17.

On iOS 16, I get:

```
dyld[44271]: Symbol not found: _$s7Network11NWInterfaceV13InterfaceTypeO13wiredEthernetyA2EmFWC
  Referenced from: <EF1178CB-B7C6-38B8-A7A9-D5055FFDCADF> /.../CoreSimulator/Devices/.../DDMauiApp.app/Frameworks/DatadogCore.framework/DatadogCore (built for iOS-sim 17.0 which is newer than running OS)
  Expected in:     <52A39E89-0D03-32E4-90B2-8BC19B604735> /Library/Developer/CoreSimulator/Volumes/iOS_20A360/Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 16.0.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Network.framework/Network
```

On iOS 15, I get:

```
dyld[44989]: Symbol not found: _$s10Foundation10URLRequestV19_bridgeToObjectiveCSo12NSURLRequestCyF
  Referenced from: /.../CoreSimulator/Devices/.../DDMauiApp.app/Frameworks/DatadogCore.framework/DatadogCore
  Expected in: /Library/Developer/CoreSimulator/Profiles/Runtimes/iOS 15.5.simruntime/Contents/Resources/RuntimeRoot/System/Library/Frameworks/Foundation.framework/Foundation
```

This was tested using a clean “Hello, World!” MAUI app targeting net8.0.

The only added dependencies are:

```
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0-ios'">
        <PackageReference Include="Bcr.Datadog.iOS.CR" Version="2.22.8" />
        <PackageReference Include="Bcr.Datadog.iOS.ObjC" Version="2.22.8" />
</ItemGroup>
```

**Comment by brunck** [comment]
@oddfrer The minimum iOS version supported is 17. This is in the README for the various NuGet packages.

**Comment by oddfrer** [comment]
Thanks for the update, @brunck! Out of curiosity—would it be technically feasible to support iOS 15 or 16 as well, or is there something in the SDK or bindings that requires iOS 17+? I understand the usage share is heavily weighted toward newer versions, but broader support could help for apps that still need to run on slightly older devices.

**Comment by brunck** [comment]
@oddfrer Yes if that's needed it can certainly be looked at. I wouldn't be able to do much testing around iOS 15 and 16 though. I wouldn't be "dogfooding" it at all, as I only support iOS 17 and above in my apps, and I had to draw the line somewhere to get things up and running.

**Comment by oddfrer** [comment]
Totally understand—thanks for the clarification! Drawing the line somewhere makes sense, especially early on. If it turns out iOS 15 support is viable without too much overhead, I’d be happy to help test or contribute where possible.

**Comment by oddfrer** [comment]
Any update on this, @brunck?

**Comment by brunck** [comment]
I'm trying to get this Android release out first before I do anything else but there's a bug in Android binding projects that's blocked me, for now.
