### ISSUE TITLE
VisionOS Support

### ISSUE THREAD

**Issue by nskonieczko** [DataDog/dd-sdk-ios#1652]
### Feature Request

- Add `visionOS` as a supported platform by this SDK or another.
- Currently we have a native visionOS app, and would prefer to be able leverage DataDog for our Vision Pro app.

**Comment by maxep** [comment]
Hi @nskonieczko ! Thank you for your request.

VisionOS is definitely on our radar. Feel free to also reach out to your support channels to escalate this feature request, it will help us better asses our priorities.

Thanks!

**Comment by kbroughton** [comment]
+1

**Comment by farshadtx** [comment]
+1

**Comment by p84mustang** [comment]
+1

**Comment by rsalvadorjr** [comment]
+1 Let's go 🚀

**Comment by Monroechabrier** [comment]
+1 to that

**Comment by maxep** [comment]
Hi everyone👋  Thank you for your interest.

As mentioned, we would need to assess priority based on feature request. Feel free to contact our support channel.
> Suggestion: please use thump-up reaction and issue subscription instead of '+1' comments :)

**Comment by maciejburda** [comment]
We've added unofficial support. All the targets [except for Crash Reporting](https://github.com/microsoft/plcrashreporter/issues/288) should compile for visionOS.
