### ISSUE TITLE
Getting Failed to build `Logger` error even though the implementation looks correct

### ISSUE THREAD

**Issue by rajtharan-allen** [DataDog/dd-sdk-ios#1657]
Error details:
→ type: ProgrammerError
→ message: 🔥 Datadog SDK usage error: `Datadog.initialize()` must be called prior to `Logger.builder.build()`.
→ stack: 🔥 Datadog SDK usage error: `Datadog.initialize()` must be called prior to `Logger.builder.build()`.

<img width="521" alt="Screenshot 2024-02-06 at 5 23 53 PM" src="https://github.com/DataDog/dd-sdk-ios/assets/128353109/d4af0f1f-9803-498c-a70a-497f7bf9be34">

Getting the above error. In the code shown below the Datadog init happens prior to Logger init as expected b
ut still getting the same error

```
Datadog.initialize(
            with: Datadog.Configuration(
                clientToken: "clientToken",
                env: env,
                site: .eu1
            ),
            trackingConsent: trackingConsent
        )

        let logger = Logger.create(
            with: Logger.Configuration(
                service: "ios-sdk-example-app",
                name: "logger name",
                networkInfoEnabled: true,
                remoteSampleRate: 100,
                consoleLogFormat: .shortWith(prefix: "[iOS App] ")
            )
        )

        logger.error("ios error test")
```

**Comment by maciejburda** [comment]
@rajtharan-allen Thank you for posting the issue. I will look into it shorty.

In the meantime I am afraid that you have accidentally exposed your client token in the original message. I removed it from the content, but it's still available in the history. I need to advice you to revoke it, in order to mitigate the potential security risk.

**Comment by rajtharan-allen** [comment]
@maciejburda Thanks for the swift Reply. I have updated the token with a random string and not the actual ones, so no security issues.

Also want to let you know that this issue was noted in latest release 2.7.0. Out of curiosity I downgraded to 2.5.1 and it worked without any errors.

**Comment by maciejburda** [comment]
I double checked your configuration and it looks like you're missing `Logs.enable()` configuration call before creating a logger. You should be able to fix your issue adding this line here:

```swift
Datadog.initialize(
    with: Datadog.Configuration(
        clientToken: "clientToken",
        env: "test-logger",
        site: .us1
    ),
    trackingConsent: .granted
)

// Logs feature needs to be enabled independently as it requires extra configuration properties.
// Here we're relying on default values for simplicity.
Logs.enable()

let logger = Logger.create(
    with: Logger.Configuration(
        service: "ios-sdk-example-app",
        name: "logger name",
        networkInfoEnabled: true,
        remoteSampleRate: 100,
        consoleLogFormat: .shortWith(prefix: "[iOS App] ")
    )
)

logger.error("ios error
```

More info in the [docs](https://docs.datadoghq.com/logs/log_collection/ios/)

**Comment by maciejburda** [comment]
@rajtharan-allen Please let us know if it solved your issue :)
