### ISSUE TITLE
[Crash] closure #1 in closure #1 in UIApplicationSwizzler.SendEvent.swizzle()

### ISSUE THREAD

**Issue by ElonPark** [DataDog/dd-sdk-ios#1661]
### The crash

This happens when you turn on view tracking and action tracking in the Datadog SDK. 
We don't use Swizzling at all in our app, only in the Datadog SDK.

We have found that turn off view tracking and action tracking using feature flags does not cause the crash.

This crash is 100% caused by the Datadog SDK

```
com.apple.main-thread
SIGABRT ABORT 0x000000020a011bc4

Crashed: com.apple.main-thread
0  libsystem_kernel.dylib         0xebc4 __abort_with_payload + 8
1  libsystem_kernel.dylib         0x30c14 abort_with_payload_wrapper_internal + 104
2  libsystem_kernel.dylib         0x30bac abort_with_payload_wrapper_internal + 30
3  libobjc.A.dylib                0x3385c _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 116
4  libobjc.A.dylib                0x337e8 _objc_fatalv(unsigned long long, unsigned long long, char const*, char*) + 30
5  libobjc.A.dylib                0x6b50 weak_register_no_lock + 392
6  libobjc.A.dylib                0xb808 objc_storeWeak + 448
7  UIKitCore                      0x11fe3c _UIResponderForwarderWantsForwardingFromResponder + 736
8  UIKitCore                      0x35470 __forwardTouchMethod_block_invoke + 44
9  CoreFoundation                 0xa7dc __NSSET_IS_CALLING_OUT_TO_A_BLOCK__ + 24
10 CoreFoundation                 0x8b5a4 -[__NSSetM enumerateObjectsWithOptions:usingBlock:] + 200
11 UIKitCore                      0x202e4c forwardTouchMethod + 236
12 UIKitCore                      0xfd0c4 -[UIWindow _sendTouchesForEvent:] + 356
13 UIKitCore                      0xfc684 -[UIWindow sendEvent:] + 3284
14 UIKitCore                      0xfb944 -[UIApplication sendEvent:] + 672
15 Karrot                         0x1852d50 closure #1 in closure #1 in UIApplicationSwizzler.SendEvent.swizzle() + 4368674128
16 Karrot                         0x1852df8 thunk for @escaping @callee_guaranteed (@guaranteed UIApplication, @guaranteed UIEvent) -> (@unowned Bool) + 4368674296
17 UIKitCore                      0xfb000 __dispatchPreprocessedEventFromEventQueue + 7088
18 UIKitCore                      0x142d64 __processEventQueue + 5632
19 UIKitCore                      0xd89a30 updateCycleEntry + 168
20 UIKitCore                      0x651678 _UIUpdateSequenceRun + 84
21 UIKitCore                      0xc90904 schedulerStepScheduledMainSection + 172
22 UIKitCore                      0xc8fad0 runloopSourceCallback + 92
23 CoreFoundation                 0xd622c __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28
24 CoreFoundation                 0xe2614 __CFRunLoopDoSource0 + 176
25 CoreFoundation                 0x6651c __CFRunLoopDoSources0 + 244
26 CoreFoundation                 0x7beb8 __CFRunLoopRun + 836
27 CoreFoundation                 0x811e4 CFRunLoopRunSpecific + 612
28 GraphicsServices               0x1368 GSEventRunModal + 164
29 UIKitCore                      0x3a2d88 -[UIApplication _run] + 888
30 UIKitCore                      0x3a29ec UIApplicationMain + 340
31 Karrot                         0x6ed4 main + 11 (main.swift:11)
32 ???                            0x1ebcbd948 (누락)
```

### Reproduction

1. View Tracking Enabled
2. Action Tracking Enabled

---

#### Datadog SDK versions:

- 1.21.0
- 2.5.0

#### Last stable Datadog SDK version:

X

#### Volume:

Number of unique users: 839.93k
Number of crash user: 213
Number of crash: 275

#### OS version:

- iOS 15
- iOS 16
- iOS 17
- iPad OS 16

#### Deployment Target:

- `iOS 15`

#### Device version:

14% - iPhone SE (2nd generation)
11% - iPhone 12
9%- iPhone 13
8% - iPhone 12 Mini
6% - iPhone 13 Mini
6% - iPhone 14 Pro
4% - iPhone 12 Pro
4% - iPhone 14
4% - iPhone 13 Pro
4% - iPhone 12 Pro Max
2% - iPhone 11
2% - iPhone 11 Pro
2% - iPhone XR
2% - iPhone X
2% - iPhone SE (3rd generation)
2% - iPhone 13 Pro Max
2% - iPhone 8 Plus
2% - iPhone 14 Pro Max
2% - iPhone XS
1% - iPhone 8
<1% - iPhone 11 Pro Max
<1% - iPhone 15 Pro
<1% - iPhone 14 Plus
<1% - iPhone XS Max

#### Environment:

_Do you notice any environment correlation in crash reports? e.g. low battery, no internet connection, memory pressure_

**Comment by ncreated** [comment]
Hello @ElonPark 👋 

Because `UIApplication.sendEvent(_:)` is an entry point to any touch interaction in the app, it is fair to expect Datadog frames appear in the stack trace if crash follows user interaction. Typically, we consider it a false-positive so not the SDK fault. What leads me to the same conclusion in this case is that I found exactly the same stack trace reported here:
- https://forums.developer.apple.com/forums/thread/715352

It names the interaction with a 3rd party keyboard to be the root cause. It also mentions [this](https://github.com/SnowGirls/Objc-Deallocating) as a possible solution. Could it be the case in your app?

> We have found that turn off view tracking and action tracking using feature flags does not cause the crash.

SDK swizzles `UIApplication.sendEvent(_:)` only for action tracking, so view tracking should make no difference here.

Given that we have not received any other reports of this problem and our swizzling code is very old, at this moment I rather don't consider it as an SDK issue. To make us look into this, we need to receive a setup and reproduction steps that prove it to be SDK fault 🙏.

**Comment by ElonPark** [comment]
Thank you for your response!
 I'll check it out and if it's not the cause, I'll reopen the issue

**Comment by hlung** [comment]
I think I found a way to replicate this.
Using an `@objc async` function for UIButton addTarget selector, when triggered, seems to crash UIApplicationSwizzler of DatadogRUM.

e.g.
```
@objc func buttonDidPress() async {
  // ...
}
```

**Comment by sethi-ishmeet** [comment]
I am experiencing the same issue. This issue should not be closed given the fact that this crash is clearly within the RUM Module of the DD SDK. Any suggestions so we could help fix this @ncreated ?

**Comment by ncreated** [comment]
Hey @sethi-ishmeet Can you provide us with reproduction steps for this crash? Ideally with an implementation of a button that causes the problem when using RUM instrumentation.

> Using an @objc async function for UIButton addTarget selector, when triggered, seems to crash UIApplicationSwizzler of DatadogRUM.

Unfortunately what @hlung provided is not enough. It seems that mixing `@objc` with `async` isn't safe in the first place (Datadog SDK excluded). See [this](https://forums.swift.org/t/objc-func-foo-async/52631/11) discussion on Swift forum and [this open bug in Swift project](https://github.com/swiftlang/swift/issues/57613).
