### ISSUE TITLE
Metrics SDK - How to send measures and counters using the iOS SDK?

### ISSUE THREAD

**Issue by rajtharan-allen** [DataDog/dd-sdk-ios#1662]
Using Open telemetry Datadog exporter we are able to add counter and record measures. After sending these data, we were able to view that in the Metrics explorer. I want to achieve the same using the dd-sdk-ios library directly.

But this library provides only logs, RUM and tracking. Doesn't look like  there is a way to achieve the counters and measures. Pleas help us in pointing the right documentation if we can do this using the SDK directly.

**Comment by maciejburda** [comment]
Thank you for opening the issue.

1. Unfortunately this is not possible through the SDK yet.

I strongly advise opening a [feature request](https://help.datadoghq.com/hc/en-us/requests/new) so we can bump the priority internally.
