### ISSUE TITLE
Privacy manifest causing collisions through CocoaPods

### ISSUE THREAD

**Issue by nabs-m** [DataDog/dd-sdk-ios#1665]
The `2.7.0` release added a privacy manifest, but its current setup with CocoaPods is causing collisions with other privacy manifest files as you can see below:

![image](https://github.com/DataDog/dd-sdk-ios/assets/2532658/22af3550-9a1c-4a21-a27a-0d0887620247)

I believe this is because the `PrivacyInfo.xcprivacy` is referenced as a `resource` in the [podspec](https://github.com/DataDog/dd-sdk-ios/blob/9faa46ce5e93ae453cebb623771a926b44f8ac23/DatadogCore.podspec#L25) instead of using `resource_bundle`. The latter would avoid collisions by putting the privacy manifest file in subfolders for each dependency, instead of going in the app bundle's root. More context on this [here](https://github.com/google/promises/pull/226#discussion_r1447871477). I think the fix would be to simple swap `resource` with `resource_bundle` here.

**Comment by maxep** [comment]
Fixed in [2.7.1](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.7.1)
