### ISSUE TITLE
Provide a boolean flag in configuration that enables batch upload even in low power mode

### ISSUE THREAD

**Issue by DrAma999** [DataDog/dd-sdk-ios#1700]
### Feature description

There are many scenarios where logs are super important even in low power mode.
DataDog disables batch upload when low power mode is enabled and there is no way to modify this behavior.

### Proposed solution

Add a boolean flag in DataDog configuration that enables batch upload in background, `shouldEnableBatchUploadInLowPowerMode` with a default to `false`.

**Comment by maxep** [comment]
Hi @DrAma999 👋 

Thanks for using our SDK! The behaviour is intentional as discussed in #176, see [this comment](https://github.com/DataDog/dd-sdk-ios/issues/176#issuecomment-693365251) in particular. 
Please note that the logs are not lost, the upload is just delayed until the device meets conditions for upload (network and power).

I'm closing this issue as it's a duplicate, but feel free to comment on #176 and to reach out to support to open a Feature Request. This would help assess demand and priorities.

**Comment by DrAma999** [comment]
Hello @maxep,
Thank you for your answer, logs are not lost but as far as I understand there is retention of 18/19 hours and cannot be changed.
Our app is a companion app of a smart device and the user open the app very few times.

**Comment by ncreated** [comment]
Hello @DrAma999 

> Our app is a companion app of a smart device and the user opens it very few times.

For such scenarios, our SDK offers several options to anticipate short durations of "upload window". Please have a look at following APIs to control how greedy the SDK should be for creating and uploading batches:
- [`batchSize`](https://github.com/DataDog/dd-sdk-ios/blob/6eab2d82441c4997ce05f9ecee7d64cc38517fc1/DatadogCore/Sources/Datadog.swift#L93-L97) - to control how often new batch file should be created (more in [docs](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?s=backgroundTasksEnabled#initialization-parameters))
- [`uploadFrequency`](https://github.com/DataDog/dd-sdk-ios/blob/6eab2d82441c4997ce05f9ecee7d64cc38517fc1/DatadogCore/Sources/Datadog.swift#L99-L103)  to control how often batch files should be uploaded (more in [docs](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?s=backgroundTasksEnabled#initialization-parameters))
- [`batchProcessingLevel`](https://github.com/DataDog/dd-sdk-ios/blob/6eab2d82441c4997ce05f9ecee7d64cc38517fc1/DatadogCore/Sources/Datadog.swift#L126-L129) - to control how many batches should be uploaded each time
- [`backgroundTasksEnabled`](https://github.com/DataDog/dd-sdk-ios/blob/6eab2d82441c4997ce05f9ecee7d64cc38517fc1/DatadogCore/Sources/Datadog.swift#L131-L137) - to decide if SDK should extend application lifecycle to "in background" for data uploads.

My recommendation would be to try:
- `uploadFrequency: .frequent`
- `batchProcessingLevel: .high`

first and keep other values as default. If it is not enough, you can try smaller batches (`batchSize: .small`) and leveraging background tasks (`backgroundTasksEnabled: true`).

Regarding the "low power mode" condition itself, this is motivated in the comment that @maxep has linked. We have no active plans to relaxing this constraint. However, you can try doing it by your own if forking our SDK. The actual code change to remove LPM check would be very minimal, see: [here](https://github.com/DataDog/dd-sdk-ios/blob/6eab2d82441c4997ce05f9ecee7d64cc38517fc1/DatadogCore/Sources/Core/Upload/DataUploadConditions.swift#L57-L59).

**Comment by DrAma999** [comment]
@ncreated Thank you so much for all your suggestion <3, we will give a try
