### ISSUE TITLE
Opt-out from method swizzling

### ISSUE THREAD

**Issue by marcelofabri** [DataDog/dd-sdk-ios#171]
1.3.0 beta release notes include:

> Your network requests are automatically traced now 🚀

This is done via swizzling (at least it looks like it). Swizzling is very invasive and can cause issues down the road, so we would like to opt-out from it. Is there an option to do it? If so, including it in the changelog would be ideal. 🙏

**Comment by buranmert** [comment]
hi @marcelofabri 👋 

**Short answer:** you don't need to do anything to opt-out

By default, auto-tracing is disabled and SDK doesn't do swizzling.
That _"automatically traced now 🚀 "_ is the last step of a 4-steps list and if you skip any of the steps, auto-tracing won't be enabled and swizzling won't take place.

Apparently I wasn't clear enough in release notes. I've just updated it, [can you please have a look](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.3.0-beta3)? 🙏 

We tried all the other options we had before going with method swizzling; such as `NSURLProtocol`, `NSProxy`-over-`URLSession`, `isa`-swizzle `URLSession` objects.
But none of them quite worked unfortunately.
We tried to make method swizzling the least invasive possible: we don't do it unless it's enabled by user action, we don't change `_cmd` parameter, we don't add new methods to runtime, we don't change execution path by not calling original implementation, etc.

If you'd like, you can have a look at how we do what we do in [`URLSessionSwizzler`](https://github.com/DataDog/dd-sdk-ios/blob/1.3.0-beta3/Sources/Datadog/Core/AutoInstrumentation/URLSessionSwizzler.swift), [`MethodSwizzler`](https://github.com/DataDog/dd-sdk-ios/blob/1.3.0-beta3/Sources/Datadog/Core/AutoInstrumentation/MethodSwizzler.swift#L63) and [`TracingInterceptor`](https://github.com/DataDog/dd-sdk-ios/blob/1.3.0-beta3/Sources/Datadog/Tracing/TracingAutoInstrumentation.swift#L50) files.

I hope that helps 🙏

**Comment by marcelofabri** [comment]
Awesome, much clearer! Thanks 🥇
