### ISSUE TITLE
Save UserInfoProvider.value across sessions

### ISSUE THREAD

**Issue by flobories** [DataDog/dd-sdk-ios#172]
### Feature request

Persist user info across sessions, set by `Datadog.setUserInfo(id:name:email:)`

### Description

It appears that the user's info (`id`, `name`, `email`) is only stored in memory, and not persisted across sessions.

This is problematic when logging launch time sequence events: in my application, I am asynchronously loading user information from my Apollo SQL cache in order to speed up the time to first layout pass for a better experience.
That information is then set on `Datadog` for future logging, by that happens on another thread. See this sample code:
```
context.workspaceRepository.users
    .distinctUntilChanged(WorkspaceUserInfo.isMeEqual)
    .observeOn(ConcurrentDispatchQueueScheduler(qos: .background))
    .subscribe(onNext: { [weak self] result in
        switch result {
        case .success(let users):
            guard let me = users.me else {
                ...
                return
            }

            log.info("Setting up Datadog", .app)
            Datadog.setUserInfo(id: me.id, name: me.profile.displayName, email: me.profile.email)

        case .failure(let error):
            ...
        }
    })
    .disposed(by: bag)
```

The consequence is that the first milliseconds of my launch sequence logging are not attributed to any users.
This is especially confusing when filtering logs with `email: me@myself.com` for instance, because it filters-out early launch!
![image](https://user-images.githubusercontent.com/7430239/87106491-6f41bb00-c212-11ea-9038-d4029bb4b1e8.png)
☝️ In the log explorer, I am not seeing `📱 Will finishlaunching`

👇 Which is present in my console output locally:
![image](https://user-images.githubusercontent.com/7430239/87106720-e70fe580-c212-11ea-822f-85a4aba6ed80.png)

This has been problematic for me to debug my session tracking code for instance.

### Possible solutions

I could persist it myself as a one-off, say in `UserDefaults` and set it synchronously, but I was expecting `Datadog` would do this for me and only clear user info when explicitly set back to `nil`.

Would you consider `Datadog` persisting this info directly?

Library such as AppCenter do this themselves for instance, see code [here](https://github.com/microsoft/appcenter-sdk-apple/blob/develop/AppCenter/AppCenter/Internals/Context/UserId/MSUserIdContext.m#L96) 

Let me know if this makes sense!

**Comment by buranmert** [comment]
hi again @flobories 👋 
first of all, thanks for this issue with all that sample code and screenshots! 💯 

if i understand well, at launch you do **not** know what your user info is and you _assume_ it'll be the same as the last launch.
if so, we'd like not to make such an assumption on how your apps work in the SDK.
as you already mentioned, our users are free to persist user info and/or other data however they like according to their apps' needs _(eg: encrypted, non-encrypted, in keychain, in user defaults, in a database or not at all)_

please let me know if i'm missing a point here!

**Comment by flobories** [comment]
Hi @buranmert, 👋 makes sense to me for `Datadog` not to assume anything about the current user before it being explicitly set.

To be fair, I *do know* who the user is because they have not logged out, it's just that my SQL access to the current user info is asynchronous, and does not block the launch sequence, thus I am missing user attribution for the first ~5 logs on any given launch.

I can implement a synchronous user info access for myself. I wanted to make sure it was an intentional design decision for you not to persist user info by default before moving forward!

Thanks for the quick reply and the regular updates to your SDK 🚀
