### ISSUE TITLE
is NOT allowed to set HSTS for main doc 

### ISSUE THREAD

**Issue by Jaeger87** [DataDog/dd-sdk-ios#1729]
### Question

I'm implementing Datadog logging for an iOS app. In the internal logs of my app, I see this message:

"Task <xxx>.<x> request https://browser-intake-datadoghq.com/api/v2/logs?ddsource=ios is NOT allowed to set HSTS for main doc (null)."

This doesn't always appear when logging something to Datadog, but if I check the Datadog log dashboard, I find the log correctly registered. Can you explain if what I'm seeing is an error or just a failed connection attempt?

**Comment by maciejburda** [comment]
Thanks for asking @Jaeger87!

Our SDK ensures https connection for the upload (unless custom proxy is used).

It seems there's a similar question posted on [apple developer forum](https://forums.developer.apple.com/forums/thread/746326). I'll discuss further with the team and see if there's anything we could do. As of now, I think it's not causing any real issues. It's just how iOS treats those requests and decides to log the warning.

Please let us know if you spot any discrepancies or problems related to it.

**Comment by Jaeger87** [comment]
Thank you @maciejburda, for now both RUM and Logs works. thank you!
