### ISSUE TITLE
2.7.1 - RUM not delivered, reporting internet connection offline when connected to wifi

### ISSUE THREAD

**Issue by krames133** [DataDog/dd-sdk-ios#1736]
### Describe the issue

RUM data is not being delivered and following error is logged:
`Task <C709767E-3D20-4456-9D06-CCE676C5DF3C>.<1> finished with error [18,446,744,073,709,550,607] Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey=50, NSUnderlyingError=0x281fb1770 {Error Domain=kCFErrorDomainCFNetwork Code=-1009 "(null)" UserInfo={_NSURLErrorBlockedTrackerFailureKey=true, _kCFStreamErrorDomainKey=1, _kCFStreamErrorCodeKey=50, _NSURLErrorNWPathKey=satisfied (Path is satisfied), interface: en0[802.11], ipv4, dns, uses wifi}}, _NSURLErrorFailingURLSessionTaskErrorKey=LocalDataTask <C709767E-3D20-4456-9D06-CCE676C5DF3C>.<1>, _NSURLErrorRelatedURLSessionTaskErrorKey=(
    "LocalDataTask <C709767E-3D20-4456-9D06-CCE676C5DF3C>.<1>"
), NSLocalizedDescription=The Internet connection appears to be offline., NSErrorFailingURLStringKey=https://browser-intake-datadoghq.com/api/v2/rum?ddsource=ios&ddtags=service:app.seerist,version:1.4,sdk_version:2.8.0,env:test, NSErrorFailingURLKey=https://browser-intake-datadoghq.com/api/v2/rum?ddsource=ios&ddtags=service:app.seerist,version:1.4,sdk_version:2.8.0,env:test, _kCFStreamErrorDomainKey=1}`

### Reproduction steps

Installed latest version of DD SDK. Run application and error appears in console. No Data is appearing in dashboard (Was appearing for 1.x integration).

### Device Information

iOS iPAD connected to Wifi

### SDK version

2.7.1

### Integration Methods

SPM

**Comment by maciejburda** [comment]
Thanks for the report @krames133

Basing on the log, I think you're referring to `2.8.0`.

We have spotted this issue with `2.8.0` release earlier today, where it wasn't properly sending the data for some iOS versions. It's related to Privacy Manifest setup. We have taken down `2.8.0` release and submitted the [hotfix](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.8.1) `2.8.1`.

It's currently pending a CI job to create all the artefacts. It should be fully available on all package managers later today.

**Comment by krames133** [comment]
@maciejburda Thanks for responding. I will try to verify the version I'm on. But actually the issue was resolved once i restarted my iPad. So this issue can be closed.
