### ISSUE TITLE
Version 2.8.0

### ISSUE THREAD

**Issue by msrutek-paylocity** [DataDog/dd-sdk-ios#1738]
### Question

What happened to version 2.8.0? Has it been taken down? We've updated to the version and we're getting the following error.

> Dependencies could not be resolved because no versions of 'dd-sdk-ios' match the requirement 2.8.0 and root depends on 'dd-sdk-ios' 2.8.0.

Should we downgrade to `2.7.1` or wait for `2.8.1`?

**Comment by maciejburda** [comment]
We had to take it down due to upload issue on certain versions of iOS.

Please proceed with `2.8.1` that contains the hotfix.
