### ISSUE TITLE
Swift Package Manager warning: No rule to process file Datadog.modulemap

### ISSUE THREAD

**Issue by ejensen** [DataDog/dd-sdk-ios#1739]
### Describe the bug

When integrating the DataDog SDK through Swift Package Manager, a warning is generated about `Datadog.modulemap` being included in the package.

### Reproduction steps

Integrate the DataDog SDK with Swift Package Manager, or just open the `Package.swift` in this repository. Notice the warning about "No rule to process file Datadog.modulemap"

### Affected SDK versions

2.8.1

### Latest working SDK version

N/A

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

SPM

### Xcode Version

Xcode 15.3 (15E204a)

### Swift Version

Swift 5.10

**Comment by maciejburda** [comment]
Thanks reporting and providing the fix! 

We'll review with the team as soon as possible and let you know in the Pull Request.

**Comment by maxep** [comment]
We have removed the modulemap in #1746
