### ISSUE TITLE
Is it safe to call enable multiple times?

### ISSUE THREAD

**Issue by trevor-holliday-instacart** [DataDog/dd-sdk-ios#1748]
### Question

We want to have the ability to dynamically change values on our tracking configurations during the run of an application. An example being changing the SampleRate. 

Is it safe to call 

`Rum.enable()`
`Trace.enable()`
`Logs.enable()`
`URLSessionInstrumentation.enable()`

Multiple times with varying configurations through an application lifecycle?

**Comment by maxep** [comment]
Hi @trevor-holliday-instacart,

Doing so will re-create the Features, meaning that you will loose the states such as logs' global attributes or current RUM session. It is technically safe but it's more of a reset than dynamic configuration. Would that still answer your need?

If not, feel free to open a feature-request through our support channel. It will help us assess demand and define priorities.

**Comment by trevor-holliday-instacart** [comment]
@maxep that does make sense. Thank you.
