### ISSUE TITLE
Update Apple Privacy Manifest - add NSPrivacyAccessedAPICategorySystemBootTime

### ISSUE THREAD

**Issue by gabriellupu** [DataDog/dd-sdk-ios#1749]
### Feature description

DatadogCore is calling [`systemUptime()`](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Kronos/KronosTimeFreeze.swift#L82) method that according to [Apple Docs](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api#4278394) needs to be reflected in the privacy manifest file as `NSPrivacyAccessedAPICategorySystemBootTime`

### Proposed solution

```xml
<key>NSPrivacyAccessedAPITypes</key>
<array>
  <dict>
    <key>NSPrivacyAccessedAPIType</key>
    <string>NSPrivacyAccessedAPICategorySystemBootTime</string>
    <key>NSPrivacyAccessedAPITypeReasons</key>
    <array>
      <string>35F9.1</string>
    </array>
  </dict>
</array>
```

**Comment by gabriellupu** [comment]
closed since this belongs in [Kronos dependency](https://github.com/MobileNativeFoundation/Kronos/issues/111#issuecomment-2020945778)

**Comment by maxep** [comment]
Hey @gabriellupu 👋 

Did you get any warning from Apple?
Because `TimeFreeze.systemUptime()` in Kronos is different from `ProcessInfo.processInfo.systemUptime`, only the later one needs to be declared.

**Comment by gabriellupu** [comment]
hey @maxep 👋🏻  thanks a lot for the quick feedback!
Yes we got a `NSPrivacyAccessedAPICategorySystemBootTime` warning from AppStore.
Unfortunately Apple warning is not pointing the source of the warning so auditing the code looks like that would be the only place in our codebase where we have anything related to `systemUptime`.

**Comment by maxep** [comment]
Thanks! Looks like Apple is only checking the signature, not the actual symbol.
We should probably add it to our manifest so I'm reopening this ticket. In the meantime, you can add it to your app manifest, it should silent the warning.

**Comment by ncreated** [comment]
👋 [**2.10.0**](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.10.0) is out and it contains the fix to this issue.
