### ISSUE TITLE
App Store Submit Issues

### ISSUE THREAD

**Issue by hyling** [DataDog/dd-sdk-ios#177]
### The issue
When I submit my app to the App Store I get the following errors:

- App Store Connect Operation Error
 ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.datadogqh.Datadog' under the iOS application 'XXX.app'."
- App Store Connect Operation Error
ERROR ITMS-90205: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/DatadogObjc.framework' contains disallowed nested bundles."
- App Store Connect Operation Error
 ERROR ITMS-90206: "Invalid Bundle. The bundle at 'XXX.app/Frameworks/DatadogObjc.framework' contains disallowed file 'Frameworks'."
#### Datadog SDK version:
1.2.2
#### Last working Datadog SDK version:
NA
#### Dependency Manager:
Carthage
#### Other toolset:
NA
#### Xcode version:
11.3.0
#### Swift version:
5.0
#### Deployment Target:
iOS 11, iPhone
#### macOS version:
10.14.5

**Comment by ncreated** [comment]
Hello @hyling 👋. Thank you once again for reporting us the issue and sorry for troubles. This should be fixed in #182. I will let you know once the hotfix is released.

**Comment by ncreated** [comment]
Fixed in [`1.2.3`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.2.3) ✅

**Comment by hyling** [comment]
Awesome!  Thanks for the quick fixes.
