### ISSUE TITLE
How do all SampleRates work on iOS?

### ISSUE THREAD

**Issue by ElonPark** [DataDog/dd-sdk-ios#1780]
### Question

Since the release of DataDog SDK 2.0, several SampleRate variables have been added.
but nowhere in the documentation is it explained how they are correlated and how much is finally sampled.

This is critical because if accidentally set a high SampleRate in the app, it will affect the server's sampling as well.

It would be nice to see a more detailed explanation of how each of these apply.

- Trace.sampleRate // 1
  - urlSessionTracking. firstPartyHostsTracing.sampleRate // 2
- RUM.sessionSampleRate // 3
  - urlSessionTracking.firstPartyHostsTracing // 4 <- difference from urlSessionTracking in tracer ???
- WebViewTracking.logsSampleRate // 5

What if I only want to sample 1% of all app sessions and trace all API networks that occur within those sessions so that I can integrate with APM?

**Comment by ganeshnj** [comment]
Thanks for filing an issue. This is actually an interesting and definitely ambiguous area.

I will start with Trace product first.

Before we go into the details, let's first see how the sampling is done on a high level.

1. All spans that recorded irrespective of the sampling decision `sampled` or `not sampled`, are sent to the Datadog.
2. `_dd.agent_psr` property is set to the sampling rate applied in the SDK.
3. `metrics._sampling_priority_v1` is set to either `1` if sampled or `0` if not sampled.

Now, back to sampling rates

## Trace sampling rate

[Trace sampling rate](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogTrace/Sources/TraceConfiguration.swift#L32) is applied to the local spans which are recorded using the `start` and `finish` or similar APIs.

Now, let's say your sampling rate is set to `50`. This means all the spans recorded and sent to the Datadog. Every span event will have `_dd.agent_psr` set to `50` and `metrics._sampling_priority_v1` set to `1` (sampled) or `0` (not sampled) based on the sampling decision.

You will see only 50% of the spans in the Datadog UI.

## URLSessionTracking sampling rate

[URLSessionTracking sampling rate](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogTrace/Sources/TraceConfiguration.swift#L106) is applied to the trace context propagation only. For example, if you are using W3C trace context propagation, the [sampled flag](https://www.w3.org/TR/trace-context/#sampled-flag) is set based on the sampling decision.

Now, let's say your sampling rate is set to `50`. This means only 50% of the requests to your backend will have the `sampled` flag set to `true`.

All Datadog agents will receive the trace context propagation headers and will do the right thing. ie you will be able to see 50% the distributed traces in the Datadog UI.

Both trace and URLSessionTracking sampling rates are independent of each other.

*Now, the complicated part when both local spans and URLSessionTracking are involved.*

## Local span as active + Distributed trace

You can start a local span and mark as `active` ie all the spans created after this span will be part of the same trace which includes the spans created in the distributed trace.

The experience looks like this:

1. If both local span and distributed trace are sampled, you will see the entire trace in the Datadog UI.
2. If local span is sampled but distributed trace is not sampled, you will see the local span but not the distributed trace.
3. If local span is not sampled but distributed trace is sampled, you will see the distributed trace but not the local span.

This is applicable for 2.9.0 version of the SDK.

🧵  1/3

**Comment by ganeshnj** [comment]
Now on RUM product.

RUM has session based sampling. Read more about [session here](https://docs.datadoghq.com/real_user_monitoring/guide/understanding-the-rum-event-hierarchy/)

Customers can enable RUM and can take advantage of distributed tracing. Both RUM session sampling rate and URLSessionTracking sampling rate are independent of each other.

There is literally no difference between the RUM URLSessionTracking tracking and the Trace URLSessionTracking sampling rate. I would advise customers to use either one of them. If you are not using local spans, using URLSessionTracking with RUM makes more sense.

🧵  2/3

**Comment by ganeshnj** [comment]
WebView tracking

WebView tracking is powered by [RUM browser SDK](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/web_view_tracking/?tab=cocoapods) ie you need to enable browser SDK to track in your website and when the page is loaded in the WebView, the RUM browser SDK will send the RUM events to the native iOS SDK, which will send to the Datadog.

Now [logsSampleRate](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogWebViewTracking/Sources/WebViewTracking.swift#L42) is applied to the logs sent by the RUM browser SDK.

🧵  3/3

**Comment by ganeshnj** [comment]
Finally

> What if I only want to sample 1% of all app sessions and trace all API networks that occur within those sessions so that I can integrate with APM?

You can do with enabling the RUM product only.

```swift
RUM.enable(
    with: RUM.Configuration(
        applicationID: "<your app id>",
        sessionSampleRate: 1,
        urlSessionTracking: .init(
            firstPartyHostsTracing: .trace(hosts: ["<your hostname>"], sampleRate: 100)
        )
    )
)
```

**Comment by ElonPark** [comment]
Thanks for the detailed explanation!

So we don't need to call `Trace.enable`?

What are the actual expected results of setting this?
```swift
    RUM.enable(
        with: RUM.Configuration(
            applicationID: "<app id>",
            sessionSampleRate: 1,
            urlSessionTracking: .init(
              firstPartyHostsTracing: .traceWithHeaders(
                hostsWithHeaders: ["<hostname>": [.datadog]],
                sampleRate: 100
              )
            )
        )
    )

    Trace.enable(
      with: .init(
        sampleRate: 1,
        urlSessionTracking: .init(
          firstPartyHostsTracing: .traceWithHeaders(
            hostsWithHeaders: ["<hostname>": [.datadog]],
            sampleRate: 100
          )
        ),
        bundleWithRumEnabled: true,
        networkInfoEnabled: true
      )
    )
```

As I asked in the last question, I only want to see 1% of all sessions using the app, and I want all the APIs that happen in it to be linked to APM via Trace.

If that happens, will I be charged extra on the server side for tracing those APIs?

**Comment by ElonPark** [comment]
Lastly, as you mentioned, if we set this up, will the servers be charged extra for reading the data because of the sampling?

```swift
RUM.enable(
    with: RUM.Configuration(
        applicationID: "<your app id>",
        sessionSampleRate: 1,
        urlSessionTracking: .init(
            firstPartyHostsTracing: .trace(hosts: ["<your hostname>"], sampleRate: 100)
        )
    )
)
```

**Comment by ganeshnj** [comment]
Setting up `urlSessionTracking` results in registration of [NetworkInstrumentationFeature](https://github.com/DataDog/dd-sdk-ios/blob/5ec20024e14d2d8f3e14095338eeb0503c303eab/DatadogInternal/Sources/NetworkInstrumentation/NetworkInstrumentationFeature.swift#L42-L43)

If you try to register from multiple places like in the example above, this is not going any side affect because of [this check](https://github.com/DataDog/dd-sdk-ios/blob/f6a6df35d09d1f6ee0f8f508a115da6c6d9eaf77/DatadogInternal/Sources/NetworkInstrumentation/DatadogURLSessionHandler.swift#L54)

When you enable both, then you get benefit of all features which I mentioned above. Automatic resources tracking, local spans, distributed tracing.

>As I asked in the last question, I only want to see 1% of all sessions using the app, and I want all the APIs that happen in it to be linked to APM via Trace.

You can get 1% sessions + APM distributed capability all with RUM. _The only caveat in this approach_ is start of your trace, because you have 1% session sampled, only 1% of traces will have start point as your app, rest of the 99% of the traces will have start point as your first backend (first system that has distributed tracing enabled). The reason I mentioned in https://github.com/DataDog/dd-sdk-ios/issues/1780#issuecomment-2061040010 (Session contains the trace and span information)

If you want to have entire trace, then you must enable both Trace and RUM. Keep RUM at 1% and Trace at 100%

```swift
RUM.enable(
    with: RUM.Configuration(
        applicationID: "<app id>",
        sessionSampleRate: 1,
        urlSessionTracking: .init(
          firstPartyHostsTracing: .traceWithHeaders(
            hostsWithHeaders: ["<hostname>": [.datadog]],
            sampleRate: 100
          )
        )
    )
)

Trace.enable(
  with: .init(
    sampleRate: 100,
    urlSessionTracking: .init(
      firstPartyHostsTracing: .traceWithHeaders(
        hostsWithHeaders: ["<hostname>": [.datadog]],
        sampleRate: 100
      )
    ),
    bundleWithRumEnabled: true,
    networkInfoEnabled: true
  )
)
```

You have to set the Trace's sample rate also to 100% because we use Tracer's sample rate here to set `metrics._sampling_priority_v1`.  If you would use 1% sampling rate on Trace, the behavior will be identical to RUM, 1% your trace will have start point as your app, other 99% will have start of trace as your backend.

>Lastly, as you mentioned, if we set this up, will the servers be charged extra for reading the data because of the sampling?

You will be charged for RUM based on number of sessions, more information [here](https://www.datadoghq.com/pricing/?product=real-user-monitoring--session-replay#products)

For APM, you will be charged per host basis, more information [here](https://www.datadoghq.com/pricing/?product=application-performance-monitoring#products)
