### ISSUE TITLE
How can we group views as service.

### ISSUE THREAD

**Issue by dineshiOSDev** [DataDog/dd-sdk-ios#1831]
### Question

We are tracking views with custom UIKitRUMViewsPredicate.
We need to group/ tag them to under specific service.  So that we can filter out based on service. 

`datadogRum.startView({ viewName, service });`
We see the web app has this ability to track view with specific name and service name. 

But on mobile sdk we see the ability to set service name only at the time of initializing the SDK's.

Any help is much appreciated.

**Comment by maxep** [comment]
Hey @dineshiOSDev 👋 

We don't have this ability on the mobile SDKs, the `service` is the application itself and can be set during [SDK init](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/ios/?tab=cocoapods#initialize-the-library), the default value will be the Bundle ID.
If you want to group your views you can add a custom attribute to your view in your custom predicate. You could also set a custom  `path` to something like `/<group>/<view id>`. Both will allow you to filter your views on the Datadog platform.

I hope this helps!
