### ISSUE TITLE
How to dynamically change configurations, such as using a remote config?

### ISSUE THREAD

**Issue by epau** [DataDog/dd-sdk-ios#1859]
### Question

Hey folks, curious if ya'll could prescribe the best way to change configuration values during runtime. 
We want to control our configuration via a remote config, similar to [this example](https://docs.datadoghq.com/real_user_monitoring/guide/remotely-configure-rum-using-launchdarkly/). This way, anytime the configuration changes, we can update our Datadog configuration accordingly without requiring the app to be terminated and cold-launched. 

Should we call `.enable` again for each module? ie ` RUM.enable(with: configuration)` etc.

Should we create a new core? If so, should we give it a unique name or reuse the same name? Should we stop the previous core? ie `Datadog.sdkInstance(named: "my-instance")`

Any details on a preferred approach here would be fantastic. Thank you!

**Comment by ganeshnj** [comment]
Hey @epau, thanks for reaching out.

A short answer here in your case is it depends on the type of configuration.

- If your configuration is related to the SDK Core, you need to [stop the previous instance](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Datadog.swift#L317) and [create a new one](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Datadog.swift#L366) with the new configuration. Trying to re-initialize the SDK Core with the same name will result in an error per https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Datadog.swift#L400. The features will automatically pick up the new updated SDK Core instance.

- If your configuration is related to the specific feature (RUM, Trace, Logs etc), you can re-enable the feature with the new configuration and it will update the configuration for that feature. Make sure you don't change the SDK Core instance here.

- If you end up changing the SDK Core name, then you have to first Stop the previous instance and then [create a new one with the new name](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogCore/Sources/Datadog.swift#L366). Re-enable the SDK features with the new core instance.

Hope this helps!

I'm curious about your use case if you can share more details about it.

**Comment by ganeshnj** [comment]
You should be able to achieve your described case with current set of APIs as I mentioned in my previous comment.

**Comment by epau** [comment]
This is working as expected, thank you for the comments!
