### ISSUE TITLE
Crash at initialization in iOS 15 / 16

### ISSUE THREAD

**Issue by JonathanFuentesF** [DataDog/dd-sdk-ios#1875]
### Stack trace

![Screenshot 2024-05-31 at 1 48 49 PM](https://github.com/DataDog/dd-sdk-ios/assets/60158789/99e053bc-a41e-49e8-b740-6a4dcc6dd830)

### Reproduction steps

Call Datadog.initialize(appContext:trackingConsent:configuration:)

### Volume

100% of iOS 15/ 16 users

### Affected SDK versions

1.17.0

### Latest working SDK version

1.17.0

### Does the crash manifest in the latest SDK version?

Yes

### Deployment Target

iOS 13+

### Device Information

All devices with iOS 15/16

### Other relevant information

This works fine in iOS 17

**Comment by maxep** [comment]
Hi @JonathanFuentesF 👋 

Version 1.17.0 has reached end of support, please have a look at our [deprecation policy](https://docs.datadoghq.com/real_user_monitoring/guide/mobile-sdk-deprecation-policy/). I strongly advise you to migrate to a newer version and benefit from bug fixes, you can follow [this migration guide](https://docs.datadoghq.com/real_user_monitoring/guide/mobile-sdk-upgrade/?tab=ios).

That being said, the stack trace you have shared doesn't say much about the crash. Could it be related to #1509?

**Comment by anuragajwani** [comment]
We had a similar issue when building DD ios sdk 2.11.0 using carthage, Xcode 15.1 and running on iOS 16. iOS 17 was working fine. We are now testing the same but with Xcode 15.4 to see whether the built binary changes based on the Xcode version.

It seems like the binary provided in GH releases is built using Xcode 14.3.1 and thus the issue could be specific to Xcode 15.1.

Will post a separate issue if the issue persists on iOS 16 when building with Xcode 15.4.

**Comment by maxep** [comment]
Closing in favour of #1880
