### ISSUE TITLE
ISO8601DateFormatter: NSInternalInconsistencyException crash on iPhone 6/6s 

### ISSUE THREAD

**Issue by ncreated** [DataDog/dd-sdk-ios#189]
### The crash

Although this `ISO8601DateFormatter` crash on iOS `11.0.x` - `11.1.x` was fixed in #126:

```
Fatal Exception: NSInternalInconsistencyException
Invalid parameter not satisfying: formatOptions == 0 || !(formatOptions & ~(NSISO8601DateFormatWithYear | NSISO8601DateFormatWithMonth | NSISO8601DateFormatWithWeekOfYear | NSISO8601DateFormatWithDay | NSISO8601DateFormatWithTime | NSISO8601DateFormatWithTimeZone | NSISO8601DateFormatWithSpaceBetweenDateAndTime | NSISO8601DateFormatWithDashSeparatorInDate | NSISO8601DateFormatWithColonSeparatorInTime | NSISO8601DateFormatWithColonSeparatorInTimeZone | NSISO8601DateFormatWithFullDate | NSISO8601DateFormatWithFullTime | NSISO8601DateFormatWithInternetDateTime))
```

we still get reports ([1](https://github.com/DataDog/dd-sdk-ios/issues/126#issuecomment-658818341), [2](https://github.com/DataDog/dd-sdk-ios/issues/126#issuecomment-660145991)) on its occurrences **on `iOS 11.0.3 iPhone 6/6s` and `iOS 11.1.2 iPhone 6s`**.

This was originally fixed in #129 by opting-out from using `.withFractionalSeconds` below `iOS 11.2`:
```diff
let formatter = ISO8601DateFormatter()
- formatter.formatOptions.insert(.withFractionalSeconds)
+ if #available(iOS 11.2, *) {
+   formatter.formatOptions.insert(.withFractionalSeconds)
+ }
```

It seems to not work on iPhone 6 and 6s.

---

#### Datadog SDK versions:

`1.2.2`

#### OS version + device version:

* iOS 11.0.3 iPhone 6
* iOS 11.0.3 iPhone 6s
* iOS 11.1.2 iPhone 6s

**Comment by mduong** [comment]
Thanks @ncreated. We had a few crash reports come in over the weekend from additional devices/OSes that indicate the issue affects more than just the iPhone 6 and 6s:

iOS 11.0.0 iPhone 6s
iOS 11.0.2 iPhone 8
iOS 11.0.3 iPhone 6s Plus
iOS 11.1.0 iPad Air 2
iOS 11.1.0 iPhone SE
iOS 11.1.1 iPhone 6s

**Comment by mduong** [comment]
@ncreated digging deeper into our DataDog logs, we found that somehow it was using SDK version 1.2.0 instead of 1.2.2. We'll figure out what happened there and make sure to update to 1.2.2+. Apologies for the mixup.

**Comment by ncreated** [comment]
@mduong thanks for the follow up 🙂! I'm happy to close this 👍.
