### ISSUE TITLE
`macOS` SDK initialization performs synchronous network request

### ISSUE THREAD

**Issue by NachoSoto** [DataDog/dd-sdk-ios#1929]
### Describe the bug

Calling `Datadog.initialize` on app launch in the main thread ends up calling `DeviceInfo.init`, which makes [this call](https://github.com/DataDog/dd-sdk-ios/blob/2.13.0/DatadogInternal/Sources/Context/DeviceInfo.swift#L112)

```swift
Host.current().name
```

These are the docs for `Host.current()`:
> This method executes synchronously. The execution time of this method can be highly variable, depending on the local network configuration, and may block for several seconds if the network is unreachable. To avoid blocking execution on the main thread, you should call this method in an `Operation` or Grand Central Dispatch block that executes asynchronously in the background.

### Reproduction steps

Initialize SDK on a macOS app using `Datadog.initialize`.

### SDK logs

![Screenshot 2024-06-27 at 08 41 40](https://github.com/DataDog/dd-sdk-ios/assets/685609/6dd633a2-5553-48d9-97cb-636acaa4d1ce)

### Expected behavior

No synchronous network requests.

### Affected SDK versions

2.13.0

### Latest working SDK version

2.10.1

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

SPM

### Xcode Version

Xcode 15.4 Build version 15F31c

### Swift Version

5.10

### MacOS Version

14.5 (23F79)

### Deployment Target

macOS

### Other relevant information

This was introduced by bd29f613798aa243971875516be3b4d041c594bb

**Comment by ncreated** [comment]
Hey @NachoSoto 👋. Indeed, the use of `Host.current().name` wasn't necessary and it is already removed in recent `develop`. We're considering starting `2.14.0` release early next week - if everything goes smooth it should be available by the end of next week, but I can't promise the exact ETA. Sorry you faced this issue, please stay tuned for `2.14.0`!

**Comment by maxep** [comment]
Fixed in [2.14.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.14.0)
