### ISSUE TITLE
Two questions about `URLSessionInstrumentation`

### ISSUE THREAD

**Issue by rudedogdhc** [DataDog/dd-sdk-ios#1958]
### Question

One, is it acceptable to call `URLSessionInstrumentation.enable(with:)` for more than one delegate class? I.e., can I do

```
URLSessionInstrumentation.enable(with: .init(delegateClass: SomeDelegate.self)
URLSessionInstrumentation.enable(with: .init(delegateClass: SomeOtherDelegate.self)
```

Two, do the delegates need to adopt `URLSessionDataDelegate` or is adopting `URLSessionDelegate` sufficient?

**Comment by maciejburda** [comment]
Thanks for tuning in @rudedogdhc,

1. Yes - it's acceptable to register multiple classes of the delegate using `enable(with:)`.
2. `URLSessionDataDelegate` is the exact requirement, although there's a dependency between those protocols.
