### ISSUE TITLE
Data dog crash logs are not symbolicating.

### ISSUE THREAD

**Issue by dineshiOSDev** [DataDog/dd-sdk-ios#1990]
### Question

Hi

We are able to get the crash trigger via datadog but we are facing problem with symbolication of the same.
We are uploading the dSYMs file and i can see the same in Debug Symbols page  as well.

But its not getting symbolicated and we see below warning.
`The stack trace could not be symbolicated because no dSYM could be found for this application`

SDK Version:
2.13.0

Any help is much appreciated.

**Comment by ganeshnj** [comment]
👋  @dineshiOSDev 

1. Are you seeing this for OS frames or application frames?
2. Also, are you running on simulator or device?
3. Could you confirm that the `binary_images` attached to error event has same UUID for the application symbol that you have uploaded?

You can check the UUID using 
```
dwarfdump --uuid {dsym_file_path}
```

**Comment by dineshiOSDev** [comment]
@ganeshnj  Thank You for getting back so quickly 
I really appreciate your response.

The particular UUID was missing and uploaded the same and now able to see the crash on exact line.

Also is there any reference doc that can help us that supports dsym file upload with bitrise automatically.
Please feel free to close this issue.

**Comment by ganeshnj** [comment]
you can use datadog-ci to upload the dsym files from your CI systems. There are some ready to use solutions as described [here](https://docs.datadoghq.com/real_user_monitoring/error_tracking/mobile/ios/?tab=cocoapods#upload-your-dsym-file). For bitrise you would need to follow https://github.com/DataDog/datadog-ci/blob/master/src/commands/dsyms/README.md
