### ISSUE TITLE
URLSessionInstrumentation not accessible

### ISSUE THREAD

**Issue by ugiacoman** [DataDog/dd-sdk-ios#2010]
### Describe the bug

The `URLSessionInstrumentation` enum exists in `DatadogInternal`. In your `Package.swift`, `DatadogInternal` is not declared as a top level product. This prevents us getting auto url tracing setup as we cannot set the delegate's swizzle. Your docs mention this is the way to setup auto tracing [here](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/advanced_configuration/ios/?tab=swift#automatically-track-network-requests). 

### Reproduction steps

I haven't tried these repro steps but this should theoretically allow for you to reproduce the issue. I was able to build locally but when I went to build on CI and there wasn't cache, I ran into the error.
1) Create an SPM package
2) Add the Datadog SDK as a dependency
3) Access `URLSessionInstrumentation`
4) Build for release. You should see a linker error declaring that there are undefined symbols.

### Expected behavior

`URLSessionInstrumentation` should be accessible. It does not seem that `DatadogInternal` should be exposed as a product, but there might be a better home for `URLSessionInstrumentation` if that is how you'd like the swizzle to function.

### Affected SDK versions

2.15.0

### Latest working SDK version

N/A

### Did you confirm if the latest SDK version fixes the bug?

No

### Integration Methods

SPM

### Xcode Version

15.1

**Comment by maxep** [comment]
Hey @ugiacoman 👋 

`URLSessionInstrumentation` is also exposed by `DatadogRUM` [here](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogRUM/Sources/RUMConfiguration.swift#L15) and `DatadogTrace` [here](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogTrace/Sources/TraceConfiguration.swift#L15) which are both top-level modules. If you import either modules, you should get access to `URLSessionInstrumentation`.

```swift
import DatadogRUM
// import DatadogTrace

URLSessionInstrumentation.enable(
    with: .init(
        delegateClass: <YourSessionDelegate>.self
    )
)

let session = URLSession(
    configuration: .default,
    delegate: <YourSessionDelegate>(),
    delegateQueue: nil
)
```

Let me know if that helps!

**Comment by maxep** [comment]
Hey 👋  Please, let us know if importing `DatadogRUM` or `DatadogTrace` didn't solve your issue.

**Comment by ugiacoman** [comment]
Hey @maxep, thanks for responding. Yes, it worked but we had to direct the compiler to the correct namespace. So instead of referencing `URLSessionInstrumentation`, we explicitly detailed the namespace `DatadogRUM.URLSessionInstrumentation`.
