### ISSUE TITLE
Prevent warning: Code path does I/O on the main thread underneath that can lead to UI responsiveness issues

### ISSUE THREAD

**Issue by boyceEstesHalo** [DataDog/dd-sdk-ios#2027]
### Question

Hi,

I have noticed that there has recently been a warning for main thread UI hangs from Datadog (ver 2.15.0) on Xcode 15.4 (15F31d). I've attached a couple of screenshots. Do you have any insights into what could be happening to cause this and what I could do in my initialization logic that could prevent this from happening? 

Simply enabling the RUM enablement in a background queue like `DispatchQueue.global().async` did not affect the problem at all. And the warning will stop appearing if I comment out the RUM enablement.

Please let me know if I am misunderstanding something in the initialization process or if there is an update that I will need to install later to fix the issue.

<img width="1304" alt="Screenshot 2024-08-19 at 14 44 52" src="https://github.com/user-attachments/assets/e6a1677a-33e4-4c9d-b5db-3c37e26626f4">

![Screenshot 2024-08-27 at 17 21 20](https://github.com/user-attachments/assets/c6f0d596-8ce9-4deb-98b2-bb215fe85c9f)

**Comment by maciejburda** [comment]
Hello @boyceEstesHalo 

Thank you for reaching out!

From our observation, it looks like you are currently using version 1.15.0 of the SDK. According to our [Mobile SDK Deprecation Policy](https://docs.datadoghq.com/real_user_monitoring/guide/mobile-sdk-deprecation-policy/#lifecycle-of-major-sdk-versions), we kindly request that you update your SDK to the latest version. This update will ensure compatibility with our systems and allow us to continue providing you with the best possible support.

For detailed instructions on upgrading your SDK, please refer to our [Mobile SDK Upgrade Guidelines](https://docs.datadoghq.com/real_user_monitoring/guide/mobile-sdk-upgrade/?tab=ios).

If you have any questions or need assistance during the upgrade, feel free to reach out—we’re happy to help!
