### ISSUE TITLE
Custom attributes aren't show up for session but for action

### ISSUE THREAD

**Issue by vani2** [DataDog/dd-sdk-ios#2036]
### Question

I had an issue before https://github.com/DataDog/dd-sdk-ios/issues/1601 and unfortunately, did't dig deeper to find out.

SDK version: 2.16.0
iPhone 14 Pro, iOS 18.0
Xcode 15.4 (15F31d)

After my app is launched, I set custom attributes 
```swift
RUMMonitor.shared().addAttribute(forKey: "permissions", value: MyCustomEncodableModel) }
```

So, no problems with the code above. The issue is that I want to filter RUM sessions by these custom attributes and I can't, because it's shown only in actions but no at the top session page. Is there a way to propagate attributes to a session, or explicitly tell the SDK that I want these attributes to be attached to a session and not only to an action?
![Screenshot 2024-09-03 at 14 54 48](https://github.com/user-attachments/assets/0401c5c1-65f4-4bea-9cd0-7c36523dfb98)
![Screenshot 2024-09-03 at 14 55 06](https://github.com/user-attachments/assets/fe7a85fd-14e2-46e2-8006-8e225e5aadb0)

**Comment by mariedm** [comment]
Hello @vani2, you should be able to filter RUM sessions by custom attributes. In the **search bar**, enter `context.your_key:your_value`.

<img width="840" alt="Screenshot 2024-09-09 at 13 24 14" src="https://github.com/user-attachments/assets/3cdd45e0-ffcc-4f44-afcf-d88c6f7bcaaf">

--- 

You can also do this from the attribute itself by clicking the **gear icon** left to it:

<img width="244" alt="Screenshot 2024-09-09 at 13 28 23" src="https://github.com/user-attachments/assets/63456b0c-c31d-4313-9a9e-c28e1c0b377e">

<br>

<img width="419" alt="Screenshot 2024-09-09 at 13 28 35" src="https://github.com/user-attachments/assets/567727b1-79f6-49cb-b417-e67710f82c23">

Let me know if that works for you.

**Comment by vani2** [comment]
Thanks!
