### ISSUE TITLE
List `DatadogInternal` as a `product` in the `Package.swift`

### ISSUE THREAD

**Issue by luispadron** [DataDog/dd-sdk-ios#2055]
### Describe the issue

Im migrating from CocoaPods to SPM and unable to do so because we are missing the `DatadogInternal` module. This is similar to #2010 but for my case I cannot find where several symbols are, like: `AttributeKey`, `TrackingHTTPHeaders`, etc.

Given that `DatadogInternal` is public for CocoaPods we should consider doing the same for SPM to make projects migrating from CocoaPods possible.

### Reproduction steps

- Depend on `dd-sdk-ios`
- Try to use a type defined in `DatadogInternal`

### SDK version

2.13.0

### Integration Methods

SPM

**Comment by luispadron** [comment]
@maxep Ah thank you for the tip on being able to still import it even though its not a product, that worked and our build is back to green without any changes on our end!

If we wanted to expose some of the other fields so users don't need to `import DatadogInternal` that makes sense, I listed some in the original description here but i imagine anything thats `public` in `DatadogInternal` would need to be re-exported by one of the other products instead, maybe `DatadogCore`? 

While `DatadogInternal` is not a product in SPM it is a spec we can depend on in CocoaPods which is where my confusion came from but thank you for the speedy reply i believe we can close this issue

**Comment by maxep** [comment]
Thanks, happy that it unblocked you!

The public interfaces of the `DatadogInternal` are meant for our own usage, we still have few exception that we need to address. Some type are re-exported by our feature modules, like [here](https://github.com/DataDog/dd-sdk-ios/blob/develop/DatadogTrace/Sources/TraceConfiguration.swift#L12L22). But it's not a pattern we should follow as it brings confusion.

Also, please note that `AttributeKey` is a typealias for `String`, there is not need to use it as a type.
