### ISSUE TITLE
Xcode16: Symbol not found when using Cocoapods

### ISSUE THREAD

**Issue by lukas-koblmueller** [DataDog/dd-sdk-ios#2059]
### Stack trace

`dyld[78821]: Symbol not found: __ZN5swift34swift50override_conformsToProtocolEPKNS_14TargetMetadataINS_9InProcessEEEPKNS_24TargetProtocolDescriptorIS1_EEPFPKNS_18TargetWitnessTableIS1_EES4_S8_E
Expected in: /Frameworks/DatadogInternal.framework/DatadogInternal`

### Reproduction steps

1. Use Xcode 16.0
2. Implement Datadog via Cocoapods
3. Run on device

### Volume

All

### Affected SDK versions

2.17.0

### Latest working SDK version

-

### Does the crash manifest in the latest SDK version?

Yes

### Deployment Target

12.0 or 13.0

### Other relevant information

Adding the post-install hook:
`post_install do |installer|
  installer.pods_project.targets.each do |target|
    if ['DatadogRUM', 'DatadogCore', 'DatadogInternal'].include? target.name
      target.build_configurations.each do |config|
        config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      end
    end
  end
end`
fixes this issue on Xcode15, but not on Xcode16 anymore.

**Comment by lukas-koblmueller** [comment]
This is only when still building with Xcode15, when re-building Datadog.xcframeworks with Xcode16 it works. But normally i would expect that also building with Xcode15 should work.

**Comment by maciejburda** [comment]
Hello @lukas-koblmueller 

I've made a fresh Xcode16 project (using [these hints](https://github.com/CocoaPods/CocoaPods/issues/12583) from CocoaPods repo).

I managed to make it work and build on iOS 18 device without any issues.
[CocoaPodsXcode16Test.zip](https://github.com/user-attachments/files/17130223/CocoaPodsXcode16Test.zip)

Could you provide a sample project that reproduces the issue?

**Comment by mariedm** [comment]
Hi, I'm closing this issue as there hasn't been any recent activity. Feel free to reopen it if the problem persists or if you have any further questions.
