### ISSUE TITLE
reference to property 'previousUploadStatus' in closure requires explicit use of 'self' to make capture semantics explicit

### ISSUE THREAD

**Issue by shadhussain-crgl** [DataDog/dd-sdk-ios#2119]
### Describe the bug

When I am trying to deploy my React Native app to iOS, I am receiving the following error message:

`reference to property 'previousUploadStatus' in closure requires explicit use of 'self' to make capture semantics explicit`

The two Datadog libraries I have installed are `@datadog/mobile-react-native` and `@datadog/mobile-react-navigation`. However, this error points to a problem not directly within the actual project code, rather something within the `dd-sdk-ios` library.

### Reproduction steps

I use Bitrise to deploy my app. It was through here that I saw this error message despite the app building and running just fine on my iOS simulator on XCode.

### SDK logs

```
/Users/[REDACTED]/git/ios/Pods/DatadogCore/DatadogCore/Sources/Core/Upload/DataUploadWorker.swift:119:35: error: reference to property 'previousUploadStatus' in closure requires explicit use of 'self' to make capture semantics explicit

      /Users/[REDACTED]/git/ios/Pods/DatadogCore/DatadogCore/Sources/Core/Upload/DataUploadWorker.swift:121:21: error: reference to property 'previousUploadStatus' in closure requires explicit use of 'self' to make capture semantics explicit

      /Users/[REDACTED]/git/ios/Pods/DatadogCore/DatadogCore/Sources/Core/Upload/DataUploadWorker.swift:137:25: error: reference to property 'previousUploadStatus' in closure requires explicit use of 'self' to make capture semantics explicit

      /Users/[REDACTED]/git/ios/Pods/DatadogCore/DatadogCore/Sources/Core/Upload/DataUploadWorker.swift:153:21: error: reference to property 'previousUploadStatus' in closure requires explicit use of 'self' to make capture semantics explicit
```

### Affected SDK versions

2.4.4 - the latest for both `@datadog/mobile-react-native` and `@datadog/mobile-react-navigation`

### Latest working SDK version

N/A - just installed these libraries for DD integration

### Did you confirm if the latest SDK version fixes the bug?

Yes

### Integration Methods

Cocoapods

### Xcode Version

16.1

### Swift Version

6.0.2

### MacOS Version

15.0.1

### Deployment Target

iOS 15+, iPad

**Comment by ncreated** [comment]
Hey @shadhussain-crgl. We need a bit more details here, specifically:

> I use Bitrise to deploy my app. It was through here that I saw this error message despite the app building and running just fine on my iOS simulator on XCode.

what is the Xcode and Swift version that you're using in Bitrise? Is "Xcode 16.1 + Swift 6.0.2" what you use in your local or on CI?

I'm asking because the error suggests you're trying to compile native SDK with older Swift compiler version. Implicit `self` capture was added in Swift 5.8.1 ([SE-0365](https://github.com/swiftlang/swift-evolution/blob/main/proposals/0365-implicit-self-weak-capture.md)) and our SDK supports Swift 5.9+ so this shouldn't be an issue.

**Comment by shadhussain-crgl** [comment]
The Xcode version was 14.1 in the pipeline. I just updated it to use 16.1 and it resolved the issue. Thanks for the help.
