### ISSUE TITLE
iOS SDK Crash - EXC_BAD_ACCESS KERN_INVALID_ADDRESS in NSURLSession Delegate

### ISSUE THREAD

**Issue by sunil-prezzee** [DataDog/dd-sdk-ios#2130]
### Stack trace

Crashed: com.apple.NSURLSession-delegate  
EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000  

```
0     Telemetry.swift - Line 169  
              specialized Telemetry.error(metric:log:buildTags:) + 169  
1     Errors.swift - Line 76  
              Analytics.reportInternalError(_:fatal:) + 76  
2     HTTPClient.swift - Line 101  
              specialized HTTPClient.handleResponse(data:response:error:url:completion:) + 101  
3     closure #1 in HTTPClient.startBatchUpload(writeKey:batch:completion:) + 3236472  
4     partial apply for closure #1 in HTTPClient.startBatchUpload(writeKey:batch:completion:) + 3241276  
5  libsystem_pthread.dylib  
              start_wqthread + 8

```

### Reproduction steps

This issue is intermittent and difficult to reproduce.

Unfortunately, we do not have a minimal code example, as the issue only occurs sporadically in production environments.

### Volume

The crash impacts a small but significant percentage of app sessions (~1%-2% of all users).

### Affected SDK versions

2.19.0 & 2.20.0

### Latest working SDK version

2.20.0

### Does the crash manifest in the latest SDK version?

Yes

### Deployment Target

Our app has a deployment target of iOS 15 and is used on both iPhone and iPad devices.

### Other relevant information

This issue seems to resemble [GitHub Issue #2117](https://github.com/DataDog/dd-sdk-ios/issues/2117), which was closed without resolution. The crash appears to originate in the telemetry reporting mechanism (Telemetry.swift).

**Comment by ncreated** [comment]
@sunil-prezzee Symbols that you listed do not belong to `dd-sdk-ios` code:
- [Telemetry.swift](https://github.com/DataDog/dd-sdk-ios/blob/2.20.0/DatadogInternal/Sources/Telemetry/Telemetry.swift) has no symbol like `Telemetry.error(metric:log:buildTags:)`
- [Errors.swift](https://github.com/DataDog/dd-sdk-ios/blob/2.20.0/DatadogSessionReplay/Sources/Utilities/Errors.swift) has no such a thing as `Analytics.reportInternalError(_:fatal:)`
- There is no such symbols as [`handleResponse`](https://github.com/search?q=repo%3ADataDog%2Fdd-sdk-ios%20handleResponse&type=code) or [`startBatchUpload`](https://github.com/search?q=repo%3ADataDog%2Fdd-sdk-ios+startBatchUpload&type=code) in the whole SDK.

I googled these symbols in [`analytics-swift` SDK](https://github.com/segmentio/analytics-swift), which is likely where you should report the problem:
- [`Telemetry.error(metric:log:buildTags:)`](https://github.com/segmentio/analytics-swift/blob/bfa46967624eb54b046c994ac80b2d65ab24b59d/Sources/Segment/Utilities/Telemetry.swift#L145)
- [`HTTPClient.startBatchUpload(writeKey:batch:completion)`](https://github.com/segmentio/analytics-swift/blob/bfa46967624eb54b046c994ac80b2d65ab24b59d/Sources/Segment/Utilities/Networking/HTTPClient.swift#L55)
- [`Analytics.reportInternalError(_:fatal:)`](https://github.com/segmentio/analytics-swift/blob/bfa46967624eb54b046c994ac80b2d65ab24b59d/Sources/Segment/Errors.swift#L69)

For the same reason we closed https://github.com/DataDog/dd-sdk-ios/issues/2117 - there is nothing to fix in `dd-sdk-ios`.
