### ISSUE TITLE
XCArchive generation fails

### ISSUE THREAD

**Issue by victormendes5** [DataDog/dd-sdk-ios#2132]
Datadog SDK version: 2.20.0
Dependency Manager: SPM
Xcode version: 15.2 (15C500b)
Deployment Target: iOS 15

# Description

I encountered an error while archiving and distributing my SDK.

# Context

I have an SDK distributed via SPM. After integrating it with Datadog, the script to generate the xcarchive fails when executed.

```bash
xcodebuild archive \
-scheme MyFeature \
-destination "generic/platform=iOS" \
-archivePath "build/MyFeature-iphoneos.xcarchive" \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild archive \
-scheme MyFeature \
-destination "generic/platform=iOS Simulator" \
-archivePath "build/MyFeature-iphonesimulator.xcarchive" \
SKIP_INSTALL=NO \
BUILD_LIBRARY_FOR_DISTRIBUTION=YES

xcodebuild -create-xcframework \
-framework "build/MyFeature-iphoneos.xcarchive/Products/Library/Frameworks/MyFeature.framework" \
-framework "build/MyFeature-iphonesimulator.xcarchive/Products/Library/Frameworks/MyFeature.framework" \
-output "build/MyFeature.xcframework"
```

If I set `BUILD_LIBRARY_FOR_DISTRIBUTION` to `NO`, the script runs successfully, but I need the `xcarchive` for distribution.

# Error

```
** ARCHIVE FAILED **

The following build commands failed:
	SwiftVerifyEmittedModuleInterface normal arm64 Verifying\ emitted\ module\ interface\ DatadogCore.swiftinterface /Users/MyMachine/Library/Developer/Xcode/DerivedData/App-epxixvymmcxxolddrqihwyguzsmi/Build/Intermediates.noindex/ArchiveIntermediates/MyFeature/IntermediateBuildFilesPath/Datadog.build/Release-iphoneos/MyFeature.build/Objects-normal/arm64/DatadogCore.swiftinterface (in target 'DatadogCore' from project 'Datadog')
(1 failure)
```

# Questions

- Any idea how can I solve this issue?

**Comment by ncreated** [comment]
Hey @victormendes5 👋,

Could you clarify the actual reason why the `SwiftVerifyEmittedModuleInterface` is failing? The information you provided outlines the command that failed, but we need more insight into the specific issue with the emitted `DatadogCore.swiftinterface`.

If your package includes a binary target, it might be impacted by this SPM limitation:
- https://github.com/swiftlang/swift-package-manager/issues/4449

Also, you might want to check this related issue: 
- https://github.com/DataDog/dd-sdk-ios/issues/1402

**Comment by ncreated** [comment]
Closing as potential duplicate: https://github.com/DataDog/dd-sdk-ios/issues/1402 blocked by https://github.com/swiftlang/swift-package-manager/issues/4449
