### ISSUE TITLE
How to correctly implement custom RUM view tracking?

### ISSUE THREAD

**Issue by russellporter** [DataDog/dd-sdk-ios#2133]
### Question

As we migrate more of our app to SwiftUI, the automatic UIKit view tracking is becoming less effective for understanding the usage of our app. What I would like to do is instead use the RumMonitor APIs to start and stop views manually, and disable the automatic view tracking. The app I'm working on already has view tracking for analytics purposes (separate from datadog) so it's easy to pass those events to Datadog.

This mostly works, however I noticed if any event (tap, api call, etc) occurs between a "stop view" and the following "start view", the events appear to be lost. It seems like a bug?

A couple workarounds I found so far:
- track a fake "between" screen view that captures any events in between stop/start view of real screen
- keep the automatic uikit tracking on (although I'm not sure this 100% solves it)

Both options introduce quite a bit of noise in the session and I was hoping for something better. I think it's more important that the session timeline is complete vs having all events perfectly associated with a screen. Thanks!

**Comment by ncreated** [comment]
Hi @russellporter 👋 

Thank you for reaching out! Here are a few thoughts on your question:
- Have you looked into our SwiftUI view instrumentation APIs? You can find more details [here](https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/setup/ios/?tab=swiftpackagemanagerspm#instrument-views). These APIs are designed to work alongside UIKit auto-instrumentation, which might help with your migration process.
- It’s expected that events occurring between a "stop view" and the subsequent "start view" will be dropped, as there is no active view during this period.
- One potential workaround is to use only the "start view" API and skip the "stop view" API. This way, one view will replace the previous one seamlessly, with no gap between them. This behavior aligns with the SDK’s intended flow, where stopping the previous view is automatically triggered by the start of a new one.

Let me know if you need any further clarification or assistance!

**Comment by russellporter** [comment]
All clear. Thank you very much for the prompt reply!
