### ISSUE TITLE
Compilation fails with Datadog SDK 1.3.0 using Cocoapods and Xcode 11.3.1

### ISSUE THREAD

**Issue by provTheodoreNewell** [DataDog/dd-sdk-ios#214]
### The issue

Compilation fails with 5 issues in a new Xcode 11.3.1 project with DataDog SDK 1.3.0:

1. `Value of type 'FileHandle' has no member 'seekToEnd'` in File.swift line 62
2. `Extraneous argument label 'contentsOf:' in call` in File.swift line 63
  1. Compiler-suggested fix: `Replace 'contentsOf: ' with ''`
3. `Value of type 'FileHandle' has no member 'readToEnd'` in File.swift line 94
4. `Ambiguous reference to member 'swizzle(using:)'` in URLSessionSwizzler.swift line 68
5. `Ambiguous reference to member 'swizzle(using:)'` in URLSessionSwizzler.swift line 109

---

**Comment by buranmert** [comment]
hey @provTheodoreNewell 👋 thanks for reporting the issue!
we made a fix and are planning to ship it as a hotfix
i'll keep you posted once this is done

### The issue
we use some `FileHandle` methods which are only available in iOS 13.4+ and Xcode 11.3.1 has an inferior base SDK version
as a fix, we wrap this code with `#if compiler(>=5.2) ... #else ... #endif`; `compiler(5.2)` means Xcode 11.4 whose base SDK is iOS 13.4
in your case, Xcode 11.3.1, compiler shouldn't see those new methods and should compile the `#else` scope

**Comment by provTheodoreNewell** [comment]
Thank you!

**Comment by buranmert** [comment]
hi @provTheodoreNewell 👋 
`1.3.1` hotfix version is shipped to fix the issue 🚀 

please let me know if the issue persists, otherwise feel free to close the issue

**Comment by provTheodoreNewell** [comment]
Resolved: `1.3.1` compiles with Xcode 11.3.1 🥳
