### ISSUE TITLE
Not working for macCatalyst and tvOS

### ISSUE THREAD

**Issue by Hengyu** [DataDog/dd-sdk-ios#274]
### The issue

The latest package won't get compiled when the project target is set to `macCatalyst` or `tvOS`.

### Detail

Since the `CoreTelephony` has not been supported for `macCatalyst` and `tvOS`. (Even the official documentation says the `CoreTelephony` can be used in `macCatalyst 13.0+`) So the compiler would generate complaints when build for mac and tv.

I know this SDK is targeted for iOS, however, after the release of macCatalyst, the same project could also be compiled to mac app. I tried to constrain the platforms to iOS only in project build settings. But the compiler is still building the Datadog module when targeting mac. Looks like this is a bug between Swift Package Manager & Xcode.

<img width="566" alt="screenshot" src="https://user-images.githubusercontent.com/4032674/95649232-11718780-0b0f-11eb-9c38-aa15532fe844.png">

### Proposed solution

Add macro in files who are using `CoreTelephony`

https://github.com/Hengyu/dd-sdk-ios/commit/c51a24fa9d2ef626b5b7e1be07a1a4c68e287034

---

#### Datadog SDK version:

`1.3.1`

#### Last working Datadog SDK version:

N.A.

#### Dependency Manager:

Swift Package Manager

#### Other toolset:

N.A.

#### Xcode version:

`Xcode 12.0 (12A7209)`

#### Swift version:

`Swift 5.1`

#### Deployment Target:

`macCatalyst 13.0+` & `tvOS 11.0+`

#### macOS version:

`macOS Catalina 10.15.7 (19H2)`

**Comment by Hengyu** [comment]
Or we can change the package type from `.dynamic` to default in Swift Package Manger.

E.g., 
```
.library(
            name: "Datadog",
            targets: ["Datadog"]),
```

By doing this, the Datadog package is embedded in the project main target as a static library. And we can choose to only embed it when the build target is iOS. The Xcode compiler itself won't compile it when the target is Mac.

<img width="320" alt="1" src="https://user-images.githubusercontent.com/4032674/95773670-84d2ef00-0cf1-11eb-89d0-a790fff48860.png">

**Comment by Hengyu** [comment]
The pros and cons between the first and second solutions:

#### 1st solution (add macros)

Pros: Make the Datadog can also be used in `macCatalyst` and `tvOS`

Cons: Code is not clean

#### 2nd solution (change type to static)

Pros: Minimal changes, clean code

Cons: From the git blame, you guys are setting the type to `.dynamic` intentionally. Changing the type back to `.static` maybe is not you expected.

**Comment by Hengyu** [comment]
Hi @buranmert , 

Thanks for so quick respond! Currently I just what to "cheat" the compiler for not generating complains. Your pull request looks great!

Can't wait to try `master`. And could you please update the git tag correspondingly once its in master, so the SPM would pull it. Appreciated!

**Comment by buranmert** [comment]
hey @Hengyu 👋 

we push new tags with new releases and we are not planning a hotfix release for this issue.
unfortunately i can't give you an estimation for the next stable release (sorry about that!)

you can keep an eye on the new releases by watching our repo in Github

until then, you can use `master` for a while (beware, it won't be stable releases!)
or maybe you can tag your own fork if you need to cache the package.

please let me know if any of them works for you 👂 
and if so, feel free to close the issue

**Comment by Hengyu** [comment]
Hello @buranmert ,

Let'm wait for the release, thanks!
