### ISSUE TITLE
Unable to send exception via Logs

### ISSUE THREAD

**Issue by sdejesusF** [DataDog/dd-sdk-ios#276]
### The thing

I'm integrating Datadog SDK for Logs in both Android and iOS and I came with an issue that for android I'm able to do
Log.E(msg, throwable) but I don't see any overload method to add neither an NSError nor Error.

Is there a way to achieve send an exception? I tried to add the attribute "error.message" or "error.stack" but those are reserved.

**Comment by buranmert** [comment]
hi @sdejesusF 👋 
thanks for reporting the issue
this is at the top of our backlog now, i'll keep here posted hopefully soon

**Comment by sdejesusF** [comment]
hi @buranmert, thank you 🙏

**Comment by sdejesusF** [comment]
🤘
