### ISSUE TITLE
Support tvOS

### ISSUE THREAD

**Issue by hlung** [DataDog/dd-sdk-ios#293]
Our app supports both iOS and tvOS. Is it possible to add support for tvOS?

**Comment by ncreated** [comment]
Hello @hlung 👋. Thanks for reaching us 🙂. The answer on `tvOS` support is similar to `watchOS` https://github.com/DataDog/dd-sdk-ios/issues/125. Our plan is to first complete all major features: [Logging](https://docs.datadoghq.com/logs/), [Tracing](https://docs.datadoghq.com/tracing/) and [Real User Monitoring](https://docs.datadoghq.com/real_user_monitoring/installation/?tab=us) and then evaluate supporting more platforms (including `tvOS` and `watchOS`). It's definitely on our list, but no precise ETA yet.

**Comment by triztian** [comment]
@ncreated I'd also support adding this, we're migrating to DD and we have a tvOS app and would like to keep logs centralized. 

Is there an alternative or a raw HTTP endpoint that can be used as a fallback in the meantime?

**Comment by priyanshi-gupta** [comment]
Hey @triztian 👋  I'm the PM for Mobile RUM team. We don't yet support an HTTP endpoint to send your data directly to - we'll keep this thread posted with updates on support for tvOS and API endpoint, both of which are in radar for Q2 - 2021.

**Comment by mschinis** [comment]
Hi @priyanshi-gupta any updates on the above? I'm very eager to add datadog to our tvOS app as well.

**Comment by triztian** [comment]
@mschinis What I ended up doing was using JustLog (which is available for tvOS) and creating a bare minimum backend destination.

  * https://github.com/AirspaceTechnologies/JustLogDataDogDestination

It is a somewhat butchered integration but it allowed us to start logging along with the other applications that were migrated to DD.

**Comment by ScottPierce** [comment]
This is a much needed feature. Also - supporting tvOS should be very easy. It's basically iOS with a separate compiler target.

**Comment by ncreated** [comment]
As a follow up here, we're now [actively working](https://github.com/DataDog/dd-sdk-ios/pulls?q=is%3Apr+tvOS) on adding `tvOS` support 🙂.
