### ISSUE TITLE
Unable to use "-" character in env

### ISSUE THREAD

**Issue by sdejesusF** [DataDog/dd-sdk-ios#319]
### The thing

Currently, our backend services and android use "-" character (for example "t-prod") as part of the env name but the iOS library is giving me an error saying: "Datadog SDK usage error: `environment` contains illegal characters (only alphanumerics and `_` are allowed)".

Any reason why on iOS this is different?

**Comment by buranmert** [comment]
hi again @sdejesusF 👋 
this issue is fixed in https://github.com/DataDog/dd-sdk-ios/pull/246 and released in [1.4.0-beta1](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.4.0-beta1)

please let me know if that helps

**Comment by sdejesusF** [comment]
Hi @buranmert, 

yes, that helps, thank you 🙏

Will close this issue then
