### ISSUE TITLE
Objective-C interop for RUM functionality

### ISSUE THREAD

**Issue by brunck** [DataDog/dd-sdk-ios#332]
RUM functionality is in beta, but it's only accessible using the Swift code. The Objective-C interop framework doesn't have anything relating to RUM in it.
I don't know if this is on the roadmap, but it would be great to have this added to the DatadogObjC framework, or otherwise have the Swift RUM code exposed to Objective-C.

**Comment by ncreated** [comment]
Hello @brunck 👋. Thanks for reaching us! Objective-C support is something we will be looking into shortly after releasing RUM. In the same way we've proceed with Logging and Tracing features (Swift first, then Objective-C through `DatadogObjc.framework`) 🙂.

**Comment by brunck** [comment]
Great, thank you @ncreated! :)
