### ISSUE TITLE
Rename Global to GlobalRum or DatadogGlobal?

### ISSUE THREAD

**Issue by henningms** [DataDog/dd-sdk-ios#333]
### The thing

Hi there,

Is it possible to rename the Global struct to something else, like GlobalRum like in the Android library or DatadogGlobal etc. Global is apparently a common name and thus raises conflicts 😅

**Comment by ncreated** [comment]
Hello @henningms 👋. This is indeed a good idea 🙂. However, we will more likely provide a convenience `DDGlobal` typealias as we do for `Logger`:
https://github.com/DataDog/dd-sdk-ios/blob/dab40304caaa393201b968d8611db600ae49c690/Sources/Datadog/Logger.swift#L26-L39

I'll put this on our roadmap, stay tuned 📻.

**Comment by ncreated** [comment]
`DDGlobal` is available in [1.4.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.4.0).
