### ISSUE TITLE
RUM implementation in SwiftUI

### ISSUE THREAD

**Issue by AXR-Tech** [DataDog/dd-sdk-ios#339]
### RUM implementation in SwiftUI

I have gone through the documentation doesn't mention anything regarding SwiftUI, natively. Is there a way to implement RUM in a native SwiftUI and not UIViewControllerRepresentable?

**Comment by ncreated** [comment]
Hey @Alexander-techIOS ! Thanks for reaching out 🙂. We plan to support SwiftUI in the future, but I can't give any estimates. Please contact our support so we can track your interest in having SwiftUI compatibility for the iOS RUM SDK 💪.

**Comment by amkomatz-ggd** [comment]
+1

**Comment by saj11** [comment]
Hi!
I don't sure if it is the same issue but I am trying to integrate Datadog into a SwiftUI app. I understand that Datadog do not support SwiftUI, in terms of RUM, so it won't track the views or actions. But RUM also includes a mode in which it can tracks the request, but it seems to do not work also.

So I want to know if any feature inside Datadog will work on a SwiftUI app

**Comment by ncreated** [comment]
Hello @saj11. Our [manual instrumentation API](https://docs.datadoghq.com/real_user_monitoring/ios/?tab=cocoapods#manual-instrumentation) offers a UI framework-agnostic variant which will work with `SwiftUI` as well. When using `SwiftUI`, you can leverage those two APIs to start and stop the RUM View:
```swift
Global.rum.startView(key:)
Global.rum.stopView(key:)
```
Network requests (auto)instrumentation will only work if there's a RUM View started, so please make sure that you call `Global.rum.startView(key:)` from your `SwiftUI's` view before the request is sent.

**Comment by hs-echkayben** [comment]
Hello @ncreated according to the manual instrumentation API you shared, Global.rum.startView(viewController: self) is the way to collect RUM resources. So what I don't understand how would that translate in the absence of a UIViewController in the case of swiftUI, the documentation is not clear when it comes to that. Thank you

**Comment by ncreated** [comment]
Hello @hs-echkayben 👋. In case of view controller absence, you can use following APIs on `RUMMonitor`:
https://github.com/DataDog/dd-sdk-ios/blob/b19956ce0262bf13c77d62b3436a395c88c698c5/Sources/Datadog/DDRUMMonitor.swift#L51-L69


With that, you can start and stop the view by giving `String` key to match its ending with the beginning. In case of SwiftUI, I think this should work fine:
```swift
struct ContentView: View {
    private let viewKey = "content-view" // must be unique
    private let rumViewName = "ContentView"

    var body: some View {
        // ...
        .onAppear {
           Global.rum.startView(key: viewKey, name: rumViewName)
        }
        .onDisappear {
           Global.rum.stopView(key: viewKey)
        }
    }
}
```

**Comment by maxep** [comment]
`SwiftUI` Instrumentation APIs have been added in [1.9.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.9.0). Our documentation still need to be updated but here some snippets on how to use it:

- View Instrumentation:
```swift
import SwiftUI
import Datadog

struct FooView: View {

    var body: some View {
        FooContent {
            ...
        }
        .trackRUMView(name: "Foo")
    }
}
```

- Tap Action Instrumentation:
```swift
import SwiftUI
import Datadog

struct BarView: View {

    var body: some View {
        Button("BarButton") { {
            ...
        }
        .trackRUMTapAction(name: "Bar")
    }
}
```

It has been designed to work seamlessly with `UIKit` auto-instrumentation for hybrid `UIKit+SwiftUI` applications.
I will close this issue, but feel free to add any comment/feedback.

**Comment by ferologics** [comment]
@maxep thanks for the update, this is very helpful! I'm currently integrating I'm curious how does the `trackRUMView(name:)` method behave in case `onDisappear()` of the view is not called?

**Comment by maxep** [comment]
Hey @ferologics! Thanks for using it :)

We keep a stack of appeared view to consistently log start and stop view events, the last item of the stack is the visible one, any items below it have appeared but `onDisappear` has not been called. Therefore, they are considered not visible but can be revealed if the last item disappears.

So if we have the following sequence, characteristically of a modal navigation:
1. View A `onAppear`
2. View B `onAppear`
3. View B `onDisappear`

The following events will be logged:
1. Start View A
2. Stop View A
3. Start View B
4. Stop View B
5. Start View A

**Comment by maxep** [comment]
Hi @payal10gupta,

You mean apps fully written using SwiftUI? Yes it will, on iOS and tvOS platforms.

**Comment by payal10gupta** [comment]
Hey @maxep ,

Thanks for responding.

So far I am able to report the crashes and upload the dSYMs on the portal. There are a few issues that I am facing,

1. When symbolicating the crashes, it not showing the exact file/class names.
2. I am trying the Mobile Session Replay feature of Datadog. The recoded sessions does not show anything. Just a SwiftUI label on the entire screen

Here is how I'm initializing the datadog,

```
Datadog.initialize(
    with: Datadog.Configuration(
        clientToken: clientToken,
        env: environment,
        service: serviceName
    ),
    trackingConsent: .granted
)

RUM.enable(
    with: RUM.Configuration(
        applicationID: appID,
        uiKitViewsPredicate: DefaultUIKitRUMViewsPredicate(),
        uiKitActionsPredicate: DefaultUIKitRUMActionsPredicate()
    )
)

CrashReporting.enable()
```

And using the below code to track the SwiftUI views,

`.trackRUMView(name: viewName)
`

Am I missing something here?

**Comment by maxep** [comment]
Hi @payal10gupta,

This GH issue is about SwiftUI support in RUM.
In regards to Crash Reporting, I invite you to contact our [support](https://www.datadoghq.com/support/), you will be able to share more privately about your configuration and they can assist you with symbolication.

Session Replay does not yet support SwiftUI, it is on our roadmap so stay tuned!
