### ISSUE TITLE
Crash Reporting support

### ISSUE THREAD

**Issue by hs-kdhillon** [DataDog/dd-sdk-ios#362]
Calling ` trackUIKitRUMViews()` tracks the views and the actions except the errors, i.e. app crashes.  Are the crashes supported by `1.4.0`?

**Comment by ncreated** [comment]
Thanks for reaching us @hs-kdhillon 👋. This is a question on Crash Reporting support. It is not yet there for Datadog iOS SDK `1.4.0`, but it's on our roadmap and we're going to add it shortly. I can't give any precise ETA, but it's coming so pleases stay tuned 🙂.

**Comment by hs-kdhillon** [comment]
Sounds good. Thanks for replying! Closing the issue now.

**Comment by 8secz-johndpope** [comment]
please post update here when supported.

**Comment by ignotusverum** [comment]
Hi @ncreated, want to follow up on expected timeline for adding crash reporting

**Comment by ncreated** [comment]
Hello @ignotusverum 👋. The initial implementation was done, but we are still stabilising and improving it for the first beta release. Unfortunately, I can't give precise ETA right now.

**Comment by danishin** [comment]
@ncreated Thanks for the update! Our team is relying on datadog for all crash reportings so this feature would be super helpful! :)
