### ISSUE TITLE
Datadog use in ios (notification) extension

### ISSUE THREAD

**Issue by SimpleApp** [DataDog/dd-sdk-ios#370]
### The issue

I'm trying to use datadog in both the app bundle and the notification extension bundle. I've tried two and encountered two different errors: 
1/ using spm. I had to manually embed the Datadog library for the notification extension code to compile. That worked just fine, however, doing that triggered a bug when submitting to apple : 
- ERROR ITMS-90685: "CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'Datadog' under the iOS application
- ERROR ITMS-90205: "Invalid Bundle. The bundle at … /Plugins/NotificationServiceExt.appex' contains disallowed nested bundles.
- ERROR ITMS-90206: "Invalid Bundle. The bundle at '…/PlugIns/NotificationServiceExt.appex' contains disallowed file 'Frameworks'."

So, i tried using Cocoapods, and wrote  "pod 'DatadogSDK' " in both the app and the extension targets. 
This doesn't compile, because of a "UIApplication.shared" dependency in RUMDebugging.swift : 
- 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.
At this point i feel kind of stuck.. Did i miss something ?

---

#### Datadog SDK version:

1.4.0
#### Last working Datadog SDK version:

?
#### Dependency Manager:
CocoaPods & SwiftPM

#### Xcode version:

12.2

#### Swift version:

5.x

#### Deployment Target:
ios 13.0

**Comment by ncreated** [comment]
Hello @SimpleApp 👋. Thanks for reporting this issue. Indeed, there was a problem with `UIApplication.shared` API when compiling the SDK for use in some app extensions (in this case, Notifications Service Extension). This is solved in #375 and will be available soon as `1.4.1` hotfix 🙂👌.

> 1/ using spm. I had to manually embed the Datadog library for the notification extension code to compile.

What was the reason of embedding `Datadog` in extension's target? It should work fine with _"Do Not Embed"_ setting. I managed to build a simple example using Share Extension and link `Datadog` through SPM. It compiles and sends logs with no issue  (tested on iOS Simulator, Xcode 12.3):

<img width="1300" alt="Screenshot 2021-01-18 at 17 43 30" src="https://user-images.githubusercontent.com/2358722/104943058-7d3c7980-59b5-11eb-8a87-93ded3c4d831.png">

**Comment by ncreated** [comment]
The fix is available in [`1.4.1`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.4.1). I'm closing the issue for now 👌, but feel free to open it or ask more questions. Thank you again for finding this bug!

**Comment by SimpleApp** [comment]
Hi, for some reason, selecting "do not embed" makes the library disappear from the list and not link at all.

**Comment by SimpleApp** [comment]
I found this https://forums.swift.org/t/is-this-an-xcode-bug-or-somehow-related-to-spm/33987 which is probably what happens here

**Comment by ncreated** [comment]
Hello @SimpleApp 👋. Thank you for digging into more details on the SPM 💪. We need to look closer into app extensions + SPM configuration with recent Xcode tooling - I put this topic high in our backlog, and we will investigate it soon. For now, linking through CocoaPods seems to be a good workaround - I hope it solves the problem for you 🙂.

**Comment by amardeepranu** [comment]
When using cocoapods, I can't build in the extension because you're using UIApplication.shared:

/ios/Pods/DatadogSDK/Sources/Datadog/RUM/Debugging/RUMDebugging.swift:99:44: 'shared' is unavailable in application extensions for iOS: Use view controller based solutions where appropriate instead.

**Comment by ncreated** [comment]
@amardeepranu this is fixed in [`1.4.1`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.4.1).

**Comment by buranmert** [comment]
ℹ️ we've recently found a new workaround for Swift Package Manager and lack of `Do not embed` option, please have a look at [this comment](https://github.com/DataDog/dd-sdk-ios/pull/405#issuecomment-775985543)
