### ISSUE TITLE
Add Carthage support

### ISSUE THREAD

**Issue by 00FA9A** [DataDog/dd-sdk-ios#39]
**Is your feature request related to a problem? Please describe:**
We are planning on using this SDK going forward to support logging via Datadog. However, at the moment, we won't be able to add that support via SPM. Additionally, we do not use Cocoapods as dependency manager anymore.

**Describe the solution you'd like:**
We would like to add Carthage support.

**Describe alternatives you've considered:**
SPM was considered but due to internal structure of out project, we are unable to do so at this time.

**Additional context:**
n/a

**Comment by ncreated** [comment]
Hey @00FA9A 👋, thanks for the feedback. Indeed, Carthage support is what many people do ask for. It's very high on our list, so please stay tuned - this should be added very soon 🙂.

**Comment by 00FA9A** [comment]
> Hey @00FA9A 👋, thanks for the feedback. Indeed, Carthage support is what many people do ask for. It's very high on our list, so please stay tuned - this should be added very soon 🙂.

thanks @ncreated! if it could help, we could get a pr for this kickstarted. not very urgent for us though, we will use our fork in the interim

**Comment by ncreated** [comment]
Carthage support added in #50
