### ISSUE TITLE
Missing RUM objects for objective-c

### ISSUE THREAD

**Issue by sdejesusF** [DataDog/dd-sdk-ios#414]
We use Xamarin.iOS for our app therefore, we need to use DatadogSDKObjc to generate bindings, and when we were trying to integrate now Datadog RUM we noticed that there are no objects exposed for datadog RUM. Not sure if objc C headers in this release (1.4.1) for RUM are missing or there is no plan to add them as there are for Trace and Logging

**Comment by ncreated** [comment]
Hello @sdejesusF 👋 , thanks for reaching us. RUM for Objc is not part of `1.4.1`, but it will be shipped in `1.5.0` 🙂. It is available right now in [`1.5.0-beta1`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.5.0-beta1) so you can try it out until we release `1.5.0`.

**Comment by sdejesusF** [comment]
Hi @ncreated thank you for the quick response.

Will give it a try, do you have any estimate on when that version will be released?

**Comment by ncreated** [comment]
No precise ETA, but I can say that we're doing last stabilisation work and dogfooding. Should be available pretty soon 🙂.

**Comment by sdejesusF** [comment]
Hi Again @ncreated  👋 ,  I've already created the bindings for Xamarin.iOS and now I'm able to access RUM objects (using 1.5.0-beta1), but it's not automatically tracking views. Not sure if it's something with my bindings or do you do think it could be related to your PR #419?

**Comment by ncreated** [comment]
Hey @sdejesusF 👋. If you're using `trackUIKitRUMViews()` (and other auto-instrumentation RUM APIs) then missing RUM events is definitely linked to #419. As this bug description says - RUM views are not properly tracked in obj-c runtime, which will lead to all other events not being linked to (missing) views.

Until we merge it and the version is available, you can fallback to either [providing your own implementation of the `UIKitRUMViewsPredicate`](https://docs.datadoghq.com/real_user_monitoring/ios/?tab=cocoapods#auto-instrumentation) or using manual API of `Global.rum.startView()` / `.stopView()`.
