### ISSUE TITLE
Feature request: Apollo / GraphQL support

### ISSUE THREAD

**Issue by rmelick-vida** [DataDog/dd-sdk-ios#416]
### Add support for ApolloClient

Similar to the support for AlamoFire (as mentioned in https://github.com/DataDog/dd-sdk-ios/issues/357) can you add support for [ApolloClient](https://www.apollographql.com/docs/ios/).

My suspicion is that working with the NetworkTransport would be pretty similar to what was done to support AlamoFire https://www.apollographql.com/docs/ios/initialization/#advanced-client-creation

**Comment by ncreated** [comment]
Hello @rmelick-vida 👋 . Thanks for opening this issue. Apollo Graph QL support is on our existing roadmap and we will start working on in very shortly. Cannot give precise ETA, but please stay tuned 🙂.

Indeed, we are considering adding the support by using Apollo's transport / interception concepts. Thanks for the clue 👌.

**Comment by kristiant** [comment]
Is there any update on this? We are looking at integrating Datadog for our app and are using ApolloClient as well.

**Comment by AlexandreCrettet** [comment]
Hello @ncreated. I've integrated the Datadog traces with apollo. However I wonder if it is possible to retrieve the created spans directly in the Apollo's `URLSessionClient`? I need to set a tag to these spans but I was not able to find how to do it. Thanks!

**Comment by gmoraleda** [comment]
In case someone is facing this as of 2023:
- Sampling rate for tracing defaults to 100...but not for first-party hosts. The default for first-party hosts is 20.
- If you define first-party hosts, you need to set the sampling rate there as well:
```
        Trace.enable(
            with: Trace.Configuration(
                urlSessionTracking: .init(
                    firstPartyHostsTracing: .trace(hosts: ["host1.com", "host2.com"], sampleRate: 100)
                ),
                networkInfoEnabled: true
            )
        )
```

that fixed our standalone spans 🙌

**Comment by loganblevins** [comment]
@gmoraleda Is this approach used instead of the session delegate subclass?

**Comment by loganblevins** [comment]
@ncreated Thanks I will give this a shot. I ran into this issue today.

**Comment by loganblevins** [comment]
Looks like `__URLSessionDelegateProviding` is deprecated .. what's the best way that is non-deprecated to handle this now? @ncreated

**Comment by ganeshnj** [comment]
hi @loganblevins, we have made some changes including support for async-await APIs in the URLSession instrumentation and now it is based on customer delegate type (no need to implement any protocol).

I have not tested it personally but below setup should work ideally

```swift
import Apollo
import DatadogTrace
import DatadogCore

Datadog.initialize(
   with: Datadog.Configuration(
       clientToken: clientToken,
       env: environment,
       site: .us1,
       uploadFrequency: .frequent
   ),
   trackingConsent: .granted
)

Trace.enable(
    with: .init(
        urlSessionTracking: .init(firstPartyHostsTracing: .trace(hosts: ["example.com"], sampleRate: 100))
    )
)
URLSessionInstrumentation.enable(
    with: .init(
        delegateClass: URLSessionClient.self
    )
)
let client = URLSessionClient()


```

**Comment by ruiz7** [comment]
@ganeshnj it worked! thank you.

**Comment by loganblevins** [comment]
@ganeshnj I will try soon thank you

**Comment by ganeshnj** [comment]
That's great @ruiz7, I will close this issue. 

Feel free to open a new one if you have any other questions or issues.

**Comment by ganeshnj** [comment]
In case someone looking for AlamoFire version of it, I tested it and it works as expected as well.

```swift
import Alamofire
import DatadogTrace
import DatadogCore

Datadog.initialize(
   with: Datadog.Configuration(
       clientToken: clientToken,
       env: environment,
       site: .us1,
       uploadFrequency: .frequent
   ),
   trackingConsent: .granted
)

Trace.enable(
    with: .init(
        urlSessionTracking: .init(firstPartyHostsTracing: .trace(hosts: ["example.com"], sampleRate: 100))
    )
)
URLSessionInstrumentation.enable(
    with: .init(
        delegateClass: SessionDelegate.self
    )
)

let rootQueue = DispatchQueue(label: "com.datadoghq.dd-sdk-ios")
let queue = OperationQueue()
queue.underlyingQueue = rootQueue
let delegate = SessionDelegate()
let urlSession = URLSession(configuration: .default, delegate: delegate, delegateQueue: queue)
let session = Session(session: urlSession, delegate: delegate, rootQueue: rootQueue)
```

**Comment by loganblevins** [comment]
> hi @loganblevins, we have made some changes including support for async-await APIs in the URLSession instrumentation and now it is based on customer delegate type (no need to implement any protocol).
> 
> I have not tested it personally but below setup should work ideally
> 
> ```swift
> import Apollo
> import DatadogTrace
> import DatadogCore
> 
> Datadog.initialize(
>    with: Datadog.Configuration(
>        clientToken: clientToken,
>        env: environment,
>        site: .us1,
>        uploadFrequency: .frequent
>    ),
>    trackingConsent: .granted
> )
> 
> Trace.enable(
>     with: .init(
>         urlSessionTracking: .init(firstPartyHostsTracing: .trace(hosts: ["example.com"], sampleRate: 100))
>     )
> )
> URLSessionInstrumentation.enable(
>     with: .init(
>         delegateClass: URLSessionClient.self
>     )
> )
> let client = URLSessionClient()
> ```

Will this simultaneously monitor networking from Apollo AND the native URLSession client?

**Comment by ganeshnj** [comment]
Only the native URLSession client, our instrumentation depends on swizzling URLSession types hence if a library uses URLSession underneath - like in this.

**Comment by dineshiOSDev** [comment]
Hi 
Any update for Apollo client support. 
The traces are not getting logged tried with above alternative as well.

Currently doing a individual trace with span on network manager

**Comment by gsbernstein** [comment]
New way of doing it is `URLSessionInstrumentation.enable(with: .init(delegateClass: Apollo.URLSessionClient.self))`
https://docs.datadoghq.com/real_user_monitoring/mobile_and_tv_monitoring/integrated_libraries/ios/
