### ISSUE TITLE
Feature request: Global Logging

### ISSUE THREAD

**Issue by rmelick-vida** [DataDog/dd-sdk-ios#417]
### Global Logging

We're able to set up a global rum in the `DDGlobal` object
```
DDGlobal.rum = RUMMonitor.initialize()
```

How about also having space for a logger there?  That would make it easier to initialize our datadog sdk in the appropriate AppDelegate / code that runs only during app launches, but still access the logger from wherever we needed to.

So then we could do something like
```
DDGlobal.logger = Logger.builder
    .sendNetworkInfo(true)
    .build()
```

**Comment by maxep** [comment]
Hey 👋  This won't be relevant with the up coming version `2.0` of the SDK. The `Global` instances and other singletons will be removed.
