### ISSUE TITLE
APM: Trace propagation HTTP headers not available to Objective-C via DDHTTPHeadersWriter

### ISSUE THREAD

**Issue by ben-yolabs** [DataDog/dd-sdk-ios#420]
### SDK

`DatadogSDKObjc`, `1.5.0-beta1`

### Issue

As per [iOS Trace Collection](https://github.com/DataDog/dd-sdk-ios/blob/master/docs/trace_collection.md), users of the SDK may want to manually propagate traces, rather than relying on interceptors provided by the SDK.

Trace propagation HTTP headers are not accessible via `DDHTTPHeadersWriter`, the Objective-C variant/facade class to `HTTPHeadersWriter`.

A `DDHTTPHeadersWriter`'s underlying `HTTPHeadersWriter.tracePropagationHTTPHeaders` should be accessible through a public property exposed to Objective-C.

**Comment by ncreated** [comment]
Thank you @ben-yolabs 🙌!
