### ISSUE TITLE
[Question] How to correctly identify users in RUM Sessions

### ISSUE THREAD

**Issue by rmelick-vida** [DataDog/dd-sdk-ios#426]
The javascript docs are pretty clear about the correct way to set the user context, by calling the [setUser](https://docs.datadoghq.com/real_user_monitoring/browser/advanced_configuration/?tab=npm#identify-user-sessions) function. What's the correct way to do this using the ios sdk?

**Comment by buranmert** [comment]
hi @rmelick-vida 👋 
thanks for reporting the issue: i took a note on our docs missing this information

you can use [`Datadog.setUserInfo(...)` method](https://github.com/DataDog/dd-sdk-ios/blob/master/Sources/Datadog/Datadog.swift#L112), here is an example usage:
```swift
Datadog.setUserInfo(
  id: "some_id", 
  name: "John Doe", 
  email: "john@doe.com", 
  extraInfo: ["extra_key": "extra_value"]
)
```
please note that this sets the active user for all features (logging, tracing, RUM)
let me know if that works for you

**Comment by buranmert** [comment]
hi again @rmelick-vida 
i'm closing the issue due to inactivity for now.
feel free to re-open if the solution above doesn't work for you.
