### ISSUE TITLE
Safe to use in production?

### ISSUE THREAD

**Issue by lmramirez** [DataDog/dd-sdk-ios#43]
More of a question than an issue:

My team uses Datadog for all of our services, and I am looking to use it for iOS as well instead of needing to find another logging app. I realize this is still in Alpha, but is this project in a place where it is safe/ready to be used in a production app? 

Thanks!

**Comment by ncreated** [comment]
Hey @lmramirez, thanks for looking at this project. We're actively dogfooding this SDK with our internal project and it seems 100% stable (1 app / 30K logs in last month / 0 crashes). If you have a beta distribution channel or use phased release, this should be fine. We are fully focused on this project and I'd be happy to help with any issues or questions 🙂.

In terms of development, right now I can only think of one breaking change that will be source compatible (network info attributes will be disabled by default).

**Comment by lmramirez** [comment]
Thanks for the information @ncreated, will test it out.

**Comment by ncreated** [comment]
I'm closing this issue as we [just released `1.0.0`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.0.0) 🚀.
