### ISSUE TITLE
[Question] Manually tracing resources

### ISSUE THREAD

**Issue by sdejesusF** [DataDog/dd-sdk-ios#438]
Hi 👋 , 

We are using Xamarin.iOS and we don't have direct access to NSURLSession therefore, we have to manually intercept requests and add them as resources using StartResource and StopResource (or WithError). My question would be if it's possible to add in between the start and stop other timings like for example TTFB, or any other custom time that would be digested as timings for that resource.

**Comment by ncreated** [comment]
Hello @sdejesusF 👋, thanks for reaching us. Resource timings (TTFB, SSL, connection etc.) can be collected by using:
```swift
Global.rum.addResourceMetrics(resourceKey:metrics:)
```
This methods accepts `URLSessionTaskMetrics` for the `metrics` parameter. This method should be called after resource is started (`startResource()`) and between it gets completed (`stopResource()` or with error). Datadog SDK will do the job of computing timing metrics for you.

We don't yet support Xamarin.iOS, so I'm not sure if you'll be able to capture `URLSessionTaskMetrics` from [`URLSessionTaskDelegate`](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/1643148-urlsession). You may want to contact our support and raise the feature request for Xamarin support, which will help us prioritising our next supported platforms.

**Comment by sdejesusF** [comment]
Hi  👋  @ncreated, 

Yes, sadly we don't have access to URLSessionTaskMetrics :( so for now we will continue to manually track the resources without having TTFB.

And sorry to bother you again with another related topic to this question. On dd-android, we are able to pass the size of the request on the StopResource method. But I don't see that possibility on iOS. Can we use something else to add the size of the resource or is not possible?

**Comment by sdejesusF** [comment]
btw, just realize that its in here https://github.com/DataDog/dd-sdk-ios/blob/c2b4e6445f87f3c908782881ef253352e0bbc248/Sources/Datadog/DDRUMMonitor.swift#L173 but its not exposed to objective c

**Comment by ncreated** [comment]
Hey @sdejesusF 👋. Thanks for spotting this! We will expose this API to Objc shortly and this should be available in the next release.

**Comment by sdejesusF** [comment]
thank you @ncreated 🙏

**Comment by ncreated** [comment]
Available in [`1.5.2`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.5.2) 👌
