### ISSUE TITLE
Tracking network requests using `firstPartyHosts ` and `DDURLSessionDelegate`

### ISSUE THREAD

**Issue by rajatgupta-bigstep** [DataDog/dd-sdk-ios#455]
Hi I am currently using the Cocoapods to install the Datadog SDK Version 1.5.0 but I am having issues with not able to track the network logs. These are the following steps i used:

        ` Datadog.initialize(
            appContext: .init(),
            trackingConsent: .granted,
            configuration: Datadog.Configuration
                .builderUsing(
                    rumApplicationID: "*******************************",
                    clientToken: "*******************************",
                    environment: "preprod"
                )
                .trackURLSession(firstPartyHosts: ["host.com"])
                .set(serviceName: "****")
                .enableTracing(true)
                .build()
        )
        
        // Register Tracer
        Global.sharedTracer = Tracer.initialize(
            configuration: Tracer.Configuration(
                sendNetworkInfo: true
            )
        )

        Global.rum = RUMMonitor.initialize()
        Datadog.verbosityLevel = .debug
        Datadog.debugRUM = true`
                
        let session = URLSession(configuration: .default, delegate: DDURLSessionDelegate(), delegateQueue: nil)
 
 Just to updates these token are working fine to track rumviews. Please let me know the next step

**Comment by ncreated** [comment]
Hello @rajatgupta-bigstep 👋. The instrumentation snippet looks good 👍, so all should work as expected. We need some more information:
* What do you mean by _"network logs"_ - is it APM spans or do you expect something else to happen? 
* Could you confirm that you're able to see RUM Resources attached to RUM Views?
* Do you send request to the `host.com` domain, or it's just a placeholder in your snippet 🙂?

**Comment by rajatgupta-bigstep** [comment]
Hi @ncreated : Please check the reply below:
1. I mean the api call using in iOS project
2. Yes I want to track RUM Resources attached to RUM Views. For example: If there are any api calls in particular screen we are able to track that.
3. `host.com` is just a example to show the snippet of code, basically we are using our actual domain to send the request.

**Comment by ncreated** [comment]
Thank you for all details @rajatgupta-bigstep. As your goal is to track RUM Resources, you must also enable tracking RUM Views, so the SDK can attach resources to views. To do that, you have to enable automatic view tracking when initializing the SDK:
```swift
.trackUIKitRUMViews() // ← enables automatic `UIViewController` tracking
.trackURLSession(firstPartyHosts: ["host.com"])
```

Alternatively, you can use [manual instrumentation](https://docs.datadoghq.com/real_user_monitoring/ios/?tab=cocoapods#manual-instrumentation) and track RUM Views manually with `.startView(viewController:)` and `.stopView(viewController:)`. In any case, the view must be started before the resource begins, so we can attach it correctly.

Let me know if you find this helpful and if I can help more 🙂

**Comment by rajatgupta-bigstep** [comment]
Hi @ncreated : Still I am not able to see any items in resource, I can see the views This is my updated code:?

        Datadog.initialize(
            appContext: .init(),
            trackingConsent: .granted,
            configuration: Datadog.Configuration
                .builderUsing(
                    rumApplicationID: "******************************",
                    clientToken: "******************************",
                    environment: "preprod"
                )
                .set(serviceName: "RiseLiving")
                .trackUIKitRUMViews()
                .enableTracing(true)
                .enableRUM(true)
                .enableLogging(true)
                .trackURLSession(firstPartyHosts: ["host.com"])
                .build()
        )
         
        // Register Tracer
        Global.sharedTracer = Tracer.initialize(
            configuration: Tracer.Configuration(
                sendNetworkInfo: true
            )
        )

        Global.rum = RUMMonitor.initialize()
        Datadog.verbosityLevel = .debug
        Datadog.debugRUM = true
        
       Session code is in separate class:
        let session =   URLSession(configuration: .default, delegate: DDURLSessionDelegate(), delegateQueue: nil)
            let task = session.dataTask(with: request) { data, response, error in
        }
        
        I observed one thing that it is calling this method in DDURLSessionDelegate class:
        open func urlSession(_ session: URLSession, task: URLSessionTask, didFinishCollecting metrics: URLSessionTaskMetrics) {
        interceptor?.taskMetricsCollected(task: task, metrics: metrics)
    }

**Comment by rajatgupta-bigstep** [comment]
Hi @ncreated : I am able to get the resources now but it is working only for the first time. To make next time work I need to delete the app and reinstall it. Is it the expected behaviour or we need to set some settings?

**Comment by ncreated** [comment]
This should work all the time. Right after the SDK is initialized, all requests sent through the instance of `URLSession` insturmented with `DDURLSessionDelegate` should be tracked.

With `1.5.0`, when using this configuration in `AppDelegate`:
```swift
// In AppDelegate.swift:

var session: URLSession!

Datadog.initialize(
    appContext: .init(),
    trackingConsent: .granted,
    configuration: Datadog.Configuration
        .builderUsing(
            rumApplicationID: "<rum-app-id>",
            clientToken: "<client-token>",
            environment: "tests"
        )
        .trackUIKitRUMViews()
        .trackURLSession(firstPartyHosts: ["datadoghq.com"])
        .set(serviceName: "ios-sdk-example-app")
        .build()
)

Global.rum = RUMMonitor.initialize()

session = URLSession(configuration: .default, delegate: DDURLSessionDelegate(), delegateQueue: nil)
```

and sending repetitive requests from `ViewController`:
```swift
// The ViewController.swift

class ViewController: UIViewController {
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)

        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.repeatRequest()
        }
    }

    func repeatRequest() {
        let task = session.dataTask(with: URL(string: "https://docs.datadoghq.com")!)
        task.resume()

        DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.repeatRequest()
        }
    }
}
```
they all get delivered to the RUM Explorer:

<img width="808" alt="Screenshot 2021-04-01 at 11 11 34" src="https://user-images.githubusercontent.com/2358722/113271644-0a1b8180-92db-11eb-97e8-f4236d142551.png">

**Comment by rajatgupta-bigstep** [comment]
@ncreated : Its working fine now but i am not able to see the request and response of api request

**Comment by ncreated** [comment]
@rajatgupta-bigstep request body and response details tracking is not supported at this moment, but this is something that we will be working on very shortly.

Great that that it works for you now 👌. I changed the title of this issue and tagged it accordingly - feel free to close it or let me know if you have more questions.

**Comment by rajatgupta-bigstep** [comment]
Ok @ncreated , Can we add email id as a filter in RUM Explorer. I am not able to find it

**Comment by ncreated** [comment]
@rajatgupta-bigstep Happy it works for you 💪. For RUM Explorer and Datadog website related questions, please refer to the online documentation (especially [Facets search](https://docs.datadoghq.com/real_user_monitoring/explorer/search/#facets-search) and [Setup facets and measures](https://docs.datadoghq.com/real_user_monitoring/explorer/?tab=facets#setup-facets-and-measures) sections for querying data by iPhone name/model/version) or [reach our support](https://docs.datadoghq.com/help/) directly.
