### ISSUE TITLE
`Datadog.debugRUM` utility view

### ISSUE THREAD

**Issue by saj11** [DataDog/dd-sdk-ios#472]
###Hi!

I am using Datadog last version with SwiftUI. In another issue (#339), you told us that we are able to use the RUM just if we use the manual methods (startView(key: String), stopView(key: String)).

Also, you give us a way in which we could be able to used:

```swift
struct ContentView: View {
    private let viewKey = "music-list" // must be unique
    private let rumViewName = "MusicListView"

    var body: some View {
        // ...
        .onAppear {
           Global.rum.startView(key: viewKey, name: rumViewName)
           Global.rum.addError(message: "Datadog is not sending data.")
        }
        .onDisappear {
           Global.rum.stopView(key: viewKey)
        }
    }
}
```

But when I try this approach in the View it appears a strange label at the bottom.

![Screen Shot 2021-04-19 at 12 17 13](https://user-images.githubusercontent.com/17533996/115283951-4f2c1a00-a109-11eb-9f4e-7519a97972f0.png)

**Comment by ncreated** [comment]
Hello @saj11 👋. This outline view comes from the `Datadog.debugRUM = true` that you must have enabled in your Datadog SDK initialization code. To make it disappear, just remove that line.

This however proves that your instrumentation works fine for `SwiftUI`. This label shows you the name of the current view that our SDK is capturing. I'd recommend to keep it there until you instrument the entire app and just remove it when you're done 🙂.

Let me know if it's clear and if it works for you 👌.
