### ISSUE TITLE
if user denies tracking - does that mean we can't enable  datadog?

### ISSUE THREAD

**Issue by 8secz-johndpope** [DataDog/dd-sdk-ios#501]

**Comment by xgouchet** [comment]
Hi @8secz-johndpope , 

It all depend on the legal requirements in your country / the country of your users. We ain't lawyers, so please check with yours to see the legal requirements you need to follow, but according to GDPR (European law) and other Data privacy laws across the world, if the user denies the application the right to track them, then Datadog should not be enabled. 

We offer a nice way to handle this, by having you give a TrackingConsent information when initializing the SDK (by default you should use `PENDING`). This will allow the SDK to start collecting information without sending them to our servers yet. Once you know what the user consent is (from a UI you implement or from your own servers) you can then update the consent to either `GRANTED` (then the collected data for this session — past and future — will be sent), or `NOT_GRANTED` (then previous data collected for this session will be dropped and tracking will be stopped).

**Comment by 8secz-johndpope** [comment]
i suspect the opt in rates going forward are going to be low across the board for tracking.
because I need to know things going wrong with the devices - it almost warrants me sending logs back to my own server -  "User signed failed to sign-in  successfully"
If users are hiding this - by not opting in - I still a solution to get visibility on what's happening.
consider enhancing product by offering some kind of crippled down version on premise / logger as a fall back. Maybe it's incompatible - but the rates of usage are likely to dwindle with apple enforcing this.

**Comment by dbezrukov** [comment]
Hi there! We're using DataDog for tracking infrastructure and web/mobile apps. 
And we want to be sure that logging mobile app's errors does not require any permissions from the user. 
Is it possible to configure the DataDog client so that the user's personal information, like ip address, is excluded and not being sent to the server? Thanks.

**Comment by maxep** [comment]
Hi @dbezrukov,

Thank you for using our products :)

For GDPR compliance, user consent is required for collecting any user data. Thereby, we have a single `trackingConsent` setting where:
- `.pending`: The RUM iOS SDK starts collecting and batching the data but does not send it to Datadog. The RUM iOS SDK waits for the new tracking consent value to decide what to do with the batched data.
- `.granted`: The RUM iOS SDK starts collecting the data and sends it to Datadog.
- `.notGranted`: The RUM iOS SDK does not collect any data. No logs, traces, or RUM events are sent to Datadog.

c.f. https://docs.datadoghq.com/real_user_monitoring/ios/advanced_configuration/?tab=swift#set-tracking-consent-gdpr-compliance
