### ISSUE TITLE
Can not use DDURLSessionDelegate any alternative?

### ISSUE THREAD

**Issue by ericyu423** [DataDog/dd-sdk-ios#503]
Documentation says to use 
URLSession(..., delegate: DDURLSessionDelegate(), ...)
however URLSession currently is using another delegate so it can not be assigned to DDURLSessionDelegate()

example in our App

URLSession(configuration: sessionConfig, delegate: URLSessionCustomDelegate(), delegateQueue: nil)
class URLSessionCustomDelegate: URLSessionDelegate{}

I am guessing I can use these functions in place of DDURLSessionDelegate
with 

 DDGlobal.rum.startResourceLoading
 DDGlobal.rum.stopResourceLoading
in one of those URLSessionDelegate functions

but not exactly sure which function and parameter I should put in.

**Comment by fedejordan** [comment]
Hey @ericyu423 were you managed to solve the issue? My project is facing the same, we're using other `URLSessionDelegate` and cannot have just the DD one.

**Comment by ncreated** [comment]
Hello @fedejordan 👋. I hope this doc will help [Using `DDURLSessionDelegate` with your own session delegate](https://docs.datadoghq.com/real_user_monitoring/ios/troubleshooting/#using-ddurlsessiondelegate-with-your-own-session-delegate) 🙂.
