### ISSUE TITLE
GRPC support?

### ISSUE THREAD

**Issue by pendolf** [DataDog/dd-sdk-ios#515]
Is any future planning for grpc (https://github.com/grpc/grpc-swift) support?

**Comment by buranmert** [comment]
hi @pendolf 👋 
we don't plan to support gRPC at least in the short-term.

[according to this gRPC tutorial](https://github.com/grpc/grpc-swift/blob/main/docs/interceptors-tutorial.md), it should be possible to listen to all your RPC streams by subclassing `ClientInterceptor` in your project.
then you can use manual instrumentation API of Datadog SDK within your `ClientInterceptor`.
here is a piece of pseudo-code to give a rough idea:
```swift
class LoggingEchoClientInterceptor: ClientInterceptor<Echo_EchoRequest, Echo_EchoResponse> {
  ...
  override func send(
    _ part: GRPCClientRequestPart<Echo_EchoRequest>,
    promise: EventLoopPromise<Void>?,
    context: ClientInterceptorContext<Echo_EchoRequest, Echo_EchoResponse>
  ) {
    switch part {
    ...
    case let .message(request, _):
      datadogLogger.log("> Sending request with text '\(request.text)'")
      self.span = datadogTracer.startSpan(operationName: "RPC stream") // self.span.finish() later when needed
      datadogRUM.startResourceLoading(resourceKey: "\(request.key)") // datadogRUM.stopResourceLoading() later when needed
    ...
    }
  }
}
```

please let me know if that helps

**Comment by pendolf** [comment]
@buranmert Thank you for clear example :beers:

**Comment by buranmert** [comment]
hey @pendolf, i'm closing the issue as there seems to be not much left to do
feel free to reopen the issue if needed and please let us know how your gRPC integration went and what could be improved, etc.
