### ISSUE TITLE
[Feature Request] Get session ID

### ISSUE THREAD

**Issue by fedejordan** [DataDog/dd-sdk-ios#526]
### [Feature Request] Get session ID 

Hi guys, I would like to know if there is a easy way to get the session ID. 

I wanted it to become available so we can associate it with other trackers, or became available in screen when debugging/testing the app.

Currently I'm doing something like this
```
Datadog.Configuration.builderUsing(...)
.setRUMViewEventMapper { viewEvent in
  let currentSessionID = viewEvent.session.id
  guard sessionID != currentSessionID else { return viewEvent }
  sessionID = currentSessionID
  return viewEvent
}
.build()
```

Thanks in advance!

**Comment by ncreated** [comment]
Hello @fedejordan 👋 , thanks for reaching us. We've discussed this in the team and it sounds like a good idea. We've put this in our backlog and this will be available soon. I can't give any precise ETA, but stay tuned 🙂.

**Comment by samitaha2** [comment]
I'd love this feature as well - we have an internal bug reporter we use and connecting it to the session id would be extremely helpful. Right now we have to write to our own log file and maintain it so it is available to send with a bug report. Exposing this property would reduce a lot of complexity for us
