### ISSUE TITLE
User info logged under "usr"

### ISSUE THREAD

**Issue by qasim** [DataDog/dd-sdk-ios#54]
Hi there 🙂

Is it intentional that user info is being logged under `usr` vs. `user`?

https://github.com/DataDog/dd-sdk-ios/blob/92883fd417a710e6c764897a106e7b0ae005f780/Sources/Datadog/Logs/Log/LogEncoder.swift#L60-L64

P.S. we've began using the SDK in our project and can't wait to see the integration grow.

**Comment by buranmert** [comment]
Hi 👋 

`usr` is [the convention at Datadog](https://docs.datadoghq.com/logs/processing/attributes_naming_convention/#user-related-attributes)

> User related attributes
> All attributes and measures are prefixed by usr.

Does that answer your question, @qasim?

P.S: Thanks! 🙌

**Comment by qasim** [comment]
Yes! Thanks for the reference.
