### ISSUE TITLE
[Question] Safety of usage in non-initialized state

### ISSUE THREAD

**Issue by kurtzheng** [DataDog/dd-sdk-ios#546]
We have an A/B test to rollout Datadog mobile RUM functionalities for a small portion of users as a trial, so `Datadog` and `RUMMonitor` are only initialized in some particular cases (based on our client settings of A/B test).

In order to switch the usages of Datadog (e.g to set `DDURLSessionDelegate` or not, add client  interceptors using `rum.start(stop)ResourceLoading` to grpc client or not), I tried to find API like `Datadog.isInitialized()`, `Datadog.isRUMMonitorInitialized()`, `Datadog.isURLSessionAutoInstrumentationInitialized()`, but I found the APIs don't exist and the related instances (e.g. `Datadog.instance`) and classes are internal, so I cannot check the initialization status of Datadog and some features (`DDRUMMonitor`, `URLSessionAutoInstrumentation`).

I also confirmed that current release (1.6.0) is safe to be used in the case Datadog and/or interested features are not initialized, but I didn't find any document to mention the default dummy implementation is the design or approach of dd-ios-sdk for the non-initialized cases, so some of us worry about the future release of dd-ios-sdk will use different approach.

So we have an extension as workaround which depends on the implementation details of dd-ios-sdk heavily:
```swift
public extension Datadog {
    static func isRUMMonitorInitialized() -> Bool {
        Global.rum is RUMMonitor
    }
    
    static func isURLSessionAutoInstrumentationInitialized() -> Bool {
        URLSessionInterceptor.shared != nil
    }
}
```

Q:
* Is dd-ios-sdk is safe to be used even when Datadog  and/or some features are not initialized?
* Is the dummy implementation is the design or approach of dd-ios-sdk for the cases when Datadog and/or some features are not initialized?
* Will it also be safe for the future releases?

**Comment by buranmert** [comment]
hi @kurtzheng 👋 

first, thanks for raising your issue with all the details 🙏 

yes, it is and will be safe to use Datadog SDK without initializing it.
i'd suggest keep using Datadog SDK in the same way regardless it is initialized or not.
your extension will _probably_ work as well, yet i don't think it's needed.

in case SDK is not initialized, `Global.tracer/rum` are no-op types by default. they receive method calls safely and do **nothing**. other SDK components, such as `URLSessionInterceptor.shared`, are `nil` so it's still safe to call them.

please let me know if you have other questions

**Comment by kurtzheng** [comment]
@buranmert Thanks for the explanation!
