### ISSUE TITLE
TraceId and SpanId information

### ISSUE THREAD

**Issue by sdejesusF** [DataDog/dd-sdk-ios#577]
Ive recently integrated a workflow using the android sdk and we are able to access traceId and spanId from the SpanContext but Im trying to access it using the objc-c lib and I dont see any property for that. Is there any way to access it that Im not seeing? Even for swift I dont see it.

**Comment by ncreated** [comment]
Hello @sdejesusF 👋, thanks for reaching us 🙂. Which exact Android SDK API do you refer to? And what is your use case for accessing `traceID` and `spanID` informations? 

Our existing tracer follows the [OpenTracing specification](https://opentracing.io/specification/), and exposing these attributes is not an explicit part of the spec:
> Most OpenTracing users only interact with `SpanContext` via references when starting new Spans, or when injecting/extracting a trace to/from some transport protocol.

so I'm wondering what's your precise use case for reading these values.

**Comment by sdejesusF** [comment]
Hi @ncreated thanks for the quick response.

In the android lib we access them from the spancontext of [OT](https://github.com/opentracing/opentracing-java/blob/master/opentracing-api/src/main/java/io/opentracing/SpanContext.java).

Regarding the use case, we are using Xamarin and we are not able to use automatically resources tracing we track them manually and in order to have end to end tracing we have to add RUM headers manually.

If there is any other way to hava this result without accessing traceid and spanid please, let me know.

**Comment by ncreated** [comment]
I see, thanks for more context 👍. Well, if your goal is to inject tracing headers into request, [OT comes with span context injection API](https://github.com/opentracing/specification/blob/master/specification.md#inject-a-spancontext-into-a-carrier) and we implement it. In Obj-c it looks this (in `1.6.0`):
```objc
DDGlobal.sharedTracer = [[DDTracer alloc] initWithConfiguration:[DDTracerConfiguration new]];

NSMutableURLRequest *request = [[NSMutableURLRequest alloc] initWithURL:[NSURL URLWithString:@"http://example.com"]];

id<OTSpan> span = [DDGlobal.sharedTracer startSpan:@"ios.request"];

// 1. Obtain `HTTPHeadersWriter`:
DDHTTPHeadersWriter *writer = [DDHTTPHeadersWriter new];

// 2. Inject span context into `writer`:
[DDGlobal.sharedTracer inject:span.context format:OT.formatTextMap carrier:writer error:nil];

// 3. Now, tracing headers are available in `writer.tracePropagationHTTPHeaders` dictionary and
// need to be set on the instrumented request:
for(id field in writer.tracePropagationHTTPHeaders) {
    NSString *headerField = field;
    NSString *headerValue = [writer.tracePropagationHTTPHeaders valueForKey:field];
    [request setValue:headerValue forHTTPHeaderField:headerField];
}
```
```
(lldb) po request.allHTTPHeaderFields
{
    "x-datadog-parent-id" = 5437575769530574608;
    "x-datadog-trace-id" = 5481960129821776164;
}
```
However, this only adds APM headers (`x-datadog-parent-id` and `x-datadog-trace-id `) which are subset of RUM headers [that you reference from our doc](https://docs.datadoghq.com/real_user_monitoring/connect_rum_and_traces/?tab=browserrum#how-are-rum-resources-linked-to-traces). In our next release `x-datadog-sampling-priority` and `x-datadog-sampled` will be added there as a fix (https://github.com/DataDog/dd-sdk-ios/pull/575) to a known issue.

Same API is also available in Android SDK through [`Injector` class](https://github.com/DataDog/dd-sdk-android/blob/34933826d3b36988dee8e9fa8a76b829b4a70314/dd-sdk-android/src/main/java/com/datadog/opentracing/propagation/DatadogHttpCodec.java#L38), although just reading these values is way simpler through their `context.toTraceId()` and `.toSpanId()` methods, I agree.

Let me know if it's possible for you to use `DDHTTPHeadersWriter` for injecting `x-datadog-parent-id` and `x-datadog-trace-id` headers and make up 3 others by hand. If it's not possible / too difficult in Xamarin, we could think of providing similar API to Android SDK.

**Comment by sdejesusF** [comment]
@ncreated  thanks for the detailed explanation. 

We are still on 1.5.2, will generate new bindings for 1.6.0 and give it a try and let you know how that goes.

**Comment by sdejesusF** [comment]
Hi @ncreated,

I think that solution will work, I did test and got the traceid and spanid but havent been able to fully test, got some issues while creating the bindings for c#.

Im not getting exposed to obj-c the init method for DDRumView and I notice that the obj annotation was removed from 1.5.2 to 1.6.0 [here](https://github.com/DataDog/dd-sdk-ios/blob/1.6.0/Sources/DatadogObjc/RUMMonitor+objc.swift#L37) 

The header file is like this:

`SWIFT_CLASS("_TtC11DatadogObjc9DDRUMView")
@interface DDRUMView : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull name;
@property (nonatomic, readonly, copy) NSDictionary<NSString *, id> * _Nonnull attributes;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end`

any reason why the obj annotation was removed? Im going to build locally with the annotation to see if the init gets exposed.

**Comment by sdejesusF** [comment]
After adding obj annotation and building the bindings are working and Im able to use the spanId and traceId 😄  thank you!

Not related with this but, now on version 1.6.0 when creating a DDRumView with a custom name (previously called path) I start to seeing the name of the controller instead of the custom name :( This happened as well on android when I updated to 1.9.0.

**Comment by priyanshi-gupta** [comment]
Hey @sdejesusF, I'm the product manager for Mobile RUM at Datadog, I'd like to hear about your usage of iOS SDK with Xamarin so we can work to improve our SDK offerings. If interested could you send me an email on priyanshi.gupta@datadoghq.com?

**Comment by ncreated** [comment]
> After adding obj annotation and building the bindings are working and Im able to use the spanId and traceId 😄 thank you!

@sdejesusF thanks a lot for spotting this issue. I managed to fix it in https://github.com/DataDog/dd-sdk-ios/pull/583 and it should be available in next release.

> Not related with this but, now on version 1.6.0 when creating a DDRumView with a custom name (previously called path) I start to seeing the name of the controller instead of the custom name :( This happened as well on android when I updated to 1.9.0.

I think you're still watching the "VIEW PATH GROUP" information, instead of "VIEW NAME" which we introduced with `1.6.0`:
<img width="553" alt="Screenshot 2021-09-01 at 16 54 52" src="https://user-images.githubusercontent.com/2358722/131694289-1aab7391-3f79-4ec7-801d-178e4e79fb05.png">

Consider "VIEW PATH GROUP" as canonical representation of the view (its view controller class name) and "VIEW NAME" as the enhancement to this concept (it's either the view controller name or your custom name if provided).

**Comment by sdejesusF** [comment]
@ncreated thanks!

Understood, Just I quick question then, for example in the session view I see view path group instead of the view name:

<img width="985" alt="Screen Shot 2021-09-01 at 21 25 02" src="https://user-images.githubusercontent.com/10758298/131740023-2ac4bf50-e1c8-40ad-8050-de8053197dc7.png">

I know in some parts we can change the fields that we want to see but do you know if this is possible in this view? 
For us android & iOS have the same screens that is why we prefer to have usage metrics based on the view name which is the same for both platforms.

**Comment by ncreated** [comment]
@sdejesusF 👋 regarding this - we don't control it on the SDK side, it's the way our web UI works. But I get your point - seems valid to me 👌. Could you reach one of our [support channels](https://docs.datadoghq.com/help/) to report this? This will help us triage the feedback, send it to the right people and you'll be able to track the status 🙂.
