### ISSUE TITLE
error: no type or protocol named '__URLSessionDelegateProviding' compiling DatadogObjc-Swift.h

### ISSUE THREAD

**Issue by ivan-hernandez-scopely** [DataDog/dd-sdk-ios#638]
### The issue

when trying to compile when importing 

```
#import <DatadogObjc/DatadogObjc-Swift.h>

DatadogSDKObjc/DatadogObjc.framework/Headers/DatadogObjc-Swift.h:403:47: error: no type or protocol named '__URLSessionDelegateProviding'
@interface DDNSURLSessionDelegate : NSObject <__URLSessionDelegateProviding, NSURLSessionDataDelegate>
```

I can see it is defined in https://github.com/DataDog/dd-sdk-ios/blob/master/api-surface-swift#L741
but not in https://github.com/DataDog/dd-sdk-ios/blob/master/api-surface-objc

---

#### Datadog SDK version:

1.7.1

#### Last working Datadog SDK version:

Unknown

#### Dependency Manager:

Cocoapods

#### Other toolset:

xxx

#### Xcode version:

Xcode 12.5

#### Swift version:

xxx

#### Deployment Target:

xxx

#### macOS version:

macOS Big Sur 11.6

**Comment by buranmert** [comment]
hi @ivan-hernandez-scopely 👋 

can you please try to import `Datadog` as a module both in Swift and Obj-C?
```
// swift
import Datadog

// Objc
@import Datadog;
@import DatadogObjc;
```

once you import `Datadog` then the compiler should be able to see `__URLSessionDelegateProviding` type.
we had a similar issue [here](https://github.com/DataDog/dd-sdk-ios/issues/128#issuecomment-642104433) and it was solved by importing the module.

please let me know if the issue doesn't disappear.
