### ISSUE TITLE
Allow preset values to be configured

### ISSUE THREAD

**Issue by scott-the-programmer** [DataDog/dd-sdk-ios#639]
### Allow preset values to be configured

Modifying preset values such as `maxDirectorySize` and `maxFileAgeForRead` would be useful for clients to be able to tailor to their specific use case. 

Personally, I think the cleanest way might be to allow leverage `set(additionalConfiguration)` introduced by https://github.com/DataDog/dd-sdk-ios/pull/456 and propagate that down to `PerformancePreset`

```swift
Datadog.Configuration
       .set(additionalConfiguration: ["performance": ["maxDirectorySize": 512 * 1_024 * 1_024]])
```

Keen to know everyone else's thoughts!

**Comment by scott-the-programmer** [comment]
The main reason would be to provide an absolute limit on the logs accumulated before `trackingConsent` is acknowledged. From the looks of it, this could be covered by setting `maxDirectorySize`.

In the absolute worst case, while trackingConsent is pending, verbose logging could store up to 512mb of logs that could potentially be shipped to datadog in a relatively short period of time.

**Comment by buranmert** [comment]
i'm hoping the concern is addressed and closing the issue.
feel free to reopen if needed.
