### ISSUE TITLE
`try?` causes Swift Error breakpoint to break on launch

### ISSUE THREAD

**Issue by iliaskarim** [DataDog/dd-sdk-ios#653]
### The thing

E.g. in https://github.com/DataDog/dd-sdk-ios/blob/master/Sources/Datadog/Core/Persistence/Files/Directory.swift

```swift
try? FileManager.default.removeItem(at: temporaryDirectory.url)
```
causes Xcode to break for "Swift Error."

This can prolong a debugging session when relying on a Swift Error breakpoint.

Here's an alternative that would address the issue at hand.
```swift
do {
  try FileManager.default.removeItem(at: temporaryDirectory.url)
} catch {
  // no-op
}
```

**Comment by buranmert** [comment]
hi @iliaskarim 👋 

thanks for reporting the issue.
i was able to reproduce it: `try? FileManager.default.removeItem(at: temporaryDirectory.url)` always throws 3 times at app launch. i made a fix above ☝️ 
other `throw` statements don't need fix as they don't always throw and are useful to catch errors, so i left them unchanged.
