### ISSUE TITLE
Apply iOS 15 crash fix to 1.8.0 branch?

### ISSUE THREAD

**Issue by computerjazz** [DataDog/dd-sdk-ios#660]
### The thing
Hello!
I am in the process of integrating the DataDog react native package, which includes DataDogSDKBridge 0.5.0 as a dependency (https://github.com/DataDog/dd-sdk-reactnative/blob/main/packages/core/DatadogSDKReactNative.podspec#L20), which in turn relies on DataDog iOS SDK `1.8.0-beta.1` (https://github.com/DataDog/dd-bridge-ios/blob/main/DatadogSDKBridge.podspec#L20).

1.7.2 included a fix for an iOS 15 crash (https://github.com/DataDog/dd-sdk-ios/commit/5db35abd541709baed38c798819e2c51d3eb7066). We are hesitant about shipping code that could potentially crash. Any chance of getting the fix into the 1.8.x branch that ships with the react native package? Thanks!

**Comment by ncreated** [comment]
Hello @computerjazz 👋. Sorry for delayed response, we've been qualifying our `1.8.0` stable release. It should be available early next week and it will be followed by an update to our RN SDK. That release will ship our recent fixes, including the iOS 15 crash you mention.

**Comment by ncreated** [comment]
[1.8.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.8.0) was just released 👍. We will follow up with a corresponding release of RN SDK in next week(s).
