### ISSUE TITLE
Datadog session details and logs are not reflecting on downloading build from testflight

### ISSUE THREAD

**Issue by sagar-nikam688** [DataDog/dd-sdk-ios#678]
### Datadog session details and logs are not reflecting on downloading build from testflight

Hey Team,

We have integrated datadog in our iOS app, and it was working as expected but suddenly it stopped when we tested by downloading build from testflight. We have cross checked this by testing on simulator it is working as expected.

Please help us to resolve this issue, Thanks in advance.!

**Comment by sagar-nikam688** [comment]
Hey team,
Our latest on this is this issue is also on we are installing an app on the device in debug mode. This was tried and tested on 3 separate iPhone devices.

**Comment by buranmert** [comment]
hi @sagar-nikam688 👋 

can you please set `Datadog.verbosityLevel = .debug` right after `Datadog.initialize(...)` while debugging?
then you should be able to see messages in the Debugger Console (bottom right in Xcode)

**Comment by sagar-nikam688** [comment]
Hi @buranmert,

Thanks for the solution, logs we got in the Xcode console state that the phone was in Low power mode. After disabling the mode stats get reflected. Do we have any solution that the app can send logs in low power mode? Will the app will log Outstanding logs when the device disables low power mode?

**Comment by buranmert** [comment]
yes: once low power mode is disabled then the pending logs will be uploaded to Datadog 👍

**Comment by sagar-nikam688** [comment]
Thanks @buranmert
