### ISSUE TITLE
is Datadog using Apache Log4j software vulnerability

### ISSUE THREAD

**Issue by Sagar9821** [DataDog/dd-sdk-ios#689]
### The issue

📝 We have just one query is datadog using Log4j software vulnerability ?

---

#### Datadog SDK version:

1.7.2

#### Last working Datadog SDK version:

1.7.2

#### Dependency Manager:

 Cocoapods 

#### Xcode version:

Xcode. 13.1

#### Swift version:

5.1

#### Deployment Target:

12

#### macOS version:

11.15.2

**Comment by ncreated** [comment]
Hello @Sagar9821 👋. Datadog iOS SDK is not impacted by this vulnerability in any way. Please check [Datadog Response to the Log4j Vulnerability](https://www.datadoghq.com/log4j-vulnerability/) for details regarding other components.
