### ISSUE TITLE
Missing required module '_Datadog_Private'

### ISSUE THREAD

**Issue by wwu-wish** [DataDog/dd-sdk-ios#698]
### The issue
I followed your document and added the following line to our package file: .package(url: "https://github.com/Datadog/dd-sdk-ios.git", .upToNextMajor(from: "1.8.0")) , but I'm getting the error: Missing required module '_Datadog_Private' 

Can someone please take a look or point us to the latest documentation? We are not using carthage. But there might be some weirdness with our project dependencies. We have the package file under another package called WishCore 

---

#### Datadog SDK version:
1.8.0

#### Last working Datadog SDK version:
NA

#### Dependency Manager:
SPM

#### Xcode version:
12.5.1

#### Swift version:
5

#### Deployment Target:
iPhone

#### macOS version:
Bigsur 11.2

**Comment by sjmadsen** [comment]
@wwu-wish, you closed this issue the same day you opened it. Did you solve your problem? I'm seeing something similar with unit test builds in an app that depends on a package that in turn depends on the DataDog SDK.
