### ISSUE TITLE
Binaries with Swift version 5.5.2

### ISSUE THREAD

**Issue by satish-ik** [DataDog/dd-sdk-ios#717]
### The thing

We are trying to update to Xcode 13.2.1 and seems like the latest binaries are not compiled with 5.5.2. 
When can we expect this? :)

**Comment by ncreated** [comment]
Hello @satish-ik 👋, thanks for opening the issue. Indeed, `Datadog-1.8.0.zip` in [`1.8.0` release](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.8.0) was originally compiled with Xcode 13.1. We just recompiled it using Xcode 13.2.x and Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30). 

Let me know if this works for you 👌.

In general, our XCFrameworks should be compatible between different Xcode versions, however there is an open bug in Swift compiler [SR-14195](https://bugs.swift.org/browse/SR-14195) that prevents us from providing module stability. Solving this problem may require significant API changes and we will work on this in the next major version of the SDK (`2.x`).

**Comment by satish-ik** [comment]
Thanks @ncreated, this resolved our issue
