### ISSUE TITLE
Crash Log not showing in iOS

### ISSUE THREAD

**Issue by rajatgupta9021** [DataDog/dd-sdk-ios#771]
Hi, I am taking reference to this case but not able to see the crash in datadog. Just to add here, I am able to see the session in Datadog properly with RUM Monitoring. DSYM work is also done and I can see the success in my Azure Pipeline.

https://github.com/DataDog/dd-sdk-ios/issues/634

I am using these versions for Datadog and firebase and am not able to see the crash in Datadog. I am attaching my contents from podfile.lock. Also, I wrote the crash code in viewDidAppear function. Can you help here?

DataDog Version:

DatadogSDK (1.9.0)

DatadogSDKAlamofireExtension (1.9.0):

Alamofire (~> 5.0)
DatadogSDK (= 1.9.0)
DatadogSDKCrashReporting (1.9.0):

DatadogSDK (= 1.9.0)
PLCrashReporter (~> 1.10.1)
Firebase versions

Firebase/Analytics (6.34.0):
Firebase/Core
Firebase/Core (6.34.0):

Firebase/CoreOnly
FirebaseAnalytics (= 6.9.0)
Firebase/CoreOnly (6.34.0):

FirebaseCore (= 6.10.4)
Firebase/Crashlytics (6.34.0):

Firebase/CoreOnly
FirebaseCrashlytics (~> 4.6.2)
Firebase/Messaging (6.34.0):

Firebase/CoreOnly
FirebaseMessaging (~> 4.7.1)
Firebase/MLVision (6.34.0):

Firebase/CoreOnly
FirebaseMLVision (~> 0.21.0)
Firebase/MLVisionTextModel (6.34.0):

Firebase/CoreOnly
FirebaseMLVisionTextModel (~> 0.21.0)
Firebase/Performance (6.34.0):

Firebase/CoreOnly
FirebasePerformance (~> 3.3.1)
FirebaseABTesting (4.2.0):

FirebaseCore (~> 6.10)
FirebaseAnalytics (6.9.0):

FirebaseCore (~> 6.10)
FirebaseInstallations (~> 1.7)
GoogleAppMeasurement (= 6.9.0)
GoogleUtilities/AppDelegateSwizzler (~> 6.7)
GoogleUtilities/MethodSwizzler (~> 6.7)
GoogleUtilities/Network (~> 6.7)
"GoogleUtilities/NSData+zlib (~> 6.7)"
nanopb (~> 1.30906.0)
FirebaseCore (6.10.4):

FirebaseCoreDiagnostics (~> 1.6)
GoogleUtilities/Environment (~> 6.7)
GoogleUtilities/Logger (~> 6.7)
FirebaseCoreDiagnostics (1.7.0):

GoogleDataTransport (~> 7.4)
GoogleUtilities/Environment (~> 6.7)
GoogleUtilities/Logger (~> 6.7)
nanopb (~> 1.30906.0)
FirebaseCrashlytics (4.6.2):

FirebaseCore (~> 6.10)
FirebaseInstallations (~> 1.6)
GoogleDataTransport (~> 7.2)
nanopb (~> 1.30906.0)
PromisesObjC (~> 1.2)
FirebaseInstallations (1.7.0):

FirebaseCore (~> 6.10)
GoogleUtilities/Environment (~> 6.7)
GoogleUtilities/UserDefaults (~> 6.7)
PromisesObjC (~> 1.2)
FirebaseInstanceID (4.8.0):

FirebaseCore (~> 6.10)
FirebaseInstallations (~> 1.6)
GoogleUtilities/Environment (~> 6.7)
GoogleUtilities/UserDefaults (~> 6.7)
FirebaseMessaging (4.7.1):

FirebaseCore (~> 6.10)
FirebaseInstanceID (~> 4.7)
GoogleUtilities/AppDelegateSwizzler (~> 6.7)
GoogleUtilities/Environment (~> 6.7)
GoogleUtilities/Reachability (~> 6.7)
GoogleUtilities/UserDefaults (~> 6.7)
Protobuf (>= 3.9.2, ~> 3.9)
FirebaseMLCommon (0.21.0):

FirebaseCore (~> 6.9)
FirebaseInstallations (~> 1.5)
GoogleToolboxForMac/Logger (~> 2.1)
"GoogleToolboxForMac/NSData+zlib (~> 2.1)"
"GoogleToolboxForMac/NSDictionary+URLArguments (~> 2.1)"
GoogleUtilities/UserDefaults (~> 6.0)
GTMSessionFetcher/Core (~> 1.1)
Protobuf (~> 3.12)
FirebaseMLVision (0.21.0):

FirebaseCore (~> 6.9)
FirebaseMLCommon (~> 0.21)
GoogleAPIClientForREST/Core (~> 1.3)
GoogleAPIClientForREST/Vision (~> 1.3)
GoogleToolboxForMac/Logger (~> 2.1)
"GoogleToolboxForMac/NSData+zlib (~> 2.1)"
GTMSessionFetcher/Core (~> 1.1)
Protobuf (~> 3.12)
FirebaseMLVisionTextModel (0.21.0):

FirebaseMLVision (~> 0.21)
FirebasePerformance (3.3.2):

FirebaseCore (~> 6.9)
FirebaseInstallations (~> 1.5)
FirebaseRemoteConfig (~> 4.7)
GoogleDataTransport (~> 7.0)
GoogleToolboxForMac/Logger (~> 2.1)
"GoogleToolboxForMac/NSData+zlib (~> 2.1)"
GoogleUtilities/Environment (~> 6.2)
GoogleUtilities/ISASwizzler (~> 6.2)
GoogleUtilities/MethodSwizzler (~> 6.2)
GTMSessionFetcher/Core (~> 1.1)
Protobuf (~> 3.12)
FirebaseRemoteConfig (4.9.1):

FirebaseABTesting (~> 4.2)
FirebaseCore (~> 6.10)
FirebaseInstallations (~> 1.6)
GoogleUtilities/Environment (~> 6.7)
"GoogleUtilities/NSData+zlib (~> 6.7)"
FSCalendar (2.7.9)

**Comment by rajatgupta9021** [comment]
Just need to update the status, Crash logs are coming on debug build but whenever I am testing on TF build crashes are not coming. For DSYM I used these command
- script: |
      npm install -g @datadog/datadog-ci
      export DATADOG_API_KEY='$(DATADOG_API_KEY)'
      datadog-ci dsyms upload ~/Library/Developer/Xcode/DerivedData/
    displayName: 'Upload DSYM'

**Comment by maxep** [comment]
Hi @rajatgupta9021, thanks for using our crash reporter.

As @ncreated [mentioned](https://github.com/DataDog/dd-sdk-ios/issues/634#issuecomment-942096892), make sure to initialise Datadog SDK before Firebase on your TestFlight build. Also, crash reports are sent after restarting the application, you should give it few seconds before it got uploaded.

In regards of the dSYMs uploads, do you have Bitcode enabled?

**Comment by rajatgupta9021** [comment]
@maxep : Update for this, Yes Datadog is initializing before the Firebase only. It worked when I commented on this line and I am able to get the crashes. But it seems it's not giving the line number with the method it crashed

Just to add you Bit code is not enabled in our project.

Steps tried on our end:
1. Add index of the bound crash in our code
2. Install Testflight build and generate the crash on button tap

I am attaching the crash, Please have a look:
SIGTRAP (#0): Application crash: SIGTRAP (Trace/BPT trap)
Thread 0 Crashed:
0  RiseLiving         0x0000000102feb040 Swift runtime failure: Index out of range + 0 <compiler-generated>:0
1  UIKitCore          0x00000001982e35a0 0x19775f000 + 12076448
2  UIKitCore          0x0000000197c418d4 0x19775f000 + 5122260
3  UIKitCore          0x0000000197c41c28 0x19775f000 + 5123112
4  UIKitCore          0x0000000197c404f8 0x19775f000 + 5117176
5  UIKitCore          0x0000000198320c04 0x19775f000 + 12327940
6  UIKitCore          0x000000019832256c 0x19775f000 + 12334444
7  UIKitCore          0x00000001982fc190 0x19775f000 + 12177808
8  Datadog            0x000000010686b560 UIApplicationSwizzler.SendEvent.selector.unsafeMutableAddressor + 36 UIApplicationSwizzler.swift:33
9  Datadog            0x000000010686b5c4 thunk for @escaping @callee_guaranteed (@guaranteed UIApplication, @guaranteed UIEvent) -> (@unowned Bool) + 56 <compiler-generated>:0
10 UIKitCore          0x0000000198383560 0x19775f000 + 12731744
11 UIKitCore          0x00000001983864b8 0x19775f000 + 12743864
12 UIKitCore          0x000000019837da3c 0x19775f000 + 12708412
13 CoreFoundation     0x000000019593f81c 0x1958a1000 + 649244
14 CoreFoundation     0x000000019593f718 0x1958a1000 + 648984
15 CoreFoundation     0x000000019593ea28 0x1958a1000 + 645672
16 CoreFoundation     0x0000000195938d20 0x1958a1000 + 621856
17 CoreFoundation     0x00000001959384bc 0x1958a1000 + 619708
18 GraphicsServices   0x00000001ac3bd820 0x1ac3ba000 + 14368
19 UIKitCore          0x00000001982dc734 0x19775f000 + 12048180
20 UIKitCore          0x00000001982e1e10 0x19775f000 + 12070416
21 RiseLiving         0x00000001027c69e8 main + 68 AppDelegate.swift:42
22 libdyld.dylib      0x00000001955ffe60 0x1955ff000 + 3680

**Comment by rajatgupta9021** [comment]
@ncreated @maxep Do we have any updates on the above?
