### ISSUE TITLE
macOS support

### ISSUE THREAD

**Issue by cszatma** [DataDog/dd-sdk-ios#78]
I'm a huge fan of datadog and my team uses it for our backend services. I am currently in the process of implementing it on iOS so that we can have a unified logging service across all platforms. An issue though has been the lack of macOS support. We have an iOS and a macOS app which share a lot of code. Because of this I have to reside to `#if os` checks to make sure the shared code can compile on both iOS and macOS. It would be great if we could use this SDK to log to datadog from our macOS app as well.

I found PR #55 where macOS support was removed. It mentioned that macOS support might be added back if requested. Is this a possibility?

**Comment by kokliKo** [comment]
Hey! Thanks for reaching out!
Unfortunately we've decided to delay the support of Mac OS for now, as it implies a lot of complexity which would delay the beta release by at least a few weeks.
We think we'll re-evaluate this when the beta is considered stable.

**Comment by buranmert** [comment]
We are closing this issue until we re-evaluate macOS support

**Comment by AvdLee** [comment]
@buranmert can we re-evaluate and reopen this issue? 🙏🙏🙏

**Comment by guillaumekh** [comment]
Hey @ncreated @maxep 
Has macOS support been re-evaluated since removal in 2020? If so, is there any hope to see it added back anytime soon?

To be fair, I don't expect the business case to have improved over the last few years — might even have been the other way around 😅.

**Comment by plousada** [comment]
Hello @guillaumekh. 
We still haven't seen a vast need for macOS support from our existing clients.

Ideally, if you're already a Datadog customer already please ask your Account Manager to open a Feature Request on your behalf on it. 
That will help raise visibility with our Product team and may cause it to gain priority.

**Comment by clintonb** [comment]
@plousada I’m a customer considering migrating away from Datadog due to the lack of sufficient macOS support. You may have a chicken-and-egg problem. Folks may not want to wait months for you all to implement macOS support, so we migrate to platforms that support macOS.

**Comment by dpihlaja** [comment]
This has been our solution. 

https://github.com/TouchBistro/dd-sdk-macOS

**Comment by MaximBazarov** [comment]
@plousada at this point it's just an embarrassment to not support all Apple platforms, besides maybe not a big number of Mac apps using it, you also blocking using the SDK or anything that uses the SDK from building for MacOS, and the years you had to reevaluate the complexity of how it is build and still no result is a shame.

Datados as a platform makes an impression of very well though solution, everything but this SDK. The fact people spend days to rebuild or workaround your decisions, should give you a signal enough, to prioritize this. 


People need tracing and logging, and since platform is one of the best, devs are locked to it because other teams using it, please find some care about developers and make it right otherwise you just being hostile.

**Comment by MaelNamNam** [comment]
Hi Maxim and first of all, thanks for speaking plainly, we appreciate all the feedback we get from our customers, whether it's good or bad.

We understand how frustrating the situation can be, and we're sorry that you're feeling we're being "hostile" as it's absolutely not our intention. Yet, we're not embarrassed by this lack of support, and If I may, let me chime about the rationale behind it:
1. **We're prioritising _'mainstream'_ over _'niche'_** – we're just playing the same game as any other company and shipping features that will be valuable for as many of our customers as possible. I'm not saying that MacOS is niche, but rather that, so far, amongst our existing customers and the prospects we've been talking to, the need for a MacOS SDK has not been widespread. Therefore, we've been focused on other topics that seemed to have a higher return on investment
2. **We're prioritising quality over quantity** – we don't cover as many frameworks or platforms as some of other observability vendors, true. But when we allow an SDK to compile, we want to make sure that:
    1. it runs well once deployed on an application used by real people _(and by 'run well' we also mean that it doesn't not affect the stability or noticeable performances of the host application)_
    2. we have the bandwidth to maintain it and make it evolve over time _(we do not want to claim we support an OS then have an SDK that does not receive any update for the next 2 years, as it often happens when multiplying the supported pieces of technology)_
    3. we have the bandwidth to support our customers if they are facing issues while adopting it

Now, we revisit our priorities constantly, and if you want to help us build a business case around the support of MacOS, being vocal here but also and foremost, escalating this to the Sales rep in charge of your account, is helpful.

Let us know if you'd like to discuss this further.

Best,

**Comment by MaximBazarov** [comment]
Hey @MaelNamNam thanks a lot for your message, and my deepest apologies for the tone of my previous message, not that I'm happy with but too late to change, that's on me.


I do understand what you saying and it shows in the SDK, that your approach is for quality and security with stability and I'm happy to see that.

There might be a misunderstanding, I didn't mean you have to prioritize the support for macOS as you support iOS, with all that RUM and automatic collection of metrics. What I would like to see is Core, Tracing and Logging to be extracted in a package that is platform agnostic, so we can build our metrics ourselves, right now it's not possible.

Also form the setup you have right now it wouldn't be an effort that would require product prioritization, it will help you with moving faster as you Open telemetry protocol is isolated from the rest of the codebase, this will also enable community to build that mentioned automatic metrics collection.


What I'm saying if your team could get it as a chore or maintenance task that would greatly benefit us all.

**Comment by MaelNamNam** [comment]
Haha we can't hide anything, can't we? The thing is, we didn't initially planned to officially support it, so our bandwidth on this would be super limited. Therefore, if we merge the PR, at first we'd be in a 'use at your own risk' kind of situation, which is not the type of support we thrive for in the team. But actually I'm happy to hear how you'd feel about this :)

**Comment by MaximBazarov** [comment]
Totally can't :) the product is too hot and you went open source :D 

This is is a huge leap, can't say for everyone, and I'm probably too niche with my requirement as you mentioned before, but after this merged it's all I need for enabling alerts when something goes wrong, for apps but also for tools, and I think that will enable swift on server to also use Datadog, which should be huge.

I know you are under pressure of responsibility to provide a product that is ready to use and proven to be stable, and probably you will be swallowed by "hey macOS enabled but this RUM doesn't work" and that sucks but I hope you will find the balance there. 

Thank you for the effort!

**Comment by MaelNamNam** [comment]
Hi Maxime 👋 Noted, thanks for sharing your view. We'll regroup and update you soon on the next steps for MacOS support :) Talk soon

**Comment by maciejburda** [comment]
https://github.com/DataDog/dd-sdk-ios/releases/tag/2.11.0

We've added unofficial support for macOS

**Comment by sethi-ishmeet** [comment]
Has anyone been able to use this ask if MacOS is one of the targets? I get the following error and haven't been able to get around it. 

![Image](https://github.com/user-attachments/assets/f076cef6-8945-4fa8-b6f6-976fd3028f4d)

**Comment by mariedm** [comment]
Hi @sethi-ishmeet 👋 

Based on your screenshot (`No such module 'UIKit'`), it looks like your macOS build is trying to compile a file that imports RUM, which isn't available for macOS. 

To fix this, ensure that **RUM is only imported in iOS builds** by using conditional compilation in any file that imports it:

```swift
#if os(iOS)
import DatadogRUM
#endif
```

**Comment by sethi-ishmeet** [comment]
@mariedm This code is part of the Datadog SDK. If you look at the file path closely on top. I am not able to edit this file.

**Comment by sethi-ishmeet** [comment]
Thank you for assistance @mariedm but I am still seeing the error even after I completely restrict Datadog to iOS. Could this be related to how packages are imported in the project?

![Image](https://github.com/user-attachments/assets/f7cbc89e-1f5f-49bd-893c-b4f12c5dcad7)

**Comment by mariedm** [comment]
Hi @sethi-ishmeet, this looks like a configuration issue with your project rather than an issue with our SDK.

But here are a few things you could try:
- Are you using a separate macOS target, or is your app built as a single target supporting both iOS and macOS?
  - If single target, make sure you wrap all RUM-related imports in `#if os(iOS)`, as suggested above.
  - If separate targets, `DatadogRUM` should be linked only to the iOS target.
- Check "Build Phases → Link Binary With Libraries" for the macOS target, and if `DatadogRUM` is listed under macOS, remove it.
- Check "Compile Sources" for the macOS target, and exclude any RUM-related files from macOS.
- If using Swift Package Manager (SPM), ensure `DatadogRUM` is only assigned to iOS.
- Try clearing DerivedData and cleaning the build with this command: `rm -rf ~/Library/Developer/Xcode/DerivedData`

Just as a reminder, **we don't officially support macOS**, so while you may get some functionality working, we can't guarantee full compatibility. In any case, if your app supports both iOS and macOS, you have to ensure that RUM-related code is excluded from the macOS build.

Hope this helps.
