### ISSUE TITLE
How to stop Datadog tracking?

### ISSUE THREAD

**Issue by ferologics** [DataDog/dd-sdk-ios#785]
### ThE tHinG

One thing is that **Discussions** would be a nice addition to the repo (this isn't really an issue).

The actual thing is: how can I stop Datadog? rum & tracer? replace by noop implementations? How to construct those? inits are internal. All I see is the `Datadog.clearAllData()` function but not a confirmation that this is enough to cease the SDK activity.

**Comment by tshort15-ford** [comment]
Looks like you can enable/disable those - see https://docs.datadoghq.com/real_user_monitoring/ios/advanced_configuration/?tab=swift#rum-configuration

**Comment by ncreated** [comment]
Hello @ferologics 👋, sorry for delay (and glad we get help from community, thx @tshort15-ford). Yes, there is no option to stop the SDK at runtime, but you can opt-out from enabling some of its features (RUM / Logging / Tracing) at startup. Hope this makes sense and solves your problem 🙏.

> One thing is that Discussions would be a nice addition to the repo (this isn't really an issue).

Can't promise, but it's noted ✅. We already have our [dedicated help channels](https://www.datadoghq.com/support/) and we want to keep their number relatively low, so we can provide best support.
