### ISSUE TITLE
SwiftUI Automated support

### ISSUE THREAD

**Issue by jostster** [DataDog/dd-sdk-ios#829]
What is the best way to use RUM for iOS with a 90/10 SwiftUI / UIView app, without having to go and add modifiers to every existing button and view? Would datadog RUM allow the tie in of `accessibilityIdentifer` for tracking so developers don't have to go back and add another modifier to all the fields in their application?

Most swiftui is ran from a UIHostingController so it seems most views are tracked as that instead of the view. Would there be an easy way to have it use the struct name of the View like it does for UIViewControllers?

**Comment by maxep** [comment]
Ah indeed, if you subclass `UIHostingController` it will be considered as custom and won't be excluded from tracking. We might change this in the future and exclude `UIHostingController` and subclasses. But for the time being, I suggest you manually exclude them by providing a custom `UIKitRUMViewsPredicate` implementation to the SDK builder, such as:

```swift
class SwiftUIPredicate: UIKitRUMViewsPredicate {
    let `default` = DefaultUIKitRUMViewsPredicate()

    func rumView(for viewController: UIViewController) -> RUMView? {
        if viewController is YourHostingController {
            return nil
        }

        return `default`.rumView(for: viewController)
    }
}

Datadog.initialize(
    ...
    configuration: Datadog.Configuration
        .builderUsing(...)
        .trackUIKitRUMViews(using: SwiftUIPredicate())
        .build()
)
```

**Comment by maxep** [comment]
I will close this issue, but feel free to add any other comment!
