### ISSUE TITLE
UIApplication.applicationState must be used from main thread only

### ISSUE THREAD

**Issue by marcgeeklaberge** [DataDog/dd-sdk-ios#853]
We noticed that our react native app is breaking on LaunchScreen sometimes and we get the following error:
`Main Thread Checker: UI API called on a background thread: -[UIApplication applicationState]
PID: 32891, TID: 144843, Thread name: (none), Queue name: dd-react-native-sdk`

I can also see this old Memory, Thread, and Crash Issue on your SDK here: 
https://github.com/DataDog/dd-sdk-ios/blob/b99e4934855b92051ac74395cbb64f3752c6bd9f/Sources/Datadog/Core/System/AppStateListener.swift#L155
<img width="1227" alt="Screen Shot 2022-05-16 at 2 07 00 PM" src="https://user-images.githubusercontent.com/13422375/168658077-960f4519-2f01-4307-97c8-d15646171051.png">

**Comment by marcgeeklaberge** [comment]
@ncreated If that can help, here's the crash trace:
[UI_MAIN_THREAD_CRASH.zip](https://github.com/DataDog/dd-sdk-ios/files/8709222/UI_MAIN_THREAD_CRASH.zip)

**Comment by marcgeeklaberge** [comment]
We did not released the version containing this in prod yet. 
We are able to reproduce this by fresh re-installing the app from xcode on both simulators and real devices.
I will test with Testflight build and update this comment after.

Thank you for assessing this quickly 🙏

**Comment by marcgeeklaberge** [comment]
This can also be related to the following:
https://github.com/DataDog/dd-sdk-reactnative/blame/98983246beeba731b0af67855eef4f349fbc0fe9/packages/core/ios/Sources/DdSdk.swift#L15
I know it's there since a long time, but maybe it can help you in your investigations.

**Comment by floriangbh** [comment]
Same issue here :)

**Comment by maxep** [comment]
Hey 👋 

Since version 1.9.0 of the SDK, it is no longer possible to call `Datadog.initialize(...)` on a background thread. You can call `Datadog.initialize(...)` on the main thread, either in the your `AppDelegate` or `SwiftUI.App/init` to workaround this.

We are currently working on a `2.0` version of the SDK that will solve this issue 👍

**Comment by maxep** [comment]
Fixed in [`2.0`](https://github.com/DataDog/dd-sdk-ios/releases/tag/2.0.0)
