### ISSUE TITLE
How to set "host" attribute?

### ISSUE THREAD

**Issue by takoikatakotako** [DataDog/dd-sdk-ios#856]
### How to set host attribute?

I want to set host attribute. But this is not working.
How to set host attribute?

```
Datadog.initialize(
        appContext: .init(),
        trackingConsent: .granted,
        configuration: Datadog.Configuration
            .builderUsing(clientToken: "{MY_TOKEN}", environment: "MyEnvironment")
            .set(serviceName: "MyServiceName")
            .build()
    )
        
let logger = DDLogger.builder
    .sendNetworkInfo(true)
    .printLogsToConsole(true, usingFormat: .shortWith(prefix: "[Datadog Logger] "))
    .build()
        
logger.addAttribute(forKey: "host", value: "MyHostName")
                
logger.info("Log Message", attributes: ["host": "MyHostName"])
```

![Screen Shot](https://user-images.githubusercontent.com/7970479/168804347-3a3e1a04-c744-476e-b83a-0dffe2d88a9f.png)

This SDK is very useful. Thank you!🙏

**Comment by ncreated** [comment]
Hello @takoikatakotako 🙂👋. Unfortunately, "host" is one of our few [reserved attributes](https://github.com/DataDog/dd-sdk-ios/blob/b99e4934855b92051ac74395cbb64f3752c6bd9f/Sources/Datadog/Logging/Log/LogEventSanitizer.swift#L12-L15) and you need to use a different name for it (I hope this won't be a problem for you). Some other reserved names are:
```
"host", "message", "status", "service", "source", "ddtags"
```
To make sure your attributes do not conflict with our internal ones, you can [enable `Datadog.verbosity = .warn` flag while debugging](https://docs.datadoghq.com/real_user_monitoring/ios/troubleshooting/#debugging). It will print SDK internal warnings to the console, e.g.:
```
[DATADOG SDK] 🐶 → 16:54:24.276 [ERROR] 'host' is a reserved attribute name. This attribute will be ignored.
```

Let me know if renaming attribute worked for you and we're happy you looked at our SDK 🙂.

**Comment by takoikatakotako** [comment]
@ncreated Thanks for the your reply.🙏
I understood reserved attributes and debugging mode.
Renaming attribute worked fine!!😊

But I hope I set "host" attribute like `set(serviceName: String)` method.
Other team use "host" attribute and my boss may instruct me, "If the SDK can't set host attribute,  use WebAPI".
I want to use this SDK.😂

Thank you for all the information you have given me.😄🙏
