### ISSUE TITLE
iOS SDK Logs have version as an attribute, not a tag like the Android SDK

### ISSUE THREAD

**Issue by Danny-SS** [DataDog/dd-sdk-ios#891]
When using the iOS SDK to Log to Datadog, I noticed my app has a `version` **attribute** to my logs.  However, my colleague using the Android SDK creating a similar Log automatically has `version` as a **tag**.

My solution was to addTag() programmatically. The downside, is `version` in both a tag and attribute with the same value for logs coming from iOS.  But at least our two teams are in sync for our tags.

I am just wandering if this was intentional or an oversight.

![Screen Shot 2022-06-13 at 5 29 49 PM](https://user-images.githubusercontent.com/31970539/173449646-581429b6-930e-40b1-8915-8ca57d0d7c0d.png)

![Screen Shot 2022-06-13 at 5 28 50 PM](https://user-images.githubusercontent.com/31970539/173449667-2858c4ff-7f70-45a4-a350-79285845a103.png)

**Comment by ncreated** [comment]
Hello @Danny-SS 👋. Thanks for spotting this. Indeed, there is a discrepancy between the [iOS](https://github.com/DataDog/dd-sdk-ios/blob/0dbfadf9d226abadc1339aef35eac909de88790e/Sources/Datadog/Logging/Log/LogEventEncoder.swift#L219) and [Android implementation](https://github.com/DataDog/dd-sdk-android/blob/3638d6b2bcffaffa2d3261b93b09fe0a6bbab767/dd-sdk-android/src/main/kotlin/com/datadog/android/log/internal/domain/LogGenerator.kt#L121-L126) of default log tags. We will work on aligning this in `dd-sdk-ios`.

Meantime, your workaround with adding `version` tag manually will work fine and have exactly the same effect as if it was added by the SDK 👍.

**Comment by ncreated** [comment]
Closing as this issue was already fixed a while ago - `version` tag was added back in https://github.com/DataDog/dd-sdk-ios/pull/914 - it is available since **[1.12.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0)**.
