### ISSUE TITLE
Compilation fails for Catalyst after update to 1.11.0

### ISSUE THREAD

**Issue by alexisbar** [DataDog/dd-sdk-ios#892]
Compilation fails for Catalyst target since `1.11.0`

24 compiler error are raised, all in `CarrierInfoProvider.swift`, and all related to `CoreTelephony`

After a quick look in the history of this file, this seems related to https://github.com/DataDog/dd-sdk-ios/pull/764/files that replaced the `#if targetEnvironment(macCatalyst)` checks by a `#if os(iOS)`

![Capture d’écran 2022-06-14 à 17 12 06](https://user-images.githubusercontent.com/8861304/173612990-1743f33d-bddc-4372-9656-812b9f774393.png)

**Comment by ncreated** [comment]
Hello @alexisbar 👋. Thanks for report. Clearly, we have a regression here - we will be deploying a hotfix soon.

**Comment by ncreated** [comment]
Fixed in [`1.11.1`](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.11.1). Thanks for report @alexisbar 👍.
