### ISSUE TITLE
Using dd-sdk-ios in another SDK

### ISSUE THREAD

**Issue by deepesh-vasthimal-cko** [DataDog/dd-sdk-ios#90]
**Is your feature request related to a problem? Please describe:**
📝 Integrate datadog with 2 different API keys, one which is used by iOS SDK and one which is used by the iOS app itself using the same SDK to trace logs. Will this cause any conflicts like other logging frameworks ? 

**Describe the solution you'd like:**
📝 Integrate datadog with 2 different API keys, one which is used by iOS SDK and one which is used by the iOS app itself using the same SDK to trace logs.

**Comment by ncreated** [comment]
Hello @deepesh-vasthimal-cko 👋 . Just to clarify if I get it right, your app uses your custom framework (your SDK) and you want to use Datadog SDK in both the app and the framework, with using two distinct client tokens?

```
[app] ---uses---> Datadog SDK
[app] ---uses---> your SDK
[your SDK] ---uses---> Datadog SDK
```

If that's correct, this is not possible for now, as there can be only one instance of the SDK running within the process.

Is this your in-house app setup? Or you're building a vendor SDK which you want to additionally instrument with Datadog SDK (then it might conflict if your client's app is also using Datadog SDK)?

**Comment by deepesh-vasthimal-cko** [comment]
Yes i am developing a vendror SDK which will be used by app developers. Can you please tell me if this is not currently supported then if its in your future list of things to support or what alternative can you suggest ?

**Comment by ncreated** [comment]
@deepesh-vasthimal-cko this is not currently supported. We discussed it internally, and we may come up with a solution in the future 👌, but it doesn't yet exist on our roadmap and we don't put any estimation on it.

With the current shape of `dd-sdk-ios` this is not difficult technically, but when looking at our roadmap it will make iterations on upcoming features way more difficult. Adding explicit support for vendor SDKs will be easier for us after reaching certain level of features implementation, when we'll see clearly what are the constraints.

Let me know if this answers your question and if we can help more 🙂.

**Comment by deepesh-vasthimal-cko** [comment]
Thanks for the detailed explanation really appreciate that. We were currently evaluating to purchase data dog and if this isn't supported can you provide us with some alternative solutions we could have with your expertise on logging products ?

**Comment by ncreated** [comment]
@deepesh-vasthimal-cko is forking our SDK and adjusting it for this use case an option for you? Given the current shape of the SDK (and only Logging feature being released), this should not require a lot of work. Of course this will come with the cost of maintaining the fork and updating it with our upstream if important fixes occur.

**Comment by deepesh-vasthimal-cko** [comment]
@ncreated thanks for your reply, So you mean your team can fork the repo and adjust it to our needs which will make 2 instances of datadog running possible one on app and other on SDK. And any future mandatory fixes will be notified to us so that we can pull those commits as cherry picks ? and any conflicts your team can help us ? . if all is this ok can it be done both on iOS and Android SDKs ?

**Comment by deepesh-vasthimal-cko** [comment]
@ncreated what if we directly use data dog API for logging ? and not use the iOS or android SDK itself. Then we can solve the problem of having 2 instances of data dog running ? , will that be viable solution ?  Thanks

**Comment by ncreated** [comment]
Hey @deepesh-vasthimal-cko 👋 🙂. As I said, we don't have resources now to maintain the Vendor SDK - compatible version of the SDK, neither its fork. I was rather asking if this is an option for you to fork it by your own and customize as you need.

> what if we dont directly use data dog API and ? and not use the iOS or android SDK data dog itself. Then we can solve the problem of having 2 instances of data dog running ? , will that be viable solution ?

Totally! If you decide to do it, I think you might find our open source iOS and Android SDKs extremely helpful on details about the interaction with Datadog API. What you are interested in is [Send Logs over HTTP API reference](https://docs.datadoghq.com/api/?lang=bash#send-logs-over-http). This is exactly what we use in [dd-sdk-ios](https://github.com/DataDog/dd-sdk-ios) and [dd-sdk-android](https://github.com/DataDog/dd-sdk-android).

This way might be even better for you, as your SDK might require different logs upload circumstances than the heuristic provided by Datadog iOS SDK and / or associate different set of default attributes with logs.

Let me know if I can help more 🙂.

**Comment by ncreated** [comment]
I'm closing this issue, as we do not have close plans to put this onto our roadmap. All the details and possible solutions were discussed above.
