### ISSUE TITLE
Errors not shown in Error Tracking depending on the method used

### ISSUE THREAD

**Issue by ivan-hernandez-scopely** [DataDog/dd-sdk-ios#907]
### Errors not shown in Error Tracking depending on the method used

**Describe what happened**

-  Using those `DDRUMMonitor ` calls i would expect for each error to have a new issue or link it to an existing issue:
   - public func `addError`(message: String,source: DDRUMErrorSource,stack: String?,attributes: [String: Any])
   - public func `addError`(error: Error,source: DDRUMErrorSource,attributes: [String: Any])
   - public func `stopResourceLoadingWithError`(resourceKey: String,error: Error,response: URLResponse?,attributes: [String: Any])
   - public func `stopResourceLoadingWithError`(resourceKey: String,errorMessage: String,response: URLResponse?,attributes: [String: Any])
  - But actually only one of those works as expected:
    - `addError`, but only if add the `stacktrace` in the `NSError` and use `DDRUMErrorSource Source`
    - `stopResourceLoadingWithError` + `NSError` does not report the issue for the error. Maybe because the source is .network instead of .source? (in Android we can change it to .source and it starts working).
    - Also It will be nice to be able to setup the error type as a parameter or a custom attribute like in Android, instead of the "self.type = "\(nsError.domain) - \(nsError.code)""

**Steps to reproduce the issue:**
- Call any of those methods.

**Describe what you expected:**
- I would expect that any of those calls aside from showing an error on my view also add an issue to be able to check those errors in the Error Tracking.
- Also i would expect that errors with the same stacktrace but different messages to be logged as different issues...
- I would expect an addError and a stopResourceLoadingWithError with those params:
- (message: String,source: DDRUMErrorSource, stack: String?, errorType: String?, attributes: [String: Any])

**Comment by maxep** [comment]
Hi @ivan-hernandez-scopely 

Thanks for the detailed report! I will ask internally if this is a feature or a bug.

**Comment by maxep** [comment]
Hey @ivan-hernandez-scopely !

I see that @xgouchet has given you more context on how Error Tracking works DataDog/dd-sdk-android#959

> Also It will be nice to be able to setup the error type as a parameter or a custom attribute like in Android

This is already possible when you stop the resource loading on an error with a `URLResponse`, see [this method](https://github.com/DataDog/dd-sdk-ios/blob/master/Sources/Datadog/RUMMonitor.swift#L508). We follow the same convention on both Android and iOS.

I hope this help!
