### ISSUE TITLE
Missing DatadogAlamofireExtension from Package.swift

### ISSUE THREAD

**Issue by anuragajwani** [DataDog/dd-sdk-ios#911]
### The issue

I am migrating to Tuist and SPM. We currently use the following modules from Datadog through Cocoapods:
- DatadogSDK
- DatadogSDKAlamofireExtension
- DatadogSDKCrashReporting

Each of these pods have its individual podspec. However the project contains a single `Package.swift` with  the following products:
```
 products: [
        .library(
            name: "Datadog",
            type: .dynamic,
            targets: ["Datadog"]
        ),
        .library(
            name: "DatadogObjc",
            type: .dynamic,
            targets: ["DatadogObjc"]
        ),
        .library(
            name: "DatadogStatic",
            type: .static,
            targets: ["Datadog"]
        ),
        .library(
            name: "DatadogStaticObjc",
            type: .static,
            targets: ["DatadogObjc"]
        ),
        .library(
            name: "DatadogCrashReporting",
            type: .static,
            targets: ["DatadogCrashReporting"]
        ),
    ],
```

As you'll notice `DatadogAlamofireExtension` is missing from this list. Thus I am unable to consume `DatadogAlamofireExtension` directly from this repo through SPM.

---

#### Datadog SDK version: 1.11.1

_Which version of the Datadog SDK causes this problem? e.g. `1.2.0`_

#### Last working Datadog SDK version: 

_What is the last Datadog SDK version where this problem didn't occur? e.g. `1.1.0`_

#### Dependency Manager: SPM

_Which dependency manager do you use? e.g. Cocoapods / Carthage / SPM / ..._

#### Other toolset:

- Tuist
_Do you use additional tools with your dependency manager? e.g. [CarthageCache](https://github.com/Wolox/carthage_cache)_

#### Xcode version:
- 13.4

_e.g. `Xcode 11.5 (11E608c)`_

#### Swift version: 5.6.1

_e.g. `5.1`_

#### Deployment Target: 14.0

_What is the Deployment Target of your app? e.g. `iOS 12`, `iPhone` + `iPad`_

#### macOS version:

_e.g. `macOS Catalina 10.15.5 (19F96)`_

**Comment by maxep** [comment]
Hi @anuragajwani ! thank you for the report.

Indeed, the Alamofire integration does not support Carthage nor SPM. But as it is mentioned [here](https://github.com/DataDog/dd-sdk-ios/tree/develop/Sources/DatadogExtensions/Alamofire#carthage-and-spm), this extension is composed of a single file that easily be copied to your source files.

The main reason for this omission is that Carthage and SPM will download transitive dependencies even if you don't use them in your project. That would increase build time, and given the size of the Alamofire extension, we decided to exclude it.
