### ISSUE TITLE
Library not loaded crash when installing to device

### ISSUE THREAD

**Issue by iamluisg** [DataDog/dd-sdk-ios#915]
### The crash

📝 Give us the crash report or stack trace, describe the problem in details and answer the questions.

Hello. After adding the Datadog package via SPM the app is crashing upon the app starting when I attempt to install on an actual device (iPhone). I can successfully run the app on simulators, but when I attempt to run on device I receive the following crash report

```
dyld[12340]: Library not loaded: @rpath/Datadog.framework/Datadog
  Referenced from: /private/var/containers/Bundle/Application/D021D71E-0821-4ACB-B40F-EBC808A33ED1/Dash Dev.app/Dash Dev
  Reason: tried: '/private/var/containers/Bundle/Application/D021D71E-0821-4ACB-B40F-EBC808A33ED1/Dash Dev.app/Frameworks/Datadog.framework/Datadog' (no such file), '/private/var/containers/Bundle/Application/D021D71E-0821-4ACB-B40F-EBC808A33ED1/Dash Dev.app/Frameworks/Datadog.framework/Datadog' (no such file), '/System/Library/Frameworks/Datadog.framework/Datadog' (no such file)
Library not loaded: @rpath/Datadog.framework/Datadog
  Referenced from: /private/var/containers/Bundle/Application/D021D71E-0821-4ACB-B40F-EBC808A33ED1/Dash Dev.app/Dash Dev
  Reason: tried: '/private/var/containers/Bundle/Application/D021D71E-0821-4ACB-B40F-EBC808A33ED1/Dash Dev.app/Frameworks/Datadog.framework/Datadog' (no such file), '/private/var/containers/Bundle/Application/D021D71E-0821-4ACB-B40F-EBC808A33ED1/Dash Dev.app/Frameworks/Datadog.framework/Datadog' (no such file), '/System/Library/Frameworks/Datadog.framework/Datadog' (no such file)
```

#### Datadog SDK versions:

_Which version(s) of the Datadog SDK you see this crash happening in?_
1.11.1

#### Last stable Datadog SDK version:

_What is the last Datadog SDK version where this crash doesn't happen?_

I haven't attempted to install previous versions of Datadog in this specific Xcode project. (Other SPM packages are working correctly in this Xcode project)

#### Volume:

_What % of your app sessions is impacted with this crash?_
100% of attempts to install this app onto my device cause crashes. After removing the Datadog package I was able to run the app successfully on device again.

#### OS version:

_Which iOS versions does this crash happen on?_

It is happening on iOS v15.4

#### Deployment Target:

_What is the Deployment Target of your app? e.g. `iOS 12`, `iPhone` + `iPad`_

iOS 15.0

#### Device version:

_Which devices does this crash happen on? e.g. `iPhone X` only or various iPads_

Happens on various iPhone devices (iPhone 12 Pro and iPhone 13 pro)

#### Environment:

_Do you notice any environment correlation in crash reports? e.g. low battery, no internet connection, memory pressure_

No

**Comment by maxep** [comment]
Hi @iamluisg 👋 

In you application **General**, under **Frameworks, Libraries, and Embedded Content**, make sure you have selected `Embed & Sign`, like below:

<img width="792" alt="image" src="https://user-images.githubusercontent.com/6815992/176914248-b7cb34fd-deaa-4b29-8af5-ed4561435365.png">

Let me know if that fixed the issue!

**Comment by iamluisg** [comment]
@maxep That fixed the issue! Thank you very much for the quick reply and help.
