### ISSUE TITLE
'UIKit/UIKit.h' file not found

### ISSUE THREAD

**Issue by kunalmohan** [DataDog/dd-sdk-ios#920]
### The issue

📝 Give us the error message you receive, describe the problem and answer the questions.
I'm building a dynamic swift library for iOS. After declaring the Datadog sdk as a dependency in Package.Swift file, the library doesn't build. It throws the following error message:

```
fatal error: 'UIKit/UIKit.h' file not found
```
I'm not using Xcode to develop the library.
(I'm quite new to swift and iOS dev, so any tips/suggestions are appreciated)

---

#### Datadog SDK version: 1.11.1

_Which version of the Datadog SDK causes this problem? e.g. `1.2.0`_

#### Last working Datadog SDK version:

_What is the last Datadog SDK version where this problem didn't occur? e.g. `1.1.0`_

#### Dependency Manager: SPM

_Which dependency manager do you use? e.g. Cocoapods / Carthage / SPM / ..._

#### Other toolset:

_Do you use additional tools with your dependency manager? e.g. [CarthageCache](https://github.com/Wolox/carthage_cache)_

#### Xcode version:

_e.g. `Xcode 11.5 (11E608c)`_

#### Swift version: 5.6.1

_e.g. `5.1`_

#### Deployment Target: iOS 14.5

_What is the Deployment Target of your app? e.g. `iOS 12`, `iPhone` + `iPad`_

#### macOS version: macOS Monterey 12.4

_e.g. `macOS Catalina 10.15.5 (19F96)`_

**Comment by maxep** [comment]
Hi @kunalmohan 👋 

Thank you for using our SDK 🙂 

Do you have Xcode installed? Even if you use the `swift` cli, you still need the Xcode toolchain to build an iOS library. The Xcode toolchain includes `UIKit` and other dedicated frameworks that we use in the Datadog SDK.
SPM is well integrated with Xcode, it will be easier to build your `Package.swift` through Xcode if you are new to the platform.

I hope this help!

**Comment by maxep** [comment]
Hi @kunalmohan! sorry for the late reply...

Are you able to build your package using Xcode?
The issue with `swift` cli is that it builds for macOS target, please refer to this thread: https://forums.swift.org/t/swiftpm-swift-build-for-ios/42517

We do not support macOS with the Datadog SDK, only iOS and tvOS. So it will be easier to build your package with Xcode or the `xcodebuild` cli.

I hope helps!

**Comment by jonluca** [comment]
Is there a way to instrument native Swift macos apps with datadog? I have a background process on a native app that I'd like to send logs from, capture errors, etc.

**Comment by ncreated** [comment]
> Is there a way to instrument native Swift macos apps with datadog? I have a background process on a native app that I'd like to send logs from, capture errors, etc.

Hello @jonluca 👋. Unfortunately we don't support macOS today. It's similar ask to #78 - if you could [send us a feature request](https://www.datadoghq.com/support) it would vastly help us to prioritise this work 🙏.
