### ISSUE TITLE
Setting sample rate?

### ISSUE THREAD

**Issue by dweiner13** [DataDog/dd-sdk-ios#922]
### The issue

The android version of the SDK allows us to set the sample rate for logs via a `setSampleRate` function on the logger builder (https://docs.datadoghq.com/logs/log_collection/android/?tabs=java#logger-initialization).

Is there similar functionality for the iOS SDK? I can't find it anywhere.

**Comment by maxep** [comment]
Hi @dweiner13 ! Thank you for the report and sorry for the late reply..

Indeed, unlike Android we do not provide sampling for logs on iOS, we should work on aligning those. I will keep you posted 👍

**Comment by dweiner13** [comment]
@maxep Thank you! For now it's easy enough to manually write that functionality, so no huge rush from my end.

**Comment by maciejburda** [comment]
Hey @dweiner13 

Logging sampling is now available in the SDK.
https://github.com/DataDog/dd-sdk-ios/pull/1045
