### ISSUE TITLE
No sub-second precision in logs

### ISSUE THREAD

**Issue by flobories** [DataDog/dd-sdk-ios#95]
**Describe what happened**
![image](https://user-images.githubusercontent.com/7430239/80761788-15c15f80-8af0-11ea-9da5-3d09c17f0b11.png)
Thanks for developing an iOS first party SDK!
We've been successful integrating it and it has been super helpful.
Unfortunately I recently discovered that sub-second precision was missing from the log explorer, and that logs within a same second appear to be randomly ordered.

**Steps to reproduce the issue:**
Log multiple events within a second.

**Expected behaviour:**
Subsecond precision is reported to the log explorer.

**Actual behaviour:**
Subsecond precision is truncated, and it appears that the log sequence within a given second is random 🙀

**Additional context**
 - OS version and device model: Confirmed on `XS @ iOS 13.4.1`
 - Datadog SDK version: `1.0.2`
 - We are piping our logs to `Datadog` using `SwiftyBeaver` with an additional log destination. The sequence of logs is preserved in our other `SwiftyBeaver` destinations: console output, OSLog...

Some code in sequence:
![image](https://user-images.githubusercontent.com/7430239/80762507-89b03780-8af1-11ea-8849-201d081bd972.png)

You can see that the two logs in the `14:31:51` second are not in the right sequence.

**Comment by buranmert** [comment]
Hi @flobories 👋 
Thanks for reporting such an important issue 🙏 (and sorry for the delay, it was a long weekend here :)

The issue was that `dateEncodingStrategy = .iso8601` was omitting milisecond precision during encoding
I pushed a fix as you can see above and it will be merged soon

**Comment by flobories** [comment]
Absolutely! Thanks for being on top of it 💯

**Comment by koneksa-sunny** [comment]
@flobories how are you piping your swifty beaver logs into datadog?

**Comment by flobories** [comment]
@koneksa-sunny here is a sample Gist https://gist.github.com/flobories/a78919c29e314a707c9114024f48444a
Hope this helps!
