### ISSUE TITLE
Displaying nil attributes in Logs

### ISSUE THREAD

**Issue by Danny-SS** [DataDog/dd-sdk-ios#951]
We are working to convert from NewRelic to Datadog in my organization.  I send my attributes in from iOS with some nil values, those do not appear in the log.  I was expecting to see "null" 

To simplify, I replicated with even using the `addAttribute` method .

```
  @objc public func log(_ message: String) {
        let value: Int?  = 2
        logger.addAttribute(forKey: "boo", value:  value)
        logger.info(message)
    }
```

When I use this method by saying log("hi"), I can see the log and my attribute {"boo" : 2) }. 

However, when I change the method to use `nil` and rerun

```
    @objc public func log(_ message: String) {
        let value: Int?  = nil
        logger.addAttribute(forKey: "boo", value:  value)
        logger.info(message)
    }

```
I can still find my "hi" message, but the "boo" attribute is no longer there.  I was expecting to see {"boo" : null} like on Android.

Maybe I am missing something.

**Comment by maxep** [comment]
Hi @Danny-SS ! sorry for the late reply.

We store attributes in a dictionary, and nilifying a value will remove it from the dictionary in Swift. So setting `nil` will remove the attribute.

May I ask why you want to see `null` values?

**Comment by maxep** [comment]
As a workaround, you can define a wrapper for you attribute, such as:
```swift
struct OptionalEncodable<Wrapped>: Encodable where Wrapped: Encodable {

    /// The nullable wrapped value
    let value: Wrapped?

    /// Encodes this optional value into the given encoder.
    ///
    /// This function throws an error if any values are invalid for the given
    /// encoder's format.
    ///
    /// - Parameter encoder: The encoder to write data to.
    public func encode(to encoder: Encoder) throws {
        var container = encoder.singleValueContainer()
        switch value {
        case .none: try container.encodeNil()
        case .some(let wrapped): try container.encode(wrapped)
        }
    }
}

extension OptionalEncodable: ExpressibleByNilLiteral {

    /// Creates an instance initialized with `nil`.
    init(nilLiteral: ()) {
        self.init(value: nil)
    }
}
```

Then you can do 
```swift
@objc public func log(_ message: String) {
    let value: OptionalEncodable<Int> = nil
    logger.addAttribute(forKey: "boo", value:  value)
    logger.info(message)
}
```

**Comment by Danny-SS** [comment]
> Hi @Danny-SS ! sorry for the late reply.
> 
> We store attributes in a dictionary, and nilifying a value will remove it from the dictionary in Swift. So setting `nil` will remove the attribute.
> 
> May I ask why you want to see `null` values?

Since we are logging a bunch of API responses from our backend when error's occurred, sometimes it is valuable for us to know when our backend team sent the iOS device a null value, in a certain situation, for a field which was supposed to contain an Int (non-optional).

We already gave something like that OptionalEncodable in our Datadog Implementation, but did not have the ExpressibleByNilLiteral.  Thanks for the tip!
