### ISSUE TITLE
Feature Request: Make logging to DDNoopRUMMonitor louder

### ISSUE THREAD

**Issue by dfed** [DataDog/dd-sdk-ios#978]
## Background

Today, accidentally logging user actions or errors to the [DDNoopRUMMonitor](https://github.com/DataDog/dd-sdk-ios/blob/927e1f014f8c729c1fc70bc7578038c5e33f28ff/Sources/Datadog/RUM/RUMMonitor/DDNoopRUMMonitor.swift) does not alert developers of API misuse – developers are only [warned when `startView` events are propagated to it](https://github.com/DataDog/dd-sdk-ios/blob/927e1f014f8c729c1fc70bc7578038c5e33f28ff/Sources/Datadog/RUM/RUMMonitor/DDNoopRUMMonitor.swift#L11-L19).

When an engineer accidentally retains an instance of `Global.rum` prior to running `Global.rum = RUMMonitor.initialize()`, they capture a `DDNoopRUMMonitor` instance. If an engineer then logs a user action or error to this `rum` instance, **no warnings appear in the console**, and of course no logs appear in DataDog dashboards either.

## The baseline request

Update `DDNoopRUMMonitor` to alert a developer that they are misusing the DataDog SDK when  _any_ event (and not just `startView`) is sent to the `DDNoopRUMMonitor`. I'd be happy to put up a PR to accomplish this if the proposal is well received by maintainers.

## The stretch request

Given that console logs might get lost in apps that log a lot to the console, and that errors routed to a `Global.rum` instance are explicitly high-priority events, ideally `DDNoopRUMMonitor`'s `addError` implementation would trigger an `assertionFailure(...)`. Again, I'd be happy to put up a PR to accomplish this if the proposal is well received by maintainers.

**Comment by dfed** [comment]
Sounds great! I've opened #1007 to cover the baseline request. I have no qualms if you would like to close this issue after #1007 lands, though I am hoping that `2.x` gets this stretch request 🙂

**Comment by maxep** [comment]
Thank you again @dfed for your contribution. This will land in `2.x` when we migrate the RUM monitor 👍
