### ISSUE TITLE
Stacktrace is missing class/function names in Datadog log info

### ISSUE THREAD

**Issue by vit-azarov** [DataDog/dd-sdk-ios#987]
Hi there!

I am working on iOS crash logging integration with datadog and here is the problem:
While the logs reach our Datadog dashboard, and the stacktrace is symbolicated, I am not seeing the most important piece of information there - classes and function names caused the problem:
<img width="990" alt="Screen Shot 2022-09-02 at 13 13 10" src="https://user-images.githubusercontent.com/100236985/188196157-e73e0f31-3483-414f-a201-4fc91940f780.png">

Crash log on the device have all detailed data, but for some reason they are missing on Datadog:
<img width="900" alt="Screen Shot 2022-09-02 at 13 13 43" src="https://user-images.githubusercontent.com/100236985/188196591-f4eebb0b-e4fc-4281-9f16-e90e2bdf30fc.png">

Here is my init code from AppDelegate:
```       
Datadog.initialize(
            appContext: .init(),
            trackingConsent: .granted,
            configuration: Datadog.Configuration
                .builderUsing(clientToken: MxConst.datadogClientToken, environment: SystemInfoUtils.getBuildType())
                .set(serviceName: MxConst.datadogLoggerName)
                .set(endpoint: .us1)
                .trackUIKitRUMViews()
                .trackURLSession()
                .enableCrashReporting(using: DDCrashReportingPlugin())
                .build()
        )
```

I am not sure if this is a bug or I misconfigured something, so i am hoping for your help to figure it out.

**Comment by maxep** [comment]
Hi @vit-azarov ! thank you for using our Crash Reporting!

Did you properly upload the dSYM files of your application? You can find the related documentation here: https://docs.datadoghq.com/real_user_monitoring/error_tracking/ios#upload-your-dsym-file
