### ISSUE TITLE
Getting linking error.

### ISSUE THREAD

**Issue by pritiverma22** [DataDog/dd-sdk-ios#996]
### The issue

📝We are trying to integrate datadog with our framework written in objective C language and Getting below error while building with target as "Any iOS Device (arm64)" while it works successfully when building by setting "Active Architecture only" to yes and targeting to specific simulator with iOS version 15 or later:

Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$__TtC11DatadogObjc10DDEndpoint", referenced from:
      objc-class-ref in OOStandardSpotAd.o
  "_OBJC_CLASS_$__TtC11DatadogObjc12DDAppContext", referenced from:
      objc-class-ref in OOStandardSpotAd.o
  "_OBJC_CLASS_$__TtC11DatadogObjc15DDConfiguration", referenced from:
      objc-class-ref in OOStandardSpotAd.o
  "_OBJC_CLASS_$__TtC11DatadogObjc17DDTrackingConsent", referenced from:
      objc-class-ref in OOStandardSpotAd.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

---

#### Datadog SDK version:

_Which version of the Datadog SDK causes this problem? version 1.11.1 . Also getting same error with version 1.11.0

#### Last working Datadog SDK version:

_What is the last Datadog SDK version where this problem didn't occur? Using it for the first time

#### Dependency Manager:

_Which dependency manager do you use? linking binary as a static framework.
#### Other toolset:

_Do you use additional tools with your dependency manager? No

#### Xcode version:

Xcode 13.4.1.  Upgraded to xcode 14.o also giving same error.

#### Swift version:

5.7 with xcode 14.0 and 5.6 with xcode 13.4.1

#### Deployment Target:

_What is the Deployment Target of your app? iOS 11

#### macOS version:

macOS Monterey Version 12.5.1

**Comment by ncreated** [comment]
Hello @pritiverma22 👋. Does this issue persist when you try our recent release: [1.12.0](https://github.com/DataDog/dd-sdk-ios/releases/tag/1.12.0) with Xcode 13.4.1?

> **Dependency Manager:**
> linking binary as a static framework.

I assume you use XCFrameworks downloaded from our release page. In `1.12.0` you'll find `Datadog-1.12.0-Xcode-13.4.1.zip` which is meant for Xcode 13.4.1. Unfortunately, due to [this bug in Swift compiler](https://github.com/apple/swift/issues/56573) we can't distribute portable XCFrameworks yet (we will work this bug around in `2.0.0`).

**Comment by pritiverma22** [comment]
I am now using latest version 1.12.0 with xcode 14.0.1 through swift package manager and I don't get these errors anymore.

**Comment by ncreated** [comment]
Thanks for confirmation 🙂, I'm closing this issue then.
